### ISSUE TITLE
Truncated output [PDF]

### ISSUE THREAD

**Issue by yagarwal** [qzind/tray#1100] opened 2023-03-01 13:28 UTC
Hi,
We are trying to validate a POC for our organization where we would like to enable direct printing of labels from the ReactJS web app. But we are having the following problems.

The label is being converted to a PDF in memory and converted to a base64 string. When it is processed through QZTray, we see that the output is truncated from the right. However, if the printer is being used to print the label using the system dialog, the printing is perfect. 

Please find the image of the print below: 
[Doc - Mar 1, 2023 - 6-54 PM.pdf](https://github.com/qzind/tray/files/10861467/Doc.-.Mar.1.2023.-.6-54.PM.pdf)

Could someone please point in the right direction for this? Honestly, we are stumped at this point.

**Comment by lite1979** [comment] 2023-03-01 16:31
@yagarwal This should be a simple fix, but to understand the changes we need to make to the QZ config, we will need the following:

1. original PDF file (base64 is fine)
2. Logs from the PC doing the printing
3. Make/model of the printer, and the exact dimensions of the label paper.
4. Operating System of the PC

If you do not wish to share this on the public issue tracker, you welcome to send them to us at support@qz.io

**Comment by yagarwal** [comment] 2023-03-02 06:03
@lite1979 Thanks for choosing to help us.

Find find the requested information below:

> 1. original PDF file (base64 is fine)

[document.txt](https://github.com/qzind/tray/files/10868077/document.txt)

> 2. Logs from the PC doing the printing

[QZTray.log](https://github.com/qzind/tray/files/10868079/QZTray.log)

> 3. Make/model of the printer, and the exact dimensions of the label paper.

TSC TE244
Roll Width: 92mm
Label Width: 75mm
Label Height: 50mm

> 4. Operating System of the PC

MacOS Ventura

We would be happy to provide any other information you might need.

**Comment by lite1979** [comment] 2023-03-02 15:37
> MacOS Ventura

This explains it. There's an open bug with regards to printing landscape (width>height) oriented PDFs on Mac, particularly with label printers; it boils down to a flaw in Java itself, so it has taken longer to escalate than a problem with our software would have:

https://github.com/qzind/tray/issues/965

Can you tell me if it works with the width and height values switched?

Alternatively, you could use the rawPDF option; I would try the ZPL method:

https://qz.io/docs/raw#zpl-1

Please note: the "pageWidth" parameter in the example above should be the print density multiplied by the physical width of the label, so 3"x203dpi = 609 (verify printer density before calculating)

**Comment by tresf** [comment] 2023-03-02 15:50
Upstream bug report: https://github.com/openjdk/jdk/pull/10808

**Comment by tresf** [comment] 2023-04-19 04:01
Closing as a duplicate of https://github.com/qzind/tray/issues/965.  Work is progressing well and an upstream patches has landed to fix this ([requires Java 21](https://github.com/qzind/tray/pull/1114#issue-1673470394) currently to test) however testing still has some issues.  Quoting our developer:

> [...] the issue is with how the `MediaPrintableArea` and `OrientationRequested` attributes are handled. I was able to fix the issue by removing them. Instead i set the `MediaPrintableArea` and `Orientation` directly to the `pageFormat` object

... although at time of writing this, no matching commit has been pushed and I'm not sure if this will cause regressions, so we have some more work to do.

**Closed by tresf** 2023-04-19 04:01 UTC
