### ISSUE TITLE
HTML prints shrink in size over the course of time

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#505] opened 2019-10-18 00:22 UTC
Multiple users have complained of their HTML size shrinking relative to the size of the label/paper after a certain period of time. We have not been able to reproduce this issue using their HTML and identical environments.

One reported case was on Java 8 (unsure what update), another was on Java 11 (AdoptOpenJDK).

**Comment by tresf** [comment] 2019-10-18 04:32
Quoting the details from one client:

> OS  - Windows 10
> Java Version  - AdoptOpenJDK 11
> QZ Tray Version  - 2.1.0-RC7
> Zipped up application logs (all of them so we can see if this is something the code is doing over time) - attached
> Explanation of how often this occurs. - I print to 3 different printer, usually this happen after I print to Epson Label Printer
> I thought maybe the printing area is larger than paper area so I set up CSS width today but the result is the same
> The HTML is pm-oneclick-label.php which send pm-bloom-single-label-oneclick.php to QZ
> 
> I already changed width on line 9 to width: 179px;
> (normally paper size is 2.5"x2.5" but I also changed to 2.38x2.38 on line 16)
> 
> [The picture](https://user-images.githubusercontent.com/6345473/67066044-b3e66d00-f13e-11e9-8ddb-ea965ca36cf1.jpg) show the label is supposed to fill the entire sticker but it only print on the top left

**Comment by tresf** [comment] 2019-10-18 04:39
For sensitivity reasons, I haven't uploaded the logs, but what I find particularly interesting is a threading error that I've never seen in the logs before:

```
2019-10-10 16:36:02,569 [WARN] Failed to acquire dialog
java.lang.InterruptedException
```

I'm adding this information here incase it turns up more.  It may be isolated to 2.1.0-RC7 as well as both clients are using this same version.

**Comment by momoko-squid** [comment] 2019-10-18 12:25
> Multiple users have complained of their HTML size shrinking relative to the size of the label/paper after a certain period of time. We have not been able to reproduce this issue using their HTML and identical environments.
> 
> One reported case was on Java 8 (unsure what update), another was on Java 11 (AdoptOpenJDK).

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by tresf** [comment] 2019-10-18 12:40
@momoko-squid if you could be so kind as to provide your symptoms that would help.  From what I recall, Fedora and losing printer settings are part of your issue, which may or may not make it a separate problem entirely.

**Comment by momoko-squid** [comment] 2019-10-19 15:33
There's no symptoms. After awhile of unuse, I started to print again, it just happened.
Earlier, I was playing with the manual portrait (no rotation) and scale to fit. But now these 2 params doesn't work anymore.
I don't know what to provide you. If you have anything specific in mind, let me know.

> @momoko-squid if you could be so kind as to provide your symptoms that would help. From what I recall, Fedora and losing printer settings are part of your issue, which may or may not make it a separate problem entirely.

**Comment by tresf** [comment] 2019-10-22 16:09
> I don't know what to provide you. 

On our mailing list, you offer much more details... I'll post it here for you as a courtesy.

> I'm using Fedora [24]'s Gnome-based Printer Settings:
> `/usr/bin/python3 /usr/share/system-config-printer/system-config-printer.py`
> ...
> I'm using this driver:
> http://www.poskeytech.com/upfile/201706/2017060854544449.rar
> ...
> ... after a few days. I rechecked the driver settings returned to the original factory settings (Auto rotation, Scale to Fit is unchecked)

These details offer an important distinction from the originally reported issue.  Details are important especially if the version of CUPS is a factor.

We'll fire up a Fedora machine and escalate as needed.

**Comment by momoko-squid** [comment] 2019-10-27 15:25
> > I don't know what to provide you.
> 
> On our mailing list, you offer much more details... I'll post it here for you as a courtesy.
> 
> > I'm using Fedora [24]'s Gnome-based Printer Settings:
> > `/usr/bin/python3 /usr/share/system-config-printer/system-config-printer.py`
> > ...
> > I'm using this driver:
> > http://www.poskeytech.com/upfile/201706/2017060854544449.rar
> > ...
> > ... after a few days. I rechecked the driver settings returned to the original factory settings (Auto rotation, Scale to Fit is unchecked)
> 
> These details offer an important distinction from the originally reported issue. Details are important especially if the version of CUPS is a factor.
> 
> We'll fire up a Fedora machine and escalate as needed.

**Comment by momoko-squid** [comment] 2019-10-27 15:29
So sorry, I didn't know those info were important.

> > I don't know what to provide you.
> 
> On our mailing list, you offer much more details... I'll post it here for you as a courtesy.
> 
> > I'm using Fedora [24]'s Gnome-based Printer Settings:
> > `/usr/bin/python3 /usr/share/system-config-printer/system-config-printer.py`
> > ...
> > I'm using this driver:
> > http://www.poskeytech.com/upfile/201706/2017060854544449.rar
> > ...
> > ... after a few days. I rechecked the driver settings returned to the original factory settings (Auto rotation, Scale to Fit is unchecked)
> 
> These details offer an important distinction from the originally reported issue. Details are important especially if the version of CUPS is a factor.
I didn't know this could be a factor. Here you go:
**cups-2.1.4-7.fc24.x86_64**
It's an old version of Fedora. It's 3 year old OS,

> 
> We'll fire up a Fedora machine and escalate as needed.

**Comment by momoko-squid** [comment] 2019-10-27 15:33
So sorry. I didn't know those info is important.

> > I don't know what to provide you.
> 
> On our mailing list, you offer much more details... I'll post it here for you as a courtesy.
> 
> > I'm using Fedora [24]'s Gnome-based Printer Settings:
> > `/usr/bin/python3 /usr/share/system-config-printer/system-config-printer.py`
> > ...
> > I'm using this driver:
> > http://www.poskeytech.com/upfile/201706/2017060854544449.rar
> > ...
> > ... after a few days. I rechecked the driver settings returned to the original factory settings (Auto rotation, Scale to Fit is unchecked)
> 
> These details offer an important distinction from the originally reported issue. Details are important especially if the version of CUPS is a factor.

I didn't know CUPS version could be a factor. Here you go:
**cups-2.1.4-7.fc24.x86_64**

> 
> We'll fire up a Fedora machine and escalate as needed.

**Comment by tresf** [comment] 2019-11-11 18:05
As answered on the mailing list, the symptoms could not be reproduced with the exact environment based on the steps given.  That said, we have an outstanding HTML issue we're working on which may be related.

If this is similar to #225, I have a feeling we'll be patching it as part of #513.

Closing since we cannot reproduce with the steps given.

**Closed by tresf** 2019-11-11 18:05 UTC
Labels: needs confirmation
