### ISSUE TITLE
Set real 0 to margins

### ISSUE THREAD

**Issue by hanfry1996** [qzind/tray#985] opened 2022-07-18 18:56 UTC
HI, I try to print a pdf in a Epson FX-1180 (matricial-dot continuous paper invoice), but to top is "cutted", the first line of the pdf.

Y use [Overriding Default Margins](https://qz.io/wiki/pixel#margins) setting it to 0 but still cutting the top of the first line.

Another thing that I try is [Setting Bounds](https://qz.io/wiki/pixel#pdf-cropbox) x=0 and y=-10 (it cut less word until -2, -10 still cutting the same size), in height and width I set the paper size.

I use version 2.1.6, Windows 10.

Thanks.

**Comment by hanfry1996** [comment] 2022-07-18 19:57
> Hi,
> 
> Negative margins are nice for virtual layouts (such as web pages) but unless handled special by the print drivers are unlikely to help much with a physical document.
> 
> Since one can't remove physical limitations of a printer's hardware margins, a baseline must be established.
> 
> Most printers document the physical margins imposed by the hardware in the technical specifications. For this reason, nearly no printers offer a true "zero margin", but some do and others can get very close.
> 
> In the case of a continuous feed printer, I would expect the top margin of a second page to be capable of a near-zero top margin. The first page may offer a "roll back" feature but some continuous feed hardware manufacturers have discouraged this due to increased jamming.
> 
> Regardless, if it's suspected that QZ Tray (or OpenJDK, or Apache PDFBOX, etc) have a bug, first we need to challenge the hardware to prove it's capable.
> 
> Furthermore, most dot matrix implementations still leverage a raw language (e.g. ESC/P) so it may prove hard to find documentation about this problem elsewhere on this specific hardware, since the most common use-cases for fixing margin issues would bypass the driver (and thus 2D content like a PDF) entirely.

Hi, yes, I understood the hardware limitations, but when I use with the Invoice's Program it works, I can print in the same height than I need to print now with QZ, maybe I don't understood something for use QZ printing...

**Comment by tresf** [comment] 2022-07-29 16:51
Hi,

Without steps to reproduce, we'll be closing this bug report.

**Comment by tresf** [comment] 2022-08-03 19:16
Closing due to lack of response.  Please request a re-open if you believe this was closed in error.

**Closed by tresf** 2022-08-03 19:16 UTC
