### ISSUE TITLE
Installing and activate QZ-Tray in Elementary OS Loki

### ISSUE THREAD

**Issue by pudyasto** [qzind/tray#169] opened 2017-02-22 15:02 UTC
Hey, I try to install QZ-Tray in Elementary OS 0.4 Loki. Installing was successful, but qz-tray cannot running. Can you help me how to solve this ?

**Comment by tresf** [comment] 2017-02-22 19:39
Duplicate of https://github.com/qzind/tray/issues/60.

This feature won't ever make it to 2.0, so if you're ok with a beta, you can find one [here](https://github.com/tresf/tray/releases/tag/v2.1.0-dorkbox) or you can [compile 2.1 from source](https://qz.io/wiki/compiling).

**Closed by tresf** 2017-02-22 19:39 UTC
Labels: duplicate
