### ISSUE TITLE
Zebra Printer LP2824 Error on Printing

### ISSUE THREAD

**Issue by dexterhussain** [qzind/tray#601] opened 2020-03-05 20:00 UTC
I have barcode printer ZebraLP2824 when i am using zebra designer software to send this command 
```
I8,A,001


Q203,024
q448
rN
S4
D7
ZT
JF
O
R71,0
f100
N
B49,34,0,1,2,6,106,B,"ABC1234"
P1
```

printer prints without any error but as soon as I use tray it for the first time printer doesnt prints and for the second time printer prints but writes err01 on the barcode as well and printer light become s still amber , I tried printing it to file the code is exact same

**Comment by tresf** [comment] 2020-03-05 20:21
@dexterhussain can you please provide an exact code snippet for us to test using our JavaScript API?  If you're using a flat file, please provide the file as a `.txt` attachment in this bug report.

Also it's less important, but OS, Java version and QZ Tray version can help if the problem is hard to reproduce on our end so please provide this as well.

**Comment by dexterhussain** [comment] 2020-03-07 12:07
This is exact code snippet
I8,A,001


Q203,024
q448
rN
S4
D7
ZT
JF
O
R71,0
f100
N
B49,34,0,1,2,6,106,B,"ABC1234"
P1

**Comment by tresf** [comment] 2020-03-07 15:16
That's not actually a code snippet, that's the raw content.

Please share the code snippet.  If you're using QZ Tray, it should be formatted like follows:

```
 var data = [
   '\nN\n',
   // ... 
   '\nP1,1\n'
];

qz.print(config, data).catch(function(e) { console.error(e); });
```

**Comment by dexterhussain** [comment] 2020-03-09 07:44
I am using QZ Tray in ErpNext which has this builtin

**Comment by lite1979** [comment] 2020-03-09 13:47
@tresf asked you for an exact code snippet. If the EPL print function is "Built In" as you say, you should be able to find the javascript function, copy it, and paste it here.

 Again, OS, QZ-Tray version, and Java version will help move this conversation forward.

To put it simply, if our EPL sample (from sample.html, located in installation directory>demo>sample.html) works, then the problem is likely with the website's integration of QZ-Tray, not with QZ-Tray itself. This may have to be escalated to the ERP next developers.

We have tested extensively on the LP 2844 (same as yours but wider paper), so we are confident that QZ-Tray works well with this printer. 

You are free to share your QZ-Tray logs with us, as that may help us determine the problem as well. The orange light usually indicates a bad command, which could be caused by an extra character or an unescaped quotation mark, apostrophe, et cetera. 

Looking forward to your reply.

**Comment by tresf** [comment] 2020-03-09 15:32
> I am using QZ Tray in ErpNext which has this builtin

Gotcha.  Can you zip and attach the logs then?

https://qz.io/wiki/faq#logs

**Comment by tresf** [comment] 2020-03-11 16:51
I'm closing this issue since multiple requests for code snippets have gone unanswered.

Note, the raw commands can be handled by QZ Tray easily, chances are your issues are environmental.  I recommend contacting the vendor that integrated with QZ Tray for more assistance.  If they're a premium subscriber, you may ask them to escalate the issue to us through our official support channel (support@qz.io).

**Closed by tresf** 2020-03-11 16:51 UTC
Labels: needs confirmation

**Comment by dexterhussain** [comment] 2020-03-14 14:07
let me check
