### ISSUE TITLE
Ubuntu 17.04 (Zesty Zapus) - Unescaped left brace in regex is deprecated, passed through in regex; marked by

### ISSUE THREAD

**Issue by wellington1993** [qzind/tray#142] opened 2016-12-05 18:30 UTC
I have this problem on install.
Sorry if duplicated issue.

Thanks.

**Comment by wellington1993** [comment] 2016-12-05 18:30
Registering with Firefox...
```
   [success] Check QZ Tray AutoConfig exists
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE certData}/ at -e line 1.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE uninstall}/ at -e line 1.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE timestamp}/ at -e line 1.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE commonName}/ at -e line 1.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE trayApp}/ at -e line 1.
   [success] Certificate installed

```

**Comment by tresf** [comment] 2016-12-05 19:06
Duplicate of #133.  For other recent-Ubuntu-type-fixes staged for 2.0.3 release please see:

#130, #131, #132, #133

**Closed by tresf** 2016-12-05 19:06 UTC
Labels: duplicate

**Comment by tresf** [comment] 2016-12-05 19:08
I'd recommend anyone needing this feature now to [compile from source](https://github.com/qzind/tray/wiki/Compiling), which takes only a few minutes.

As a courtsy to yourself, please bump the [`VERSION` string](https://github.com/qzind/tray/blob/2.0/src/qz/common/Constants.java#L12) to something sane such as `2.0.3-RC0` prior to building so that you know you're not on `2.0.2`, but a modified version.

**Comment by tresf** [comment] 2016-12-05 19:13
Note also, the Linux build doesn't use any special signing like [Mac](https://github.com/qzind/tray/blob/2.0/ant/apple/apple-packager.sh.in#L31) and [Windows](https://github.com/qzind/tray/blob/2.0/build.xml#L234:L262) require for installation -- i.e. no real advantage in using the version from our downloads page except for consistency).

**Comment by wellington1993** [comment] 2017-04-24 12:50
@tresf Thanks! Good tip.
