### ISSUE TITLE
RAW base64 PDF printing quality issue.

### ISSUE THREAD

**Issue by atvvarna** [qzind/tray#218] opened 2017-08-01 06:09 UTC
Hello,
I've a problem with printing quality using raw base64 PDF printing. I tried pixel printing but result is the same. Anybody can help?

QZ printed:
![qz](https://user-images.githubusercontent.com/17295454/28811566-cbe98978-7698-11e7-959a-3e09fb13da2e.jpg)

Adobe PDF printed:
![pdf](https://user-images.githubusercontent.com/17295454/28811565-cbe56794-7698-11e7-977c-07d6a634d4b9.jpg)

Regards,
Alex

**Comment by tresf** [comment] 2017-08-01 15:20
Alex,

This seems to be a duplicate of an email you've sent to our mailing list.  We will answer it there instead.

https://qz.io/support/?place=msg%2Fqz-print%2FWTrjIRCflkM%2FlLiuuU0tAQAJ

**Closed by tresf** 2017-08-01 15:20 UTC
