### ISSUE TITLE
Java OutOfMemoryError with multiple Images

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#139] opened 2016-11-20 18:10 UTC
This was tested on Windows to an XPS printer.

When constructing the `data` object to contain 12 images, Java will crash with an `OutOfMemoryError`

Changing the [`launch.opts` to `Xms1024m`](https://github.com/qzind/tray/blob/2.0/ant/project.properties#L9) allowed up to 20 images to print, but crashed when 25 images were attempted.

```
2016-11-16 12:31:37,224 [ERROR] Connection error
java.lang.RuntimeException: Cannot call method public void qz.ws.PrintSocketClient#onMessage(org.eclipse.jetty.websocket.api.Session, java.io.Reader) with args: [org.eclipse.jetty.websocket.common.WebSocketSession, org.eclipse.jetty.websocket.common.message.MessageReader]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.unwrapRuntimeException(CallableMethod.java:93)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:75)
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at qz.printer.action.PrintImage.print(Unknown Source)
	at sun.print.RasterPrinterJob.printPage(Unknown Source)
	at sun.print.RasterPrinterJob.print(Unknown Source)
	at qz.printer.action.PrintPixel.printCopies(Unknown Source)
	at qz.printer.action.PrintImage.print(Unknown Source)
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source)
	at qz.ws.PrintSocketClient.processMessage(Unknown Source)
	at qz.ws.PrintSocketClient.onMessage(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
	... 5 more
2016-11-16 12:32:25,046 [INFO] Connection closed: 1006 - Disconnected
2016-11-16 12:32:25,046 [INFO] Closing all communication channels for QZ Support
```

**Comment by tresf** [comment] 2016-12-02 19:04
@klabarge can you provide the following:
```bat
java -XX:+PrintFlagsFinal -version | find "HeapSize"
```

Specifically `InitialHeapSize` and `MaxHeapSize`.  Divide by `1,048,576` to get it in MB.

Also, can you provide the following:

 * Physical Memory
 * Windows Version + 32-bit or 64-bit
 * Java Version

Last, if your Java version is not 8u111, can you see if this is reproducible with the latest?  @bberenz and I are having a hard time reproducing unless we have less than 4GB ram and I want to see if there's something different between our setups.

**Comment by klabarge** [comment] 2016-12-10 02:18
I couldn't reproduce this on my machine, but I was able to reproduce it with one of my VM's.

Might be worth having @lite1979 providing his specs, as he originally reproduced this.

#### When I could reproduce:
`InitialHeapSize`: 16 MB
`MaxHeapSize`: 256 MB

* **RAM:** 6GB
* **OS:** Windows 7 32bit
* **Java:** 8u111

#### When I could not reproduce:
`InitialHeapSize`: 256 MB
`MaxHeapSize`: 4,076 MB

* **RAM:** 16GB
* **OS:** Windows 10 64bit
* **Java:** 8u91

**Comment by tresf** [comment] 2016-12-10 15:14
@klabarge can we see if 32-bit JVM defaults to a lower heap versus 64-bit JVM?  This would help explain why we don't have more complaints.

**Comment by klabarge** [comment] 2016-12-29 01:43
So, it does look like the 32-bit JVM defaults to a lower heap size. Below are my results using the command you provided.  I used the exact same machine, just different versions of Java.

```bat
java -XX:+PrintFlagsFinal -version | find "HeapSize"
```

| OS               | RAM | JVM                      | `InitialHeapSize` | `MaxHeapSize` |
|--------------|-------|--------------------|-------------------|------------------|
|Windows 10 | 16GB | 8u111 **64-bit** | 256MB               | 4,076MB            |
|Windows 10 | 16GB | 8u111 **32-bit** | 16MB                 | 256MB               |

**Comment by tresf** [comment] 2016-12-29 02:28
@klabarge thanks.  Let's followup with the customer with the crash and see if they currently utilize 32-bit JVM?

**Comment by tresf** [comment] 2017-03-05 02:53
The client confirms this was caused by a 32-bit JVM.  Closing as won't-fix as nearly all clients are capable of upgrading to a 64-bit JVM.

**Closed by tresf** 2017-03-05 02:53 UTC
Labels: bug
