### ISSUE TITLE
Print to Multipurpose Tray?

### ISSUE THREAD

**Issue by FinishingLine** [qzind/tray#1182] opened 2023-09-28 10:06 UTC
I note that it is possible to print to different trays using the `printerTray` config option, but how does one print to the MP tray? This tray doesn't seem to appear when getting the printer details under trays

**Comment by tresf** [comment] 2023-09-28 14:26
Hi,

Can you please be more specific in regards to what the "multipurpose" tray is (e.g. by name) and how it would be listed in the operating system normally (e.g. screenshots)?

**Comment by FinishingLine** [comment] 2023-09-28 15:28
The multi-purpose tray (MP tray, or manual feed tray) - this tray appears on some printers so the paper can be taken from an alternative source, rather than needing to open the cassette draw and change the paper

![image](https://github.com/qzind/tray/assets/40236371/82c0dc3f-44a8-46bf-90ed-27ed46b41faa)

![image](https://github.com/qzind/tray/assets/40236371/8b9039f2-da5d-4b49-bd56-60edc74665d2)

![image](https://github.com/qzind/tray/assets/40236371/5972b889-4f4b-44e5-b772-4bf81fcb9af4)

This particular printer isn't returning a list of trays, namely as I suspect it only has one cassette draw

**Comment by tresf** [comment] 2023-09-28 15:41
Hnmm... We do support -- and have tested -- manual feed trays.  The fact that it's called "Multipurpose" or "MP" shouldn't affect this.

> This particular printer isn't returning a list of trays

Well, I think this may be the underlying problem.  The printer driver is not exposing the tray listing to Java.  This could be for several reasons, but I do not think it's due to the tray type, I believe it's due to the way the device driver is interacting with our software.

This may not be a bug that we can easily fix.   We can make certain troubleshooting recommendations (such as testing out different drivers), but without the exact hardware on-hand (or working with someone on your side that understand Java), this will be pretty tricky to pindown.

**Comment by FinishingLine** [comment] 2023-09-29 08:25
Oh ok, wonder if possibly Kyocera specific as we have a couple of different models of that but couldn't spot that

**Comment by tresf** [comment] 2023-11-01 16:41
@FinishingLine since the C650 offer a wide array of printer driver options, can you please test QZ Tray against the various options?  For example, on Oki's website it lists:
* Bundled software package `Version: 1.0.4`
* PCL6 (PCLXL)  `Version: 1.0.4`
* PCL5  `Version: 1.8.0`
* PostScript  `Version: 1.0.3`

In my experience, different implementations of the printer driver can influence feature compatibility.

> Oh ok, wonder if possibly Kyocera specific as we have a couple of different models of that but couldn't spot that

Hi, this part of your message is a bit confusing, you mean to say "Oki" instead of "Kyocera"?

**Comment by FinishingLine** [comment] 2023-11-02 09:50
Thanks for the update - the image used was used as a "generic" image to show the manual feed tray, sorry for any confusion

It is a Kyocera printer - two models that we have a P2040dn and a MA2100cwfx and have tried on both, but can try different drivers to see if any of these show the tray

**Comment by tresf** [comment] 2023-11-02 16:57
> P2040dn

Thank you for the clarification.  Yes, it appears Kyocera provides many driver options for these printers.

<img width="905" alt="image" src="https://github.com/qzind/tray/assets/6345473/cc1c7287-f99a-4e5a-91c3-ee65d6a02026">

**Comment by tresf** [comment] 2023-12-21 19:04
@FinishingLine closing this.  If you believe the problem is with QZ Tray please let us know and we can reopen it.  We currently use Java's APIs for accessing printer trays so if it is a defect with QZ Tray we'd need to prove that it's actually a defect, since offering a proprietary driver implementation for trays would be considered an enhancement.  We do have some edge-cases that we try to work around driver limitations, but this generally requires some very advanced low-level communication with the win32 API, so we tend to do this on an as-needed basis.

**Closed by tresf** 2023-12-21 19:04 UTC
Labels: needs confirmation
