### ISSUE TITLE
PrintRequestAttributeSet breaks page size macOS

### ISSUE THREAD

**Issue by tresf** [qzind/tray#174] opened 2017-02-26 03:38 UTC
This is simply to track the upstream bug, since Oracle does not make it public information.  This is something broken with the JRE that we discovered and reported August 2016.  Logging it for historical purposes.  No action on our part can be done until the JVM is repaired.

Oracle SR ~~`SR #3-13242741891`~~, `SR #3-17231848201`.

STEPS 
----------------------- 
The issue can be reproduced at will with the following steps: 
Steps to reproduce: 

1. Configure a default printer for the system to use either a virtual printer (such as Lisanet PDF Writer) or a printer capable of printing a 4" x 6" label. 
2. Run the attached `PageSizeBug.java main(...)`, leaving the line "`attributes.add(Chromacity... )`" commented out. 
3. Notice the 4" x 6" page is properly printed. 
4. Un-comment the line "`attributes.add(Chromacity...")`
5. Run the `main(...)` function 
6. Notice the page size has been reset to the printer default (usually `A4` or `Letter`) 

**Open:** Oracle SR `SR #3-17231848201`
[PageBookSizeBug.zip](https://github.com/qzind/tray/files/1909917/PageBookSizeBug.zip)

**Closed:** Oracle SR ~~`#3-13242741891`~~
~~[PageSizeBug.java.zip](https://github.com/qzind/tray/files/801710/PageSizeBug.java.zip)~~

**Comment by klabarge** [comment] 2017-04-11 02:28
Oracle has provided us with a patched JDK for testing. With their patch, we are unable to reproduce this issue.

Oracle said that this fix will be publicly released in JDK 8u152

**Comment by klabarge** [comment] 2017-04-11 03:06
Below is the Java version information from Oracle's fixed build, as @tresf mentioned that logic will need to be added to check for the Java version. Note that this fix is scheduled to be released in JDK 8u152

```bash
$ java -version
java version "1.8.0_121-030417y8167102y8061258"
Java(TM) SE Runtime Environment (build 1.8.0_121-030417y8167102y8061258-20170403100041.alitvino.jdk8u121-b99)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b99, mixed mode)
```

**Comment by tresf** [comment] 2017-04-17 18:42
Currently looking for a `SemVer` parsing library as the one we've written for the 2.1 branch in it's current state is inadequate for backporting.

I found a very nice candidate, but it seems to break on Oracle versioning.  Replacing the `_` underscore with a `.` period does not seem to fix it either.

https://github.com/zafarkhaja/jsemver/issues/37

**Comment by tresf** [comment] 2017-06-28 02:00
Just got an email from Oracle support:

> Sustaining provides an update that we will need to rework the fix in this case. It maybe that the customer has to continue to use their workaround for 8u152. I will keep you posted on the development of Bug 24796421 (private).

This means we could have some problems once 8u152 is released.   Will have to revert the patch.

**Comment by tresf** [comment] 2017-09-19 05:34
Oracle has updated the ticket suggesting the fix will make it into `8u162`.  They have made no guarantee yet, but if they do, we can revert 3af01b6 and change the check to `8u162`.

**Comment by tresf** [comment] 2017-12-05 01:45
This is now slated for `8u172`, this time the fix is expected to stick.  Will revert 938c9cd and change the check to `8u172.

**Comment by tresf** [comment] 2017-12-05 06:27
Closed via d79b3ff.

**Comment by tresf** [comment] 2017-12-07 21:40
Oracle has notified us this will make the January release.  Lowered feature to be enabled in `Java8u162` instead of `Java8u172` via 2873666.

**Comment by tresf** [comment] 2018-04-05 23:32
This is still broken in Java8u162.  Reopening `SR 3-13242741891`, thus reopening this.

**Comment by tresf** [comment] 2018-04-13 04:07
Turns out Oracle's fix worked for QZ Tray v2.0.2, but we went and found a way to break it again in QZ Tray v2.0.3.  We're discussing this under `SR 3-13242741891` currently.  We believe the `Book` class to be the cause but we're not 100% sure on that yet.  Will post updates as we find them.

**Comment by tresf** [comment] 2018-09-04 14:59
Oracle has patched this in a private build for us again, here's their latest update in `SR 3-17231848201`:

> [Oracle has] attached a Fix Verification Binary for you to try.  It is named [ `fvb1-jdk-8u181-290818y8201818-macosx-x86_64.dmg` ].  Download it from the attachments section of this service request.  It should correct the problem but it is still a preliminary fix.  It is not ready for production use.  While we ask you to try it to see if it corrects the problem, once you have the results, you should not use it any further.

@klabarge can you please test?

**Comment by klabarge** [comment] 2018-09-06 00:00
@tresf I tested Oracle's patched Java version `fvb1-jdk-8u181-290818y8201818-macosx-x86_64.dmg` against the [test case you provided](https://github.com/qzind/tray/files/1909917/PageBookSizeBug.zip) and it does appear to fix the bug.

I also tested by removing the [`attributes.clear();` logic](https://github.com/qzind/tray/blob/2.0/src/qz/printer/action/PrintPDF.java#L110-L113) and running against the provided JDK.

Let me know if you would like me to run any further tests

**Comment by tresf** [comment] 2018-09-27 21:39
Oracle can't yet guarantee a release version that fixes this.  Once they have a version number, we'll bump our code to use it.

**Closed** 2018-10-01 02:06 UTC
Labels: upstream
