### ISSUE TITLE
PDF generator bug with OpenSans font from version 2.0.6.

### ISSUE THREAD

**Issue by Berek1987** [qzind/tray#366] opened 2018-10-15 16:17 UTC
Hi guys,
I just discovered a serious issue for us.
Yesterday we deployed new PDF template for our tickets, with new font - Open Sans from Google, which is embedded in the document.
Previously we were using Dejavu Sans, without any problem across all your QZ 2 versions, and it always printed correctly.

With this new font, however, QZ from version 2.0.6. is corrupting the document (both 2.0.6. and 2.0.7.).
QZ 2.0.5. is printing the same document perfectly, as it is supposed.

Below are several documents:
1. the original document sent to QZ, 
2. resulting document after sent to Microsoft PDF printer,
3.  QZ log.

Notice that the document is corrupted in exactly the same way when sending directly to real printer, so it is not an issue related to Microsoft PDF printer.

It is somekind of bug in interpretation of PDF, that was introduced in version 2.0.6.
Lower below is my code for printing.

Thanks for your help!

[QZ_2_0_7_original.pdf](https://github.com/qzind/tray/files/2479570/QZ_2_0_7_original.pdf)
[QZ_2_0_7_printed_to_Microsoft_PDF.pdf](https://github.com/qzind/tray/files/2479569/QZ_2_0_7_printed_to_Microsoft_PDF.pdf)
[QZ_2_0_7_printed_to_Microsoft_PDF.log](https://github.com/qzind/tray/files/2479571/QZ_2_0_7_printed_to_Microsoft_PDF.log)

base64 printing
code example

       `printPDF: function(pdfB64) {
        var config = qz.configs.create(globalPrinter.name, {
            size: {width: 8.27, height: 11.69},
            units: 'in',
            scaleContent: false,
            rasterize: false,
            duplex: false,
            jobName: "Printing Entrio ticket"
        });
        var data = [{
            type: 'pdf',
            format: 'base64',
            data: pdfB64
        }];
        qz.print(config, data).catch(function(e) {
            console.error(e);
            send_log(e, "print_error");
        });

    }`

**Comment by tresf** [comment] 2018-10-15 16:57
In https://github.com/qzind/tray/commit/71c9e1f3aa4b06dc87b6d889dc38c1eb7798344c we upgraded the PDFBOX library but that was part of 2.0.5, so if your test results are accurate, PDFBOX may not be the culprit.  We'll do some unit tests with and without QZ Tray and share our results.

**Comment by Berek1987** [comment] 2018-10-15 17:57
Thanks a lot for your quick response!
However, I'm still not sure what to do next what is exactly the problem.
I downloaded Open Sans directly from Google, it should be a stable font, also I'm using it in TCPDF PHP  library, exactly the same as I used to generate it with DejavuSans font.
[dejavusans_original.pdf](https://github.com/qzind/tray/files/2479942/dejavusans_original.pdf)

Do you think it's some specific problem with this exact font?

I understand it's not the bug on your side, but I would be really grateful if you could direct me to what to try to get OpenSans display correctly in my PDFs.

Thanks a lot,

**Comment by tresf** [comment] 2018-10-15 18:15
Before we dive deeper I wanted to confirm the observed regression.... I can confirm that the font renders correctly with QZ Tray v2.0.5.  We have fixed several bugs with PDF printing since v2.0.5 and it is likely that the correct printing was a result of an underling bug.  Here's the code difference from v2.0.5 and v2.0.6: https://github.com/qzind/tray/compare/v2.0.5...v2.0.6.  Note, there's one slightly change that was removed because it caused an edge-case regression the color instance: https://github.com/qzind/tray/commit/9ed2203231102418c7c2f88a6dcf106bd50521ce.  I would guess that this is the commit which caused the regression.

Back to the solution... 

I (all of us here at QZ) don't know the underworkings of PDFs well enough to provide fixes on the PDF-generation level.  For that we usually need help with this stuff from either you (i.e. steps to reproduce the creation of this PDF) or as a fallback, consulting from the Apache PDFBOX project (something that has no guarantee in turnaround time but has been stellar in our experience).  This is because it's not trivial to troubleshoot so often it's easiest living as a PDFBOX bug report despite us not actually knowing if it's a bug.  Tillman Hauscherr has kindly helped us resolve several issues, some issues with the PDF and some core issues with PDFBOX.  They also have a mailing list, `users@pdfbox.apache.org`.

I'll start by quoting a similar issue (which was reported resolved) in the commit which introduced the error message we're seeing [PDFBOX-3344](https://issues.apache.org/jira/browse/PDFBOX-3344).

> As Tilman noted, the problem with the etichette.pdf file is that it contains a `CIDFontType2` with a `FontFile2` which contains an `OTF` instead of a `TTF`. We've seen these kinds of mix-ups before, and Acrobat tends to resolve them.
> 
> OpenType fonts are special, because OTFs technically come in two flavours, PostScript and TrueType. The PostScript flavour begins with the ASCII sequence OTTO and is generally referred to as an `OTF` and given the extension `.otf`, while the TrueType flavour begins with a fixed-point version number and is given the extension `.ttf`. In PDFBox the `OpenTypeFont` class reflects this dual purpose, behaving as both a TrueTypeFont, and providing the ability to access the embedded `CFF`. If you try to parse `TTF` outlines from a `CFF`-flavoured font, you're going to get errors about the local and glyf tables being missing, likewise if you try to extract the `CFF` table form a `TTF-flavored` font.
>
> Most of PDFBox was built around `CFFFont` and `TrueTypeFont`, with `OpenTypeFont` being added more recently to accommodate exactly this kind of "wrong FontFile" problem, where we have to second-guess the PDF file. Note that it's sometimes necessary to treat fonts as both - to using the `cmap` table for encoding, but the `CFF` for rendering glyphs.

What I find interesting is that a later comment shows another user having a similar problem and asking how to escalate... 

> I'm a newbie with font types and I have the same issue with a `PDCIDFontType0` (this bug fix is for `PDCIDFontType2`). Should I open a new issue?. I have locally changed the code for `PDCIDFontType0` and now it seems to be working (I'm not really sure if this is a PDFBox issue or a problem with my pdf/fonts).

And Tilman's answer is pretty straight forward... 

> Make sure you're using the latest version. If it still happens, please open a new issue, attach your file and a minimal code segment, unless it can be reproduced with `PDFDebugger`.

PDFBOX's general stance is to try to mimic the behavior of Acrobat, so they may be willing to fix this long-term.  Even if they don't, they're likely to make advisement where it's going wrong.

In the meantime, if you have a way for us to mimic the PDF that you're creating, we can spend some trial-and-error resources on our end.  We're always happy to learn, it makes our product and our service better.

**Comment by Berek1987** [comment] 2018-10-15 20:48
Wow, you suprise me every time with a customer level and responsiveness you're providing to your customers, thanks again for that! :)

Regarding the issue, I literally know nothing about fonts and PDF, so it was a long day for me debugging, with almost no results.
I'm not sure what you mean by mimicing the behaviour - I'm generating PDF's with TCPDF library in PHP for my web system, which I am testing locally on my laptop. But I don't see any way of you reproducing my whole setup and whole source code.

Instead, I generated 3 different PDFs below, with 3 different fonts embedded - with exactly the same procedure.
DejavuSans and Roboto are working fine, only OpenSans is not printing as it should.
That's really strange, because one could conclude that there is a problem with font, but it's one of the most popular modern fonts, used all around the globe. And supported by Google.

Btw, in TCPDF, I'm using the following command for embedding the font:
```
$pdf->setFontSubsetting(true);
$main_font = $pdf->addTTFfont(realpath(BASEPATH . '../../public_html/fonts').'/open_sans/OpenSans-SemiboldItalic.ttf', 'TrueTypeUnicode');
```
After that, I'm calling the font with a standard command, and setting it's size:
`
$pdf->SetFont($this->main_font, '', 11);
`
But it's the same if I let TCPDF create it's font source files, or if I create them by myself through a service like http://fonts.snm-portal.com/.
Also, if I remove parameter "TrueTypeUnicode", everything is the same.

Just to note once again, all generated PDF's are perfectly readable and printable in several different programs and computers.

It's only that QZ / PDFbox has some problems with OpenSans font :(

Here are the examples so you can try and push them through QZ for yourself.
And it's totally unbelievable that 2.0.5. prints it perfectly and that it was because of a "bug" in that version :/

[test__dejavusans.pdf](https://github.com/qzind/tray/files/2480450/test__dejavusans.pdf)
[test__roboto.pdf](https://github.com/qzind/tray/files/2480451/test__roboto.pdf)
[test__opensans.pdf](https://github.com/qzind/tray/files/2480452/test__opensans.pdf)

Thanks!
Bero

**Comment by tresf** [comment] 2018-10-16 03:09
Unit test:

Setup the environment:
```bash
# Install TCPDF
curl -sS https://getcomposer.org/installer | php
php composer.phar require tecnickcom/tcpdf

# Fetch OpenSans
git clone https://github.com/google/fonts

# Fetch PDFBOX
curl -O http://apache.spinellicreations.com/pdfbox/2.0.12/pdfbox-app-2.0.12.jar

```

Create `test.php`
```php
<?php
   require(__DIR__ . '/vendor/tecnickcom/tcpdf/tcpdf.php');
   $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
   $pdf->setFontSubsetting(true);
   $font = TCPDF_FONTS::addTTFfont(__DIR__ . '/fonts/apache/opensans/OpenSans-SemiboldItalic.ttf', 'TrueTypeUnicode');
   $pdf->SetFont($font, '', 36);
   $pdf->AddPage();
   $pdf->SetXY(100, 100);
   $pdf->writeHTML('<h1>OpenSans-SemiboldItalic</h1>', true, false, false, false, '');
   $pdf->Output(NULL, 'I');
?>
```

Generate the PDF:

```bash
php test.php > test.pdf
```

Print the PDF using Apache PDFBOX:
```bash
java -jar pdfbox-app-2.0.12.jar PrintPDF -printerName "Microsoft Print to PDF" test.pdf
# replace "Microsoft Print to PDF" with a valid printer
```

@Berek1987 can you confirm that this test result passes?  It's just a very basic example of loading the font, making a PDF and printing it with PDFBOX.

Note, on Windows some commands such as `curl` are not available on Windows so the example may need to be modified.

**Comment by tresf** [comment] 2018-10-17 17:36
@Berek1987 just checking to see if the use-case above works for you or not.  It uses the CLI version of PHP to render the PDF.

There may be notable differences to consider such as:
* Font size
* The source of the font itself (we're grabbing it from GitHub)
* The version of TCPDF (we're using latest from composer)
* The HTML tags we're using (likely unrelated but worth noting and/or comparing)

I'd like to close this out as the above unit tests show that PDFBOX and QZ Tray are behaving properly, but I also want to be cognizant of any bugs and not close prematurely.  Please let me know your findings.

**Comment by Berek1987** [comment] 2018-10-17 17:58
Hi Tres,
if I got you right, your test from above resulted in correct PDF printed out through QZ?
Then it might be the newer TCPDF version or some other syste-related difference...

I fell into some extremely busy period and I'm not sure I'll find time to recreate your steps in the following days. Temporarily we replaced Open Sans in our PDFs with Roboto which is similar.

I'll try to recreate this ASAP and let you know the results.

**Comment by tresf** [comment] 2018-12-04 14:50
> I'd like to close this out as the above unit tests show that PDFBOX and QZ Tray are behaving properly

Closing as `invalid` since the bug is not reproducible using the latest tools.  Feel free to continue discussion here.  I'd be happy to reopen with steps to reproduce the issue.

**Closed by tresf** 2018-12-04 14:50 UTC
Labels: upstream
