### ISSUE TITLE
pdf print with Portrait orientation doesn't work on Mac

### ISSUE THREAD

**Issue by CindyLulu** [qzind/tray#335] opened 2018-06-15 13:01 UTC
I want to print a portrait label with 2.36 x 1.18  size using Zebra printer. It works correctly in Windows, but the label content looks very small in Mac.

Here' s the sample code include pdf data(2.36 x 1.18). 
[sample.txt](https://github.com/qzind/tray/files/2106041/sample.txt)

Please open qz client of 2.0.6 version, and help update config of sample.html like below:
orientation: portrait
width: 1.18
height: 2.36

Then copy the content from sample.txt, and execute it in web console.
Here's what I got by switching the width and height.
![fa667674d948689db9c4db5ce319bf7f](https://user-images.githubusercontent.com/7055387/41469320-4d2a9252-70df-11e8-8705-37c39a02f05b.jpg)

**Comment by tresf** [comment] 2018-06-15 15:35
This generally means Mac can't find that label size when printing.  Also, it appears you're using `rasterize: true` (default).

* Can you please specify `rasterize: false` ?  This is a setting that default to `true` on 2.0.0 due to a bug with MacOS and PDFBOX which Oracle has since provided a patch for and is no longer needed.
* Instead of `2.36 x 1.18`, can you use `{ size: { width: 2.3622, height: 1.1811} }` respectively (60mm x 30mm)?  Although Windows may be able to match the form size on approximation, Mac has generally been more picky.
* Why is the source PDF `3.0 x 1.15`?  I would expect the PDF and label size to be identical.  Please let us know which size is intended.  We have a `scaleContent: true` flag in the config that can be used but first we'd need to know if this is desired.

I've extracted the Base64 PDF here so that others can reproduce with a single file instead of pasting the Base64 block of data:

[issue_335.pdf](https://github.com/qzind/tray/files/2106604/issue_335.pdf)

**Comment by CindyLulu** [comment] 2018-06-20 11:11
Hi @tresf , thanks for your reply!
I've tried rasterize: false, doesn't work for me.
When I trying to set different label size, it works for me when I set the both width and height in the sample.html same with the actual width of the pdf, very odd.
Here's the portrait file (2.62" x 1"), only setting the width and height with both value 2.62. Then the portrait orientation print will work.
[abc.pdf](https://github.com/qzind/tray/files/2118994/abc.pdf)

Could you try this in Mac using zebra printer? Is this a bug?

**Comment by tresf** [comment] 2018-06-20 13:33
> Could you try this on Mac using zebra printer? Is this a bug?

We don't have the same labels, so this will be hard to reproduce, but we need the exact paper dimensions before reproducing anything.

We need the dimensions that the paper manufacturer sells these at in exact `in` or exact `mm`.

The fact that putting the wrong height fixes this is certainly strange but the way Java interacts with the CUPS printing subsystem on Mac is very, very buggy so we can only raise an issue with Oracle if we have the exact steps to reproduce, and part of that is matching the exact paper dimensions and feeding the application the dimensions that the driver would expect.

Windows has a nice feature where a custom form can be defined and Java will use the closest match.

I'm not sure how CUPS does this and we only QA against 4x6 in our lab so if you can link a place to buy the paper, we can see how far we can get. :+1:

**Comment by CindyLulu** [comment] 2018-06-21 01:59
Yes, @tresf , I also believe that's a jvm issue when communicating with CPUS driver on Mac.
To reproduce this issue I think we can use any label size larger than the actual pdf size, using 2.625" x 1.25" (common zebra label) or 4 x 6 are both the same.
The issue also is also existed for other pdf size like 2.15" x 1.15" and more.

The issue is not related with QZ side, but if other person also meets with the same issue, maybe we could add the fix in QZ library to forbid this issue.

**Comment by tresf** [comment] 2018-06-21 02:02
> To reproduce this issue I think we can use any label size larger than the actual pdf size, using 2.625" x 1.25" (common zebra label) or 4 x 6 are both the same.
The issue also is also existed for other pdf size like 2.15" x 1.15" and more.

No, 4x6 works fine.  We test this each release.

> I also believe that's a jvm issue when communicating with CPUS driver on Mac.

I don't yet see any evidence of that.  Please provide a link to purchase the paper so that we can reproduce this issue, otherwise it will be closed as `invalid`.

**Comment by CindyLulu** [comment] 2018-06-21 06:38
sure, please try the label below with size 2.25 x 1.25 to print the attached pdf.
https://www.amazon.com/Direct-Thermal-Eltron-Compatible-Labels/dp/B072B9VBQ5/ref=sr_1_6?ie=UTF8&qid=1529562747&sr=8-6&keywords=zebra%2Blabel%2B2.25%2Bx%2B1.25&th=1
[225_115.pdf](https://github.com/qzind/tray/files/2122423/225_115.pdf)

**Comment by tresf** [comment] 2018-06-21 14:56
> I want to print a portrait label with `2.36 x 1.18` size using Zebra printer. It works correctly in Windows, but the label content looks very small in Mac.

>> please try the label below with size `2.25 x 1.25` to print the attached pdf.

Thanks.   We'll order the labels on priority and see how far we can get.

On a side note, I'd like to add that these above statements are what are concerning me. Can you please clarify the technical requirements?  I don't see `2.62` or `2.36` in the label description and the original bug report makes this seem like a hard requirement.

We have seen some cases on MacOS where the print dialog must be opened once and the smaller label size must be selected prior to Java locating this size.  That was the case with the [`JAPANESE_POSTCARD` hack that we used to use in 1.9](https://github.com/qzind/qz-print/commit/579a96d523c22368653d1caa079e5f24222ba434) to get 4x6 labels to print.

Since then we've had great success with using the [`MediaPrintableArea`](https://stackoverflow.com/a/40702698/3196753) technique instead.  Proof of this is that if you use the Lisanet PDF printer, you can print to virtually any document size.  CUPS handles this well and we use it for the baseline of our testing.

There may be a bug with the page dimensions that the Zebra driver exposes to CUPS and having the exact label size will allow us to reproduce that and make recommendation.

To that point, the exact paper size is paramount to solving this problem.  If you can offer an explanation as to the above discrepancies, that will give us the information needed to test, reproduce, escalate accordingly. :)

**Comment by lite1979** [comment] 2018-06-21 19:46
Cindy:

Label stock has been ordered, and it will arrive Wednesday to Friday of
next week (6/27-6/29).

Did you turn the printer off before connecting to the Mac after using it in
Windows?  Also, what driver are you using in Mac?  Some recent versions of
CUPS have not had the correct Zebra driver, so I have referred a few
non-QZ-related inquiries to the PPD file located here:

https://gist.github.com/JakeVdub/3cce5604cf82d0172a4c2ee267e6b677

I will update with results of my tests once I have the correct label stock



On Thu, Jun 21, 2018 at 10:56 AM, Tres Finocchiaro <notifications@github.com

**Comment by CindyLulu** [comment] 2018-06-26 06:34
Thanks @lite1979 , I usually don't turn off the printer before connecting to Mac, and I've tried turn off and turn on, still not work. 
My Printer is zebra LP 2844.
The CPU version I installed is 2.2.5
The related model I installed is Zebra EPL2 Label Printer.
Java version: jdk-8u171

**Comment by tresf** [comment] 2018-06-29 17:46
Paper arrived at @lite1979's place today.  We'll begin testing now.

**Comment by lite1979** [comment] 2018-06-29 19:45
@cindylulu

Are your labels aligned to the left, or are they centered in the printer?

**Comment by CindyLulu** [comment] 2018-06-30 06:54
Hi @lite1979,
The labels are centered in the printer.
When I disconnect my printer, I can see the pdf preview in my zebra print queue. The issue looks the same with my printed labels.

When I set
1) Orientation: Portrait
    Width: 1.25
    Height: 2.25
![image](https://user-images.githubusercontent.com/7055387/42122494-5fdd4628-7c75-11e8-8b20-4ef3b72b85fc.png)

2) Orientation: Portrait
   Width: 2.25
   Height: 1.25
![image](https://user-images.githubusercontent.com/7055387/42122495-69854a40-7c75-11e8-9352-b7962f6c17ce.png)

**Comment by lite1979** [comment] 2018-06-30 16:41
Orientation problem confirmed, but I'm still having trouble reproducing the results for W: 1.18, H: 2.36, hence my previous question.

![img_20180630_123504550](https://user-images.githubusercontent.com/3408749/42127208-3d10d9b0-7c62-11e8-85a6-6d03c8ae632c.jpg)

This is indeed strange.  I asked about the offset of the paper because my results seem to behave as though the paper is expected to be justified to the left (all content to the right of the 2.25" mark is missing).  I think this is a driver problem, but I will confirm after I test with Windows in a short while.

**Comment by lite1979** [comment] 2018-06-30 17:11
Windows results below:

![img_20180630_130156102](https://user-images.githubusercontent.com/3408749/42127396-0917c3e0-7c66-11e8-8828-282713a5b4ce.jpg)

It would appear that not only is the orientation affected using MacOS, but the offset is incorrect for the smaller paper size with my driver (LP2844-Z; not LP2844). We will investigate further regarding orientation in QZ-Tray and get back to you.  

There are clearly some problems related to the driver in Windows vs. driver in Mac regarding my blank space to the right, but that is a separate issue, and out of our control at this time.

![img_20180630_130932512](https://user-images.githubusercontent.com/3408749/42127455-1498f058-7c67-11e8-8d9c-259fae78b572.jpg)

**Comment by CindyLulu** [comment] 2018-07-02 08:55
@lite1979 
Thank you so much for your verification, look forward for your further investigation on the Mac orientation issue.
BTW, the current label you use is 2.25 x 1.25 right? so could you use a pdf not larger than label to print? 
You can try https://github.com/qzind/tray/files/2122423/225_115.pdf I uploaded before, the size is 2.25 x 1.15. This will help resolve the offset issue for windows I think.

**Comment by tresf** [comment] 2018-09-27 21:07
@lite1979 how to proceed on this?

**Comment by tresf** [comment] 2019-03-05 19:35
I have a feeling this issue is linked to #428.

**Comment by tresf** [comment] 2019-03-06 15:36
@CindyLulu sorry for the delay...

I have a strong feeling this is related to #428.  Can you re-test?  Here's an installer with the improved landscape logic from #428. https://github.com/tresf/tray/releases/tag/v2.0.9-landscape

**Comment by tresf** [comment] 2019-03-07 20:18
@CindyLulu I'm closing this report out since we're not able to directly reproduce it.  Feel free to chime in at your earliest convenience.

**Closed by tresf** 2019-03-07 20:18 UTC
Labels: bug, needs confirmation
