### ISSUE TITLE
Ubuntu Tray Icon

### ISSUE THREAD

**Issue by dsanders11** [qzind/tray#127] opened 2016-11-06 03:29 UTC
I'm seeing some issues with the tray icon under Ubuntu with QZ Tray 2.0.1. I have Chromium set to full screen on startup for a kiosk application we're making, and when this happens the QZ Tray icon is visible over top of the full screen until you click it (hard to do with a touch screen since it is small and at the top) and then back to Chromium, which makes it disappear.

You can also see this bad behavior if you use 'Super + W' on the keyboard to view all windows. The top panel disappears along with the tray icons, except for QZ Tray, which has the icon stay visible the whole time. This is on Ubuntu 16.10.

It may be a decent chunk of work, but you may want to consider using the project [dorkbox/SystemTray](https://github.com/dorkbox/SystemTray) to handle system tray icons, as it aims to solve cross-platform issues and has support for AppIndicators which is what the ideal solution on Ubuntu entails.

Switching to that project may also fix the tray icon issue in #50 and would also probably remove the need for the Ubuntu-specific code which tries to deal with tray icon issues.

**Comment by tresf** [comment] 2016-11-06 03:31
@dsanders11 https://github.com/dorkbox/SystemTray/issues/22#issuecomment-249657232 :)

Duplicate of #60 

Oh and 👍

**Closed by tresf** 2016-11-06 03:31 UTC

**Comment by tresf** [comment] 2016-11-06 03:36
@dsanders11 also, a stop-gap may be to simply set a timer which re-sets the icon.  Right click where the icon **was** and click "Reload".  IIRC, the icon will re-draw just fine because it cycles through red, yellow, green icon.  Anyway, we're working with dorkbox on 16.10 so hopefully that will put it to rest permanently.

**Comment by dsanders11** [comment] 2016-11-06 03:40
> Anyway, we're working with dorkbox on 16.10 so hopefully that will put it to rest permanently.

Awesome. Apologies for the duplicate issue, I tried searching before creating it but didn't identify #60 as being related to this issue from the title.

Thanks for the fast response!

**Comment by tresf** [comment] 2016-11-06 03:57
> didn't identify #60 as being related to this issue from the title

Fixed. 👍 

> 
![image](https://cloud.githubusercontent.com/assets/6345473/20035255/82b9c762-a3b3-11e6-8dcd-470fc578c60a.png) **tresf** changed the title of #60 from **Gala/Pantheon desktop environment support** to **Better Linux SystemTray Support (Unity/Gala/Pantheon)** just now
