### ISSUE TITLE
No native M1 Mac build

### ISSUE THREAD

**Issue by HVR88** [qzind/tray#761] opened 2021-02-24 03:09 UTC
Read the subject.  It's 4 months on since the M1 shipped to consumers. 10 months since developer systems shipped.  

QZ doesn't run natively on M1 and on top of that doesn't work (at all) with native M1 Firefox.

**Comment by tresf** [comment] 2021-02-24 04:52
Duplicate of #591.

**Closed by tresf** 2021-02-24 04:52 UTC

**Comment by tresf** [comment] 2021-02-24 04:59
> QZ doesn't run natively on M1 and on top of that doesn't work (at all) with native M1 Firefox.

Firefox 88, which has dual arch support for ARM64 + x86_64 works fine with Rosetta 2 in my testing.  If you are having issues with it, I would recommend opening a dedicated bug report with steps to reproduce.

```
file /Applications/Firefox.app/Contents/MacOS/firefox
/Applications/Firefox.app/Contents/MacOS/firefox: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm6
/Applications/Firefox.app/Contents/MacOS/firefox (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/Firefox.app/Contents/MacOS/firefox (for architecture arm64):	Mach-O 64-bit executable arm64
```

![image](https://user-images.githubusercontent.com/6345473/108949695-e0fc3700-7632-11eb-8faf-f8e2e650cca0.png)
