### ISSUE TITLE
Large string QR Code does not print completely in ESC/POS

### ISSUE THREAD

**Issue by pedrollmatias** [qzind/tray#484] opened 2019-08-28 16:22 UTC
I'm trying to use QZ Tray to print raw ESC/POS commands. I'm having trouble in printing a large QR Code string. The example provided on the documentation (https://qz.io/wiki/2.1-raw-printing#escpos-qr-code) works fine. However, I need to print a string with about 150 characters. The problem is when I replace the ```qr``` in the example to my qr, the QR isn't fully printed. An QR Code is printed, but the rest of string is printed as normal text, as if the qr considered had been cut until a certain size (which is considered to generate QR) and the rest is ignored. Am I missing something?

**Comment by tresf** [comment] 2019-09-03 18:22
@pedrollmatias thanks for reporting.  I was able to reproduce the bug with your code snippet.  I believe it's a duplicate of #415, where raw data sent from CUPS is becoming corrupted.  Providing `{ altPrinting: true }` seems to correct the issue.

Note, while reproducing, I decided to improve the QR length calculation for QR codes over 256 characters.  The wikis have been updated to reflect this.

https://github.com/qzind/tray/wiki/2.0-raw-printing#escpos-qr-code
https://github.com/qzind/tray/wiki/2.1-raw-printing#escpos-qr-code

**Comment by pedrollmatias** [comment] 2019-09-05 17:03
Hi Tres,

Thank you for the answer and sorry for my delay. Actually I'm using Windows
as OS and I didn't try to print on Linux (because of printer's driver), so
*altPrinting* didn't work. I tryied to modify the size parameter and its
calculation as you suggested, but I didn't succeed (the print continues as
in the image above). I also tried to set size parameters manually, and
sometimes I could print a bigger string, but I couln't find any logic.

Regards,
Pedro Matias

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em ter, 3 de set de 2019 às 15:22, Tres Finocchiaro <
notifications@github.com> escreveu:

**Comment by tresf** [comment] 2019-09-05 18:06
@pedrollmatias thanks for the additional information.  Reopening and I will test this code again using Windows.

**Comment by tresf** [comment] 2019-09-05 18:21
@pedrollmatias my apologies.  I had made another code change in my testing and never published it.  Here is it.. 

```js
var config = qz.configs.create("Epson TM-T88VI", { encoding: 'ISO-8859-1', altPrinting: true });
```

What's happening is the UTF8 characters start to corrupt unless `{ encoding: 'ISO-8859-1' }` is forced.  Since this only occurs at certain byte sequences, it will result in sporadic behavior when we're using hex to represent length.  The issue is described in detail here: #155.

I've updated the wikis to reflect this requirement.  Sorry for the oversight and thanks for reporting.

**Closed by tresf** 2019-09-05 18:21 UTC

**Comment by pedrollmatias** [comment] 2019-09-05 18:47
@tresf Using ```{ encoding: 'ISO-8859-1' }``` the QRCode works perfectlly, but another problem came up. I was using ```{ encoding: 'CP850' }``` because I had to print some special characters such as ```ç```, ```ã```, ```é``` ([docs](https://qz.io/wiki/raw-encoding#escpos-western-european), but using this encoding the QRCode became corrupt. However, using ```{ encoding: 'ISO-8859-1' }``` I get some strange characters instead the specials one. Is possible to have both working (special characters and QRCode)?

**Comment by tresf** [comment] 2019-09-05 19:28
@pedrollmatias I will test these characters and let you know. #155 describes how this technique can cause issues when combined with other encoding techniques.  I'll see if I can get both to work and update this thread.

**Comment by tresf** [comment] 2019-09-05 20:07
@pedrollmatias can you please try:

```diff
- //'\x1D' + '\x28' + '\x6B' + size1 + size0 + '\x31' + '\x50' + '\x30' + qr, // <Function 080> send your data to the image storage area in the printer
+ { type: 'raw', format: 'hex', data: 'x1Dx28x6B' + toHex(qrLength % 256) + toHex(Math.floor(qrLength / 256)) + 'x31x50x30' }, qr, // <Function 080> send your data to the image storage area in the printer
```

... and add this helper function:

```js
function toHex(number) {
   var hex = (Math.abs(number)).toString(16);
   while (hex.length < 2) {
      hex = "0" + hex;
   }
   return "x" + hex.substring(0, 2).toUpperCase();
}
```

What this does is, instead of using the encoding to fix the data, it sends the data in an alternate "hex" format which bypasses the UTF8 conversion bug.

**Comment by pedrollmatias** [comment] 2019-09-05 21:17
@tresf There's a piece of the code which I'm trying to run:
```javascript
function initPrinter() {
    return '\x1B' + '\x40';
}

function toHex(number) {
    var hex = (Math.abs(number)).toString(16);
    while (hex.length < 2) {
        hex = "0" + hex;
    }
    return "x" + hex.substring(0, 2).toUpperCase();
}

function qrCodeGenerator(qrSource) {
    const dots = '\x07';
    const qrLen = qrSource.length + 3;
    return '\x1D' + '\x28' + '\x6B' + '\x04' + '\x00' + '\x31' + '\x41' + '\x32' + '\x00' +
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x43' + dots +
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x45' + '\x49' +
        '\x1D' + '\x28' + '\x6B' + toHex(qrLen % 256) + toHex(Math.floor(qrLen / 256)) + '\x31' + '\x50' + '\x30' +
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x51' + '\x30' +
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x52' + '\x30';
}

function dataToPrint() {
    const qrSource = 'http://hnfce.fazenda.mg.gov.br/portalnfce/nfce/qrcode?p=31190810958795000107650010000000251217012903|2|2|1|85205AA554B70B9B17FAA9067BFB7F03599A79FD';
    return [
        {
            type: 'raw',
            format: 'hex',
            data: [
                initPrinter(),
                qrCodeGenerator(qrSource),
            ]
        }
    ];
}
```
and here I send data to print:
```javascript
const config = qz.configs.create(printerName, { encoding: 'CP850', altPrinting: true });
qz.print(config, dataToPrint());
```
but I'm getting this error:
```
Cannot parse (HEX)["\u001b@","\u001ba\u0001\u001d(k\u0004\u00001A2\u0000\u001d(k\u0003\u00001C\u0007\u001d(k\u0003\u00001EI\u001d(k\\x96\\x001P0\u001d(k\u0003\u00001Q0\u001d(k\u0003\u00001R0\u001ba\u0000"] as a raw command
```
Am I missing something?

**Comment by pedrollmatias** [comment] 2019-09-05 21:21
BTW, I found [this ESC/POS function](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=32) which allows to select character code table. Is this related to encoding? I tries to set ```{ encoding: 'ISO-8859-1' }``` and add ```'\x1B' + '\x74' + '\x39'``` in data array, but nothing changed...

**Comment by tresf** [comment] 2019-09-05 21:30
You're sending one large string, I'm sending an array of strings.  You'd have to refactor a bit to use the helper that I wrote.

```js
function initPrinter() {
    return '\x1B' + '\x40';
}

function toHex(number) {
    var hex = (Math.abs(number)).toString(16);
    while (hex.length < 2) {
        hex = "0" + hex;
    }
    return "x" + hex.substring(0, 2).toUpperCase();
}

function qrCodeGenerator(qrSource) {
    const dots = '\x07';
    const qrLen = qrSource.length + 3;
    return [
         '\x1D' + '\x28' + '\x6B' + '\x04' + '\x00' + '\x31' + '\x41' + '\x32' + '\x00' +
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x43' + dots +
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x45' + '\x49',
        // '\x1D' + '\x28' + '\x6B' + toHex(qrLen % 256) + toHex(Math.floor(qrLen / 256)) + '\x31' + '\x50' + '\x30' +
        { type: 'raw', format: 'hex', data: 'x1Dx28x6B' + toHex(qrLen % 256) + toHex(Math.floor(qrLen / 256)) + 'x31x50x30' },
        qr,
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x51' + '\x30' +
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x52' + '\x30'
      ];
}

function dataToPrint() {
    const qrSource = 'http://hnfce.fazenda.mg.gov.br/portalnfce/nfce/qrcode?p=31190810958795000107650010000000251217012903|2|2|1|85205AA554B70B9B17FAA9067BFB7F03599A79FD';

    var data = qrCodeGenerator(qrSource);
    data.unshift(intPrinter());
    return [
        {
            type: 'raw',
            format: 'hex',
            data: [
                data
            ]
        }
    ];
}

**Comment by tresf** [comment] 2019-09-05 21:34
>  I found this ESC/POS function that allows you to select character code table. Is this related to encoding?

That's only intended to prepare the printer for a different encoding.  The issue is being created by a silent UTF-8 encoding from browser to Java, before it even hits the printer.  The above technique should work as it delays the byte parsing until it prints.

**Comment by pedrollmatias** [comment] 2019-09-06 15:32
> You're sending one large string, I'm sending an array of strings. You'd have to refactor a bit to use the helper that I wrote.

I'm getting the same error even after refactoring...

Also tried to change
``` javascript
return "x" + hex.substring(0, 2).toUpperCase();
```
to
``` javascript
return "\\x" + hex.substring(0, 2).toUpperCase();
```

**Comment by pedrollmatias** [comment] 2019-09-06 17:46
> You're sending one large string, I'm sending an array of strings. You'd have to refactor a bit to use the helper that I wrote.

Got it! Finally, I could make both things work. Here is my code if someone has the same problem:
```javascript
function initPrinter() {
    return '\x1B' + '\x40';
}

function breakline() {
    return '\x0A';
}

function specialCharactersGenerator() {
    return 'çãÃéèúÚõ';
}

function toHex(number) {
    var hex = (Math.abs(number)).toString(16);
    while (hex.length < 2) {
        hex = "0" + hex;
    }
    return "x" + hex.substring(0, 2).toUpperCase();
}

function qrCodeGenerator(qrSource) {
    const dots = '\x07';
    const qrLen = qrSource.length + 3;
    const size1 = this.toHex(qrLen % 256);
    const size0 = this.toHex(Math.floor(qrLen / 256));
    return [
        '\x1D' + '\x28' + '\x6B' + '\x04' + '\x00' + '\x31' + '\x41' + '\x32' + '\x00',
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x43' + dots,
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x45' + '\x49',
        { type: 'raw', format: 'hex', data: 'x1Dx28x6B' + size1 + size0 + 'x31x50x30' },
        qrSource,
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x51' + '\x30',
        '\x1D' + '\x28' + '\x6B' + '\x03' + '\x00' + '\x31' + '\x52' + '\x30',
    ];
}

function dataToPrint() {
    const largeQrsource = 'http://hnfce.fazenda.mg.gov.br/portalnfce/nfce/qrcode?p=31190810958795000107650010000000251217012903|2|2|1|85205AA554B70B9B17FAA9067BFB7F03599A79FD';
    const data = [];
    data.push(initPrinter());
    data.push(specialCharactersGenerator());
    data.push(breakline());
    qrCodeGenerator(largeQrsource).map((element) => {
        data.push(element);
    });
    return data;
}
```
and here I send data to print:
```javascript
const config = qz.configs.create(printerName, { encoding: 'CP850', altPrinting: true });
const printContent = dataToPrint();
qz.print(config, printContent);
```
@tresf Thank you very much for your help.

**Comment by tresf** [comment] 2019-09-06 17:48
@pedrollmatias thanks kindly for sharing your code.
