### ISSUE TITLE
Label orientation issue after upgrade to 2.0.11

### ISSUE THREAD

**Issue by chriswheeler** [qzind/tray#500] opened 2019-10-10 14:35 UTC
Hello,

I recently upgraded from 2.0.4 to 2.0.11, and I'm now finding it impossible to get labels to print correctly from my Dymo LabelWriter 450 onto a Large Address Label (88.90mm x 35.56mm)

Sample PDF File:

[Address_Labels_190202-1.pdf](https://github.com/qzind/tray/files/3713059/Address_Labels_190202-1.pdf)

With 2.04 the following options produced the correct result:

	options = {
		size: { 
			width: 35.56, 
			height: 88.90 
		}, 
		units: 'mm', 
		colorType: 'grayscale',
		orientation: 'landscape',
		interpolation: "nearest-neighbor" 
	}

After upgrading, the label was printed very small at the top right:

![image](https://user-images.githubusercontent.com/2039180/66578427-fcb48980-eb72-11e9-8d1d-020cbb047b01.png)

if I add:

	scaleContent: "false"

I get the correct size label, but in the wrong position:

![image](https://user-images.githubusercontent.com/2039180/66578593-4bfaba00-eb73-11e9-9c8c-8cc36a094723.png)

I have tried setting a negative left margin to move it over, but that does not have any effect (and feels like a hack).

I have tried various combinations of orientation settings, and switching the width/height values.

It feels like QZ is auto-scaling (based incorrectly on width), then positioning the label, and then rescaling back to the original size, but with a mis-calculated positioning.

I'm using the following code to call qz.print:

	var config = qz.configs.create(printer, options); 
	var data = [ { type: 'pdf', data: url } ];
	return qz.print(config, data);

`url` is the web address to a PHP script which outputs a PDF file with one of more labels.

**Comment by tresf** [comment] 2019-10-10 16:12
Dymo's can be picky about layout and some OSs are better about matching sizes than others.

The code suggests the label dimensions are 1.4" in x 3.5" correct?  Inspecting the PDF shows the same dimensions.  I only ask because usually we commonly see  sizes like 1 1/8.  Dymo installs a variety of "form" sizes and it's up to the print spooler to make sure there's a matching form available.

* On 2.0.5 we made many improvements to orientation including the default option to autorotate when the orientation of the PDF was incorrect for the given paper.  https://github.com/qzind/tray/commit/e602da65590051d8833340c6c92bdd4e3a4ec163
* On 2.0.10, we fixed a bug where rotation was occuring incorrectly. https://github.com/qzind/tray/commit/3e2e8370c41bddb14cde7793f99a4ce3ecc9336e

Since your PDF appears to be landscape already, it appears something's gone wrong with the resizing.

If you remove `{ orientation: 'landscape' }` completely, does it do the same thing?

We have hardware we can test the code out on but to reproduce:
* What OS
* What version of Java
* Can you please provide the logs

**Comment by chriswheeler** [comment] 2019-10-10 16:40
These are the labels - https://www.amazon.co.uk/Dymo-LabelWriter-Address-Labels-Self-Adhesive/dp/B00028XNN6

They are described as 36mm x 89mm and I'm not sure where I originally got the 35.56 / 88.90 values from to be honest. I can certainly try setting the PDF and QZ configuration to be 36 x 89.

Worth mention that the PDF I provided prints correctly on the Dymo if printed directly from Adobe Acrobat or from Chrome's PDF viewer.

I did try removing the `orientation: landscape` and, if i remember correctly, it resulted in the same output as my first image with the label very small, but rotated 90 degrees. I can try that again to confirm later on.

OS is Windows 10

Java Version is latest (I actually upgraded QZ from 2.0.4 to 2.0.11 after a recent Java Update, which made QZ complain about a null value when trying to print. I will confirm exact version later.

I also use QZ for printing A4 documents to a Brother laser printer and that still works fine with 2.0.11

Where do I get the logs from?

**Comment by tresf** [comment] 2019-10-10 16:41
Where do I get the logs from?

Windows: `%APPDATA%\qz`
Mac: `~/Library/Application Support/qz`
Linux: `~/.qz`

**Comment by tresf** [comment] 2019-10-10 16:50
`36mm x 89mm` is the `30321 / Large Address Label` which should come default with the Dymo driver installation.

Windows is pretty good about rounding up/down.

> I'm not sure where I originally got the 35.56 / 88.90 values

It's `1.4 x 3.5 in` directly converted to `mm`.  Interestingly enough, the box has both units of measure.  In that case, you should be fine with providing either although as a sanity check a good idea to double-check the OS forms to see how Dymo defines it.  You can define a windows form in metric or imperial. 

![image](https://user-images.githubusercontent.com/6345473/66589346-5493c600-eb5c-11e9-947f-9f8097a67c40.png)

**Comment by chriswheeler** [comment] 2019-10-10 19:40
Logs (with orientation)

```
2019-10-10 09:20:52,989 [INFO] Connection opened from /0:0:0:0:0:0:0:1:53057 on socket port 8181
2019-10-10 09:20:53,102 [DEBUG] Message: {"certificate":"-----BEGIN CERTIFICATE-----iZrkZ4g==\n-----END CERTIFICATE-----\n","promise":{},"timestamp":1570695653099,"uid":"vl5u3n","position":{"x":683,"y":364}}
2019-10-10 09:20:53,105 [DEBUG] Received new certificate from connection through 53057
2019-10-10 09:20:53,160 [DEBUG] Message: {"call":"print","promise":{},"params":{"printer":{"name":"Dymo"},"options":{"colorType":"grayscale","copies":1,"density":0,"duplex":false,"fallbackDensity":null,"interpolation":"nearest-neighbor","jobName":null,"legacy":false,"margins":0,"orientation":"landscape","paperThickness":null,"printerTray":null,"rasterize":true,"rotation":0,"scaleContent":"false","size":{"height":35.56,"width":88.9},"units":"mm","altPrinting":false,"encoding":null,"endOfDoc":null,"perSpool":1},"data":[{"type":"pdf","data":"https://x.com/addresslabel.php?method=batch&batchid=123"}]},"signature":"5rx0g==","timestamp":1570695653112,"uid":"47vk6o","position":{"x":683,"y":364}}
2019-10-10 09:20:53,167 [DEBUG] Using qz.printer.action.PrintPDF to print
2019-10-10 09:20:53,167 [DEBUG] Searching for PrintService matching Dymo
2019-10-10 09:20:53,168 [DEBUG] Found 9 printers
2019-10-10 09:20:53,168 [DEBUG] Found match: DYMO LabelWriter 450
2019-10-10 09:20:53,168 [DEBUG] Found Resolution: 30000x30000 dphi
2019-10-10 09:20:53,372 [DEBUG] Parsed 1 files for printing
2019-10-10 09:20:53,412 [INFO] Starting printing (1 copies)
2019-10-10 09:20:53,485 [DEBUG] Paper area: -151,0:251,100
2019-10-10 09:20:53,612 [DEBUG] Paper area: -151,0:251,100
2019-10-10 09:20:53,626 [DEBUG] Paper area: -151,0:251,100
2019-10-10 09:20:53,655 [INFO] Printing complete
2019-10-10 09:27:48,998 [INFO] Connection closed: 1001 - null
2019-10-10 09:27:48,999 [INFO] Closing all communication channels for x.com

**Comment by chriswheeler** [comment] 2019-10-10 19:47
OK, so I removed `orientation: landscape` and now it works perfectly!

Thanks for the help, if there is anything else I can do to help you work out why there is an issue when the orientation is specified please let me know. 

For reference I kept the units in mm at 35.56 / 88.90. 

Java Version 8 update 221.

Perhaps it was something as stupid as needing a reboot after updating Java...

**Comment by tresf** [comment] 2019-11-11 19:51
I'm marking this as duplicate of #501 as they read nearly identical.  @klabarge if you disagree when testing #501 feel free to reopen.

**Closed by tresf** 2019-11-11 19:51 UTC
