### ISSUE TITLE
Java environment missing error is not shown

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#222] opened 2017-08-15 12:45 UTC
> Quoting @ArunEdathadan :

> When I tried to run old version, during it's initialization , displays error regarding the missing of java. but for new version , the error is missing.

Can you provide your environment details (OS, etc.) and steps to reproduce?

I tried installing QZ Tray 2.0.4 on Windows 7 Professional 64-bit and I get the "Java is required" message.

![image](https://user-images.githubusercontent.com/12505463/29316325-955298de-8195-11e7-8088-57b1e22da16f.png)

**Comment by tresf** [comment] 2017-08-15 12:53
@ArunEdathadan are you on macOS?

Is this related to https://github.com/qzind/qz-print/issues/37?  If so, this was changed a few years ago.  Can you explain exactly how to reproduce?

**Comment by ArunEdathadan** [comment] 2017-08-15 12:56
I am using windows10

**Comment by tresf** [comment] 2017-08-15 12:59
@ArunEdathadan can you reproduce on multiple workstations?  We'd be happy to patch this bug if we can reproduce.  Currently, we cannot.  We need exact steps.

**Comment by tresf** [comment] 2017-08-17 03:19
> then there was a java class missing error.

Another thing worth mentioning is that we do a Java version check (e.g. > 1.7) on install, so this problem sounds like an edge-case.

Regardless, we'll be happy to reproduce, just give us the exact Java version required to reproduce the problem (install succeeds, but launch fails).

If you can't provide this, we'll assume this is a corrupt Java installation or non-standard environment causing the problem and close out as invalid.

**Comment by tresf** [comment] 2017-09-19 04:05
> If you can't provide this, we'll assume this is a corrupt Java installation or non-standard environment causing the problem and close out as invalid.

Closing since the required information was not provided.  Please let us know if you have an environment to recreate and we'll reopen.

**Closed by tresf** 2017-09-19 04:05 UTC
