### ISSUE TITLE
Html Print Not Working

### ISSUE THREAD

**Issue by shajunr88** [qzind/tray#389] opened 2018-11-30 06:46 UTC
I am using QZ tray version 2.0 along with java version 8 and windows 7.In the sample.html, when I click the raw printing it works perfectly and get printed out put .Upon clicking HTML print button,only a java popup comes and disappear.There is nothing get printed.I tried with Java version 7 also.But it throws some Java FX error.My printer in EPSON TM-T82 .

**Comment by lite1979** [comment] 2018-11-30 13:35
@shajunr88 

Are you sending the HTML content to a raw queue? HTML printing will not work if sent to a raw queue. We recommend Oracle Java 8 (update 191 is the latest as of this post) with JavaFX. HTML printing will not work without JavaFX.

**Comment by lorro** [comment] 2018-11-30 16:03
Have you installed the correct printer driver? I had the same problem a couple of days ago because I had installed it as Generic / Text Only. You should download & install the correct drivers for the printer. So it can print other things than only text.

**Comment by tresf** [comment] 2018-12-04 14:47
Closing because as a support request and not a bug, defect or enhancement with QZ Tray.  Feel free to continue discussion, but the status of this bug will remain closed.

**Closed** 2018-12-04 14:48 UTC
Labels: question
