### ISSUE TITLE
Printer driver filter

### ISSUE THREAD

**Issue by tresf** [qzind/tray#47] opened 2016-05-03 00:09 UTC
We need to provide the ability to filter listed printers available for listing and printing based on a driver-filter.

I think it's better to just allow the user to black-list a particular driver(s) rather than hard-coding a bunch of stuff that may change.
- [x] Windows
  - Possibly use JNA approach for win32: http://stackoverflow.com/questions/15476914/how-can-i-get-a-printers-make-and-model-in-java (decided out of scope)
  - Read registry, provide driver name back to JavaScript
    - `HKLM\SYSTEM\CurrentControlSet\Control\Print\Printers\`  for local printers
    - `HKCU\Printers\Connections\<servername>` for server printers
      - Note, points to:  `HKLM\Software\Microsoft\\Windows NT\CurrentVersion\Print\Providers\Client Side Rendering Print Provider\Servers\<servername>\Printers\<guid>`
- [x] CUPS
  - `lpstat -l -p PDFwriter` provide driver name back to JavaScript
    - `Interface: /private/etc/cups/ppd/PDFwriter.ppd` for Mac
    - `Interface: /etc/cups/ppd/PDF.ppd` for Linux
- [ ] Documentation
  - Wiki and/or `sample.html`

**Comment by bberenz** [comment] 2016-06-14 14:22
From an API perspective, how would this be implemented?
Javascript can be modified, so would we need an alternative method of restricting it, or is that not a worry for this level of implementation?

On that note, what's to prevent them from forcing multiple copies to a physical printer? Even the basic driver print dialog allows that on most printers.

**Comment by tresf** [comment] 2016-06-14 15:04
In this case, it would be assumed that the end user wouldn't have the ability (or expertise) to modify the JavaScript code.  I understand that assumption is quite.... well.... assuming... but it's the best we can do and the sponsor understands this.

> what's to prevent them from forcing multiple copies to a physical printer? Even the basic driver print dialog allows that on most printers

Since we don't show the printer dialog and the implementation will leverage something like base64 under the covers to obscure the data that will be the way to mask this from the end user.  Locking down the data as well as the browser would be the responsibility of the client.

**Comment by bberenz** [comment] 2016-06-14 15:10
Alight then, so where would this information be passed?
In the listing of the printers? In the config? In the print options? Elsewhere?

**Comment by tresf** [comment] 2016-06-14 15:13
> From an API perspective, how would this be implemented?

Perhaps something like `qz.printers.blackList({"FILE:", "PORTPROMPT:", "PrimoPort:"});` or whatever technique can be used to filter a particular port or driver (I would expect something more technical than a printer name, just don't have the info at this moment).

I would also say we should provide a checkbox on our `sample.html` "Prevent printing to virtual printers" which would have a laundry list of these which Kyle and I can provide once we figure out a reliable filtering mechanism.

**Comment by tresf** [comment] 2016-06-14 15:20
> where would this information be passed?

Configs seems like the best place however it's becoming quite inflated with so many items.  What are your thoughts?

**Comment by bberenz** [comment] 2016-07-07 15:38
So I've gone the route of adding a new api call (`qz.printers.details`) that will return details about each printer, including the driver name, 281ff50941c3bb6ef0aa50e7d19fc47d00ff34ac. This way, as each config needs a printer name set, the site can get full control of what printers they'd even want available for selection.

**Comment by tresf** [comment] 2016-07-08 15:36
@bberenz I think we have an issue when printers contain backslashes in their name.... 

The printer name is: `\\servername\Printer Name 4`.

The logs show this:

```
Executing: [reg, query, HKLM\SYSTEM\CurrentControlSet\Control\Print\Printers\,,servername,Printer Name 4, /v, Printer Driver]
```

```
[ERROR] 2016-07-08 11:34:55,438 @ qz.ws.PrintSocketClient:?
        Problem processing message
java.lang.StringIndexOutOfBoundsException: String index out of range: -5
        at java.lang.String.substring(Unknown Source)
        at qz.utils.PrintingUtilities.getDriver(Unknown Source)
        at qz.printer.PrintServiceMatcher.getPrintersJSON(Unknown Source)
        at qz.ws.PrintSocketClient.processMessage(Unknown Source)
        at qz.ws.PrintSocketClient.onMessage(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by bberenz** [comment] 2016-07-08 15:41
I can assure you that is not the cause of this issue (I have one named `\\diskstation\usbprinter`).

What output do you get from running `reg query HKLM\SYSTEM\CurrentControlSet\Control\Print\Printers\,,servername,Printer Name 4 /v Printer Driver` directly in your command line?
And is this a printer that is presently available, or just listed as installed?

**Comment by tresf** [comment] 2016-07-08 15:47
You're right, this is a different problem.  The registry key does not exist at all there, it's a HKCU key.  All domain-pushed printers don't show up in HKLM.

I see a mapping here: `HKCU\Printers\Connections\,,server,Printer Name 4` but it doesn't have the information we're looking for.

**Comment by tresf** [comment] 2016-07-08 15:58
Hmm... 

By looking it up in `HKCU\Printers\Connections\,,server,Printer Name 4`, you can get the GUID. 

e.g. `{FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF}`

Then, under the following location (note "servername" from `,,servername,`)

```reg
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Print\Providers\Client Side Rendering Print Provider\Servers\servername\{FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF}
```
..  you can see the printer driver name as "HP LaserJet FOO BAR" as well as `Action, Attributes, ChangeID, CreatorSid, Datatype,Description,Port, Print Processor`, etc.

**Comment by tresf** [comment] 2016-07-08 16:02
Upon investigation, these above key may be added by Remote Desktop services.   I've no idea where the pushed mappings go to.

**Comment by bberenz** [comment] 2016-07-08 16:05
Anything useful under `HKLM\SYSTEM\CurrentControlSet\Control\Print\Providers`?

**Comment by tresf** [comment] 2016-07-08 16:09
Unfortunately no.  These printers are mapped in user space at login time.  They're life-cycle and settings are most likely maintained in `HKCU`.

**Comment by tresf** [comment] 2016-07-08 16:14
So I'm fairly confident that the

`HKCU\Printers\Connections\,,server,Printer Name 4\Guid` is required to fetch it per e.g. `{FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF}`.

Although `Client Side Rendering Print Provider` does contain the RDP mapped printers, it doesn't seem to be exclusive.

I'll export the keys and email you.

**Comment by bberenz** [comment] 2016-07-11 13:36
Should be fixed with 79a2e225e2425c1b78b93b5777ffc9caf48ab1dd, but as I don't have a network printer configured like this, you'll need to verify it works.

**Comment by tresf** [comment] 2016-07-20 04:04
Tested and patched via 163a6fd.

Issues:
 * Network printers aren't listing the printer trays.

Cosmetic issues:
 * Due to the amount of information available on this screen, a static dialog would be preferred
 * I think we need to bullet out the features a bit better.  @klabarge can do this, but I think we can do something like:
  * Microsoft XPS Document Writer
    * **Driver:** Microsoft XPS Document Writer v4
    * **Trays:** 1: Letter, 2: Manual Feed, etc
    * **Density:** 600dpi

Testing on Windows is good so far though.  I'd like to see how this works on Linux and Mac.

**Comment by bberenz** [comment] 2016-07-20 14:22
> Network printers aren't listing the printer trays.

What output do you get from the following code for printer `<NAME>`?

```java
public static void main(String[] args) {
    PrintService ps = PrintServiceMatcher.matchService("<NAME>");
    for(Media m : (Media[])ps.getSupportedAttributeValues(Media.class, null, null)) {
        System.out.println(m.toString());
    }
}
```

**Comment by tresf** [comment] 2016-07-20 18:11
> What output do you get

Here's what I get:

```
na-letter
na-legal
executive
iso-a3
iso-a4
iso-a5
jis-b4
jis-b5
b
na-number-10-envelope
iso-designated-long
iso-c5
iso-b5
monarch-envelope
oufuko-postcard
16K
folio
B5 (ISO)
8K
B5 ISO 176x250mm
Double Japan Postcard Rotated
Executive (JIS)
 Printer Auto Select
 Manual Feed in Tray 1
 Tray 1
 Tray 2
 Tray 3
 Tray 4
Unspecified
Plain
Preprinted
Letterhead
Transparency
Prepunched
Labels
Bond
Recycled
Color
Light 60-75 g/m2
Heavy 106-163 g/m2
Cardstock >164 g/m2
Glossy 75-105 g/m2
Heavy glossy
Tough paper
Envelope
```

**Comment by bberenz** [comment] 2016-07-20 20:11
I'm going to assume you didn't alter the output, which means occasionally the Media class decides to add extra whitespace around it's names..

Now you've reopened #61 on this, and in your styling suggestion here you list the tray number and supported format, but as you can see in your own output, we don't get that level of detail. And currently we just return the highest number returned from the generic "Tray X" media as the number of trays for this field. 
Printers vary a bit on the extra tray media (eg the `Manual Feed in Tray 1` type trays). So how would you want the supported printer tray listing (and api selection) implemented? As right now listing returns a single number and selection only takes a number and appends `Tray ` on it to find the matching Media.

**Comment by tresf** [comment] 2016-07-20 20:25
> which means occasionally the Media class decides to add extra whitespace around it's names..

Correct, I didn't change formatting.  Curious... are you sure `toString()` is the best way to parse this object?

> Now you've reopened #61 on this, and in your styling suggestion here you list the tray number and supported format, but as you can see in your own output, we don't get that level of detail. And currently we just return the highest number returned from the generic "Tray X" media as the number of trays for this field. 

Then that will have to suffice for now. :+1: 

> Printers vary a bit on the extra tray media (eg the Manual Feed in Tray 1 type trays). So how would you want the supported printer tray listing (and api selection) implemented? As right now listing returns a single number and selection only takes a number and appends Tray on it to find the matching Media.

I think it depends on how detailed we can get the tray information.  I'm not sure what use a laundry list is in this case, so any insight is welcome.  For starters, if we can do something like `Tray 1 (Manual Feed in Tray 1)` that would be a nice start.

**Comment by tresf** [comment] 2016-07-20 20:42
In regards to driver filter on Mac:

Test results pass after applying 130cf5a. The patch was to sanitize the blank `ShellUtilities.execute(...)` return values, since there's conveniently a disabled printer on this VM. :+1: I took the liberty to apply the same logic to Windows.

 I'm operating under the assumption that the `-1` dpi is normal.

![image](https://cloud.githubusercontent.com/assets/6345473/17002221/55721d2e-4e98-11e6-84e2-c1b87162ddde.png)

**Comment by bberenz** [comment] 2016-07-20 20:45
> are you sure toString() is the best way to parse this object

..it's the only way actually.. The constructor takes a single int to follow `EnumSyntax` class, `getCategory` only returns `Media.class`, and `getName` returns the literal string "media" ..

In regards to the listing we can return an array of what's reported in media (ie `["Manual Feed in Tray 1", "Tray 1", "Tray 2", ...]` and then accept either that exact string or a number and default to "Tray X"?

> I'm operating under the assumption that the -1 dpi is normal.

Yes, it's returned if we cannot parse the default dpi. I get it on a few of mine that _are_ connected.

**Comment by tresf** [comment] 2016-07-20 21:12
@bberenz I've marked Windows and CUPS as completed.  Let's take this conversation over to #61, since the driver feature is almost completed.

**Comment by tresf** [comment] 2016-08-05 03:21
Here's the list so far.  This will eventually live over at `qzind/sift` once completed.

```javascript
var filePrinters = [

   /* Mac */
   "PDFwriter.ppd",
   "Print_to_VipRiser.ppd",
   "Virtual_PDF_Printer.ppd",

   /* Linux*/
   "PDF.ppd", 

   /* Windows*/
   "Microsoft XPS Document Writer",
   "Microsoft Print To PDF",
   "Send to Microsoft OneNote",
   "PDFCreator",
   "PrimoPDF",
   "CutePDFWriter",
   "Bullzip PDF",
   "Adobe PDF",
   "doPDF",
   "novaPDF",
   "OPTIsend", //Print&Share, Brother
   "pdf995",
   "docPrint PDF", // VeryPDF
   "EmfPrinter",
   "ColorPlus",  // BlackIce
];
```

**Closed** 2020-01-10 16:27 UTC
Labels: enhancement
