### ISSUE TITLE
The current connection attempt has not returned yet

### ISSUE THREAD

**Issue by jkatsiotis** [qzind/tray#746] opened 2021-01-21 11:14 UTC
On Qz Tray (v 2.1.2) I keep getting this error appearing on browser's console: **The current connection attempt has not returned yet.** 

And sometimes this: **Connection closed before response received**

Any ideas?

**Comment by tresf** [comment] 2021-01-21 17:04
We seem to be getting this more and more with the 2.1 version, but we lack steps to reproduce.  One cause can be something like a form post, tab or popup window that's closed before a call (such as `qz.print(...)`) has completed and preferably `qz.websocket.disconnect()` has occurred.

We have reports that multiple tabs open at once may be causing this, but we lack steps to reproduce.  If you can provide these, we're very interested in looking into it.

**Comment by jkatsiotis** [comment] 2021-01-22 08:54
I'm afraid I can't reproduce as it appears on client machines and I'm notified via an log mechanism.

Does this log below helps?
![image](https://user-images.githubusercontent.com/751955/105468909-31811d00-5ca0-11eb-9a17-de1b4d16758a.png)

**Comment by tresf** [comment] 2021-01-22 14:27
@jkatsiotis thanks for the additional information.  Unfortunately, this is not helpful for tracking this particular issue down.  To identify a defect in the code requires specific steps, usually involving the developer that integrated QZ Tray to offer steps with our API to reproduce.

On occasion we're able to reproduce issues using our sample or demo page: https://demo.qz.io, but this particular bug I believe is hard to reproduce using that page due to a very specific timing of events.

**Comment by tresf** [comment] 2021-05-04 20:40
@jkatsiotis I'm going to close this until we have enough information to open it back up.

**Closed by tresf** 2021-05-04 20:40 UTC

**Comment by tleish** [comment] 2023-03-17 20:15
We are in the same boat.  We have customers experiencing this multiple times a day.  We've had conference calls with the customers asking them to reproduce it, but they are unable to on demand.  But "Connection closed before response received " shows up shows up in our logging daily.
