### ISSUE TITLE
Printing landscape PDFs in Mac OS result in content being cropped

### ISSUE THREAD

**Issue by mattchad** [qzind/tray#521] opened 2019-11-21 21:01 UTC
Attempting to print a landscape PDF to a landscape label but on printing the content is cropped at each side. See original (label.pdf) and the result from PDFWriter (job_1579 QZ Tray PDF Print.pdf)

Options..

`{
            size: {
                width: 6, 
                height: 4
            }, 
            units: 'in', 
            rasterize: false,
            orientation: 'landscape',
            scaleContent: false,
        }`

**Environment:**

QZ Tray: 2.0.11-1
Mac OS: 10.14.6 
Label Printer: TSC DA210 / PDFWriter
Label size: 150 x 100mm (6x4inch)

[label.pdf](https://github.com/qzind/tray/files/3876735/label.pdf)

[job_1579 QZ Tray PDF Print.pdf](https://github.com/qzind/tray/files/3876736/job_1579.QZ.Tray.PDF.Print.pdf)

**Comment by tresf** [comment] 2019-11-21 21:06
> `{ size: { width: 6, height: 4 } }`

Can you try reversing these?  Also, you should not need to provide "landscape" as we will fix origination automatically.

**Comment by mattchad** [comment] 2019-11-21 21:11
Thank you for the Swift response - much appreciated!

The resulting PDF is much closer. However, it is now printed portrait rather than landscape in PDFwriter (See attached)  and printed across multiple labels when printed using a physical printer.

[job_1585 QZ Tray PDF Print.pdf](https://github.com/qzind/tray/files/3876768/job_1585.QZ.Tray.PDF.Print.pdf)

**Comment by lite1979** [comment] 2019-11-21 22:25
Is the physical printer also connected to a MacOS machine? CUPS will frequently have 5x4 inches as the default page size for Zebra printers. It's worth checking the settings in localhost:631 for this.

**Comment by tresf** [comment] 2019-11-22 05:38
> it is now printed portrait rather than landscape in PDFwriter

Technically, all print jobs are portrait according to the print spooler.  I'm not sure why it's not smart enough to open as landscape, but it shouldn't affect the printing.  For example, if you print this same PDF using Preview to a user-defined page size of 4x6, it does the same thing (prints a portrait document).

> printed across multiple labels when printed using a physical printer.

Hmm... can you try setting `{ scaleContent: true}` and/or `{margins: 0}`.

**Comment by mattchad** [comment] 2019-11-25 10:43
> Is the physical printer also connected to a MacOS machine? CUPS will frequently have 5x4 inches as the default page size for Zebra printers. It's worth checking the settings in localhost:631 for this.
> 
> Edit: I see that you're using a TSC printer, but the default page size can still cause problems.

Changing the printer's default page size fixed my issue on Mac OS. Thank you!

However, i need to reverse width / height under Windows to get it to work correctly. The options look like this now for Mac OS..

`{
            size: {
                width: 38, 
                height: 102
            }, 
            units: 'mm', 
            rasterize: false,
            scaleContent: true,
            margins: 0,
        }`

And under Windows..

`{
            size: {
                width: 102, 
                height: 38
            }, 
            units: 'mm', 
            rasterize: false,
            scaleContent: true,
            margins: 0,
        }`

**Comment by klabarge** [comment] 2019-11-26 02:10
> However, i need to reverse width / height under Windows to get it to work correctly. The options look like this now for Mac OS..

Okay, thanks for that information. We want the same behavior for all OS's. I'll attempt to reproduce and escalate as needed.

@mattchad Does Windows behave properly if you set `orientation: 'landscape'`?

**Comment by klabarge** [comment] 2019-11-27 01:43
> width: 38, height: 102

Is this a typo? `38 mm` is `1.49 in`. You originally were using a `4x6in` label.

Regardless, I am unable to reproduce this symptom on Windows. Using `{ size: { width: 4, height: 6 }, rasterize: false}` I get identical landscape printouts using your label,

Can you please provide us the [stack trace](https://qz.io/wiki/faq#logs) for this behavior on Windows?

**Comment by tresf** [comment] 2019-11-27 16:03
>  I am unable to reproduce this symptom on Windows. Using `{ size: { width: 4, height: 6 }`, rasterize: false} I get identical landscape printouts using your label,

I wonder if the TSC doesn't define the paper sizes the same as the Zeba ZDesigner driver?

**Comment by mattchad** [comment] 2019-11-28 16:09
Thanks for the response. We were originally using larger labels but are now using 100mm x 38mm with the same result.

Logs for Mac...

> [DEBUG] 2019-11-28 15:57:21,289 @ qz.ws.PrintSocketClient:?
> 	Message: {"call":"printers.find","promise":{},"params":{},"signature":"Wq9RVUa4HL/5HnSJUhDsTS3Ol0ou8NbbfoILv0umyDqsGkwr9MU3dD9wyw73C0yRpW74RyA9/RObKyLPEPKEJoYkI/M/MHtfOEWcdvp1qm76e5kHQFzGsQqDSE+4Zq/5KI4SXWVO8nsInAHx3vBpSKxGaoUQCUHSkzgEH56zXYmWNSBy7j0PXnuElq2hGvRD/V3yo8+jmzTZnEE7j5bX4nFLK9O3ac43UDBkrGetRQ8eBE3F9WpUcvnY+oq6iSlL/dLuUfnOvj0xiM8GUN8CCwOquBnQN5Gfd7B1HqPyV7vPPre33MtGG4o8d080rxigbBHxwqoX0ysjcJCk3ZroGA==","timestamp":1574956641274,"uid":"db80gw","position":{"x":1280,"y":731.5}}
> [TRACE] 2019-11-28 15:57:21,293 @ qz.ws.PrintSocketClient:?
> 	Valid signature from Company Name
> [DEBUG] 2019-11-28 15:57:21,302 @ qz.printer.PrintServiceMatcher:?
> 	Found 5 printers
> [DEBUG] 2019-11-28 15:57:21,331 @ qz.ws.PrintSocketClient:?
> 	Message: {"call":"printers.find","promise":{},"params":{"query":"CITIZEN CL-S521"},"signature":"UBlr97kgc9NBSteCE30+F5LH6ZdG6sL4LL8HBAq8dLRv6eOeTNnhywngY7pT4fo3GGl8Q3rMPWvNl/w4PtZmTbpf8sJs7kcMCwKF9xnraW0Sf0UXe5Stmsn+aQAq18nj3EBPsukNioO6M5Am8TEMS925gtTebdpW9HenlP4AqVLdlH7SSPO5nqzDY73PcLATf2sgq43MWjMY3xyZg2BW5BdUFLR8nKYiGgPg3iHMEDq/DlW4AKQXmdUEZzzWmZZ7jB2OR4KNFMOd0h2XlgEdiAhNyccjZ/nLzvoV/cLa7QU7Zt6bK+UKK8bhehAZmNkdcXyDO+l1i4fBDCpuuLoHOg==","timestamp":1574956641321,"uid":"mr07re","position":{"x":1280,"y":731.5}}
> [TRACE] 2019-11-28 15:57:21,334 @ qz.ws.PrintSocketClient:?
> 	Valid signature from Company Name
> [DEBUG] 2019-11-28 15:57:21,335 @ qz.printer.PrintServiceMatcher:?
> 	Searching for PrintService matching CITIZEN CL-S521
> [DEBUG] 2019-11-28 15:57:21,342 @ qz.printer.PrintServiceMatcher:?
> 	Found 5 printers
> [DEBUG] 2019-11-28 15:57:21,348 @ qz.printer.PrintServiceMatcher:?
> 	Found match: CITIZEN CL-S521
> [DEBUG] 2019-11-28 15:57:21,363 @ qz.ws.PrintSocketClient:?
> 	Message: {"call":"print","promise":{},"params":{"printer":{"name":"CITIZEN CL-S521"},"options":{"colorType":"color","copies":1,"density":0,"duplex":false,"fallbackDensity":null,"interpolation":"bicubic","jobName":null,"legacy":false,"margins":0,"orientation":null,"paperThickness":null,"printerTray":null,"rasterize":false,"rotation":0,"scaleContent":true,"size":{"width":38,"height":102},"units":"mm","altPrinting":false,"encoding":null,"endOfDoc":null,"perSpool":1},"data":[{"type":"pdf","format":"file","data":"URL"}]},"signature":"Rh+HWpncx/yrrheaD5zmoAMkbkNJIdRGVpSJ+ZPQcVgEHvrbALtpqScmtrqY5K+uUH4E2F8aMkzErJu5upye8StIbT2OL2PgzLtLolgFL7gGxCViX9VHA0uSccCk4tRf9VYa08pdqNEcDWc09lXCs0mAWYNhJXOu0hZ8owmyi8H2K3Y2+mKvU49D3G1I9QiqdY/hZChbMljBTTj8VQiCZXk5G/bxujd3Ou1r53Gd7n3cJFXEfDdBL4PCFwaqSmo9dmKLaKsstONsQIijidKc8HcZ03IThZ1wtfCmvJcXX4Mkyl3S95Hp5+VKzV98rS33aEocNsEBGxkufzjfnbcZrQ==","timestamp":1574956641353,"uid":"lfq8fl","position":{"x":1280,"y":731.5}}
> [TRACE] 2019-11-28 15:57:21,367 @ qz.ws.PrintSocketClient:?
> 	Valid signature from Company Name
> [TRACE] 2019-11-28 15:57:21,368 @ qz.utils.PrintingUtilities:?
> 	Waiting for processor, 0/8 already in use
> [DEBUG] 2019-11-28 15:57:21,368 @ qz.utils.PrintingUtilities:?
> 	Using qz.printer.action.PrintPDF to print
> [DEBUG] 2019-11-28 15:57:21,369 @ qz.printer.PrintServiceMatcher:?
> 	Searching for PrintService matching CITIZEN CL-S521
> [DEBUG] 2019-11-28 15:57:21,376 @ qz.printer.PrintServiceMatcher:?
> 	Found 5 printers
> [DEBUG] 2019-11-28 15:57:21,382 @ qz.printer.PrintServiceMatcher:?
> 	Found match: CITIZEN CL-S521
> [DEBUG] 2019-11-28 15:57:21,382 @ qz.utils.PrintingUtilities:?
> 	Found Resolution: 20300x20300 dphi
> [DEBUG] 2019-11-28 15:57:21,406 @ qz.printer.action.PrintPDF:?
> 	Parsed 1 files for printing
> [TRACE] 2019-11-28 15:57:21,411 @ qz.printer.action.PrintPixel:?
> 	DPI: 0.0	CNV: 2.83464
> [TRACE] 2019-11-28 15:57:21,412 @ qz.printer.action.PrintPixel:?
> 	Drawable area: 0.0,0.0:38.0,102.0
> [TRACE] 2019-11-28 15:57:21,412 @ qz.printer.action.PrintPixel:?
> 	[(0.0,0.0)->(38.0,102.0)mm, color]
> [TRACE] 2019-11-28 15:57:21,414 @ qz.printer.action.PrintPixel:?
> 	DPI: 0.0	CNV: 2.83464
> [TRACE] 2019-11-28 15:57:21,415 @ qz.printer.action.PrintPixel:?
> 	Drawable area: 0.0,0.0:38.0,102.0
> [TRACE] 2019-11-28 15:57:21,415 @ qz.printer.action.PrintPixel:?
> 	[(0.0,0.0)->(38.0,102.0)mm, color]
> [INFO] 2019-11-28 15:57:21,416 @ qz.printer.action.PrintPixel:?
> 	Starting printing (1 copies)
> [TRACE] 2019-11-28 15:57:21,434 @ qz.printer.BookBundle:?
> 	Requested page 0 for printing
> [DEBUG] 2019-11-28 15:57:21,435 @ qz.printer.PDFWrapper:?
> 	Paper area: 0,0:289,107
> [TRACE] 2019-11-28 15:57:21,447 @ qz.printer.BookBundle:?
> 	Requested page 0 for printing
> [DEBUG] 2019-11-28 15:57:21,447 @ qz.printer.PDFWrapper:?
> 	Paper area: 0,0:289,107
> [INFO] 2019-11-28 15:57:21,465 @ qz.utils.PrintingUtilities:?
> 	Printing complete
> [TRACE] 2019-11-28 15:57:21,466 @ qz.utils.PrintingUtilities:?
> 	Returning processor back to pool


Logs for Windows....

> [DEBUG] 2019-11-28 16:03:46,630 @ qz.ws.PrintSocketClient:?
>                 Message: {"call":"printers.find","promise":{},"params":{},"signature":"CG8C1l89TY+GPUr98Tlb5ZSAPXaWAGKYIoYcRw1pyTyOXLEvH/rq4/K7N/ix3F54bDastynK7IKH4/sej+bqS+zb8AGhL5qxBtx20DCMkNcpBmXAcDJA6upZzwLguIt1P8EqVI5OVY9gxf0GMT/Gw8ZIL2thCLxTgdpFTFuTFmEZQWJpwnoiDEL8sApjxK8jeWZ/Okq3fNwhLRERW/0t3wpDnCWCKid9AJBgrUMfEwgAgLMLkBddneaOfBozfjnCnaYCEOjpfAxmAmlrUTj9yZouRjx8D6QgzB15ms7nkp17mIrVTBboFiXPXTEQSkJAtz4Wln+krHZ51Lt27wjp4A==","timestamp":1574957026584,"uid":"g1pjwu","position":{"x":960,"y":520}}
> [TRACE] 2019-11-28 16:03:46,632 @ qz.ws.PrintSocketClient:?
>                 Valid signature from Company Name
> [DEBUG] 2019-11-28 16:03:46,633 @ qz.printer.PrintServiceMatcher:?
>                 Found 7 printers
> [DEBUG] 2019-11-28 16:03:46,665 @ qz.ws.PrintSocketClient:?
>                 Message: {"call":"printers.find","promise":{},"params":{"query":"TSC DA210"},"signature":"k4NTuIcT0XTH6hPKTCxpCcl2Ic/hvUJVR7QNiz7psyqEJtGcjqwLO5QWSDvERPsZKSEGMxXviPAKKGwBwpZN+U+TG3HLGAV7GRQf5NrgewD/iqSdQ4r2wdfHYlsLn205nw530g0mFsTqvRhgNaIAk0YX9Wbo+4+9Iv4rx7s8+FAhwEg1gHrX6Fv/tECg0r160P+nUTRWVO6oCCxaklbM9VPvFInU1BJyzBW87+uhmaJ6X+Z5dtc83Nt7aPRI9Ei1Gj3pqhlFpFYyoQK4Jb04/dw1buHdNSEsvCzvJ2/x2ImZ9qCmrFbLHQ1WQEtjK8AVQ6UQmISbBKuPvuPxacqEKQ==","timestamp":1574957026635,"uid":"af5sh4","position":{"x":960,"y":520}}
> [TRACE] 2019-11-28 16:03:46,680 @ qz.ws.PrintSocketClient:?
>                 Valid signature from Company Name
> [DEBUG] 2019-11-28 16:03:46,680 @ qz.printer.PrintServiceMatcher:?
>                 Searching for PrintService matching TSC DA210
> [DEBUG] 2019-11-28 16:03:46,680 @ qz.printer.PrintServiceMatcher:?
>                 Found 7 printers
> [DEBUG] 2019-11-28 16:03:46,680 @ qz.printer.PrintServiceMatcher:?
>                 Found match: TSC DA210
> [DEBUG] 2019-11-28 16:03:46,727 @ qz.ws.PrintSocketClient:?
>                 Message: {"call":"print","promise":{},"params":{"printer":{"name":"TSC DA210"},"options":{"colorType":"color","copies":1,"density":0,"duplex":false,"fallbackDensity":null,"interpolation":"bicubic","jobName":null,"legacy":false,"margins":0,"orientation":null,"paperThickness":null,"printerTray":null,"rasterize":false,"rotation":0,"scaleContent":true,"size":{"width":102,"height":38},"units":"mm","altPrinting":false,"encoding":null,"endOfDoc":null,"perSpool":1},"data":[{"type":"pdf","format":"file","data":"URL"}]},"signature":"fZY7zdOJX9CKNH1+sUw1q+CG9T3L/7/7R37a7JCny0VqQCNuVHK3OQeKNv4ewXQhOPZIviL7mZyWTchLGCjdS/BzL11ZKvXF03hvd35O3/3KA2Ta57tHy+6ZpHGjUdOiZuDARmhFWn0i9HMpLwsNIMEZ71JGmQ40hOV+HtfYKdfFbHZ7bqVS15yTHT6kY9ffNfx1ZyQMqCVy3FHxqpHIPSo2gwT1M40qMlZCAvGxDjkzY5lu9L+WSlV9vYYidbndo2L3IVjpE+I3nzrFMsjq9QyWOMRc5yISexbj0mjwa5KYg9ZLi/4kgQGE6fyil05Q1bM71tMP+IjNVRB4/R7UYw==","timestamp":1574957026688,"uid":"wvviv9","position":{"x":960,"y":520}}
> [TRACE] 2019-11-28 16:03:46,743 @ qz.ws.PrintSocketClient:?
>                 Valid signature from Company Name
> [TRACE] 2019-11-28 16:03:46,743 @ qz.utils.PrintingUtilities:?
>                 Waiting for processor, 0/4 already in use
> [DEBUG] 2019-11-28 16:03:46,743 @ qz.utils.PrintingUtilities:?
>                 Using qz.printer.action.PrintPDF to print
> [DEBUG] 2019-11-28 16:03:46,743 @ qz.printer.PrintServiceMatcher:?
>                 Searching for PrintService matching TSC DA210
> [DEBUG] 2019-11-28 16:03:46,743 @ qz.printer.PrintServiceMatcher:?
>                 Found 7 printers
> [DEBUG] 2019-11-28 16:03:46,743 @ qz.printer.PrintServiceMatcher:?
>                 Found match: TSC DA210
> [DEBUG] 2019-11-28 16:03:46,743 @ qz.utils.PrintingUtilities:?
>                 Found Resolution: 20300x20300 dphi
> [DEBUG] 2019-11-28 16:03:46,964 @ qz.printer.action.PrintPDF:?
>                 Parsed 1 files for printing
> [TRACE] 2019-11-28 16:03:47,046 @ qz.printer.action.PrintPixel:?
>                 DPI: 0.0 CNV: 2.83464
> [TRACE] 2019-11-28 16:03:47,051 @ qz.printer.action.PrintPixel:?
>                 Drawable area: 0.0,0.0:102.0,38.0
> [TRACE] 2019-11-28 16:03:47,052 @ qz.printer.action.PrintPixel:?
>                 [(0.0,0.0)->(102.0,38.0)mm, color]
> [TRACE] 2019-11-28 16:03:47,075 @ qz.printer.action.PrintPixel:?
>                 DPI: 0.0 CNV: 2.83464
> [TRACE] 2019-11-28 16:03:47,075 @ qz.printer.action.PrintPixel:?
>                 Drawable area: 0.0,0.0:102.0,38.0
> [TRACE] 2019-11-28 16:03:47,076 @ qz.printer.action.PrintPixel:?
>                 [(0.0,0.0)->(102.0,38.0)mm, color]
> [INFO] 2019-11-28 16:03:47,079 @ qz.printer.action.PrintPixel:?
>                 Starting printing (1 copies)
> [TRACE] 2019-11-28 16:03:47,176 @ qz.printer.BookBundle:?
>                 Requested page 0 for printing
> [DEBUG] 2019-11-28 16:03:47,177 @ qz.printer.PDFWrapper:?
>                 Paper area: 0,0:289,107
> [TRACE] 2019-11-28 16:03:47,228 @ qz.printer.BookBundle:?
>                 Requested page 0 for printing
> [DEBUG] 2019-11-28 16:03:47,229 @ qz.printer.PDFWrapper:?
>                 Paper area: 0,0:289,107
> [INFO] 2019-11-28 16:03:47,259 @ qz.utils.PrintingUtilities:?
>                 Printing complete
> [TRACE] 2019-11-28 16:03:47,260 @ qz.utils.PrintingUtilities:?
>                 Returning processor back to pool

**Comment by tresf** [comment] 2020-04-28 20:23
We recently patched the PDF rotation logic which may impact the status of this issue.  #617. The patch is only slated to land in 2.0, so I'll review and see if a backport to 2.0 is warranted.

**Comment by tresf** [comment] 2020-09-15 15:12
Closing.  Please request reopen if this issue still persists in newer versions.

**Closed by tresf** 2020-09-15 15:12 UTC
