### ISSUE TITLE
Support: Unable to compile client using Let's Encrypt certificate on MacOS

### ISSUE THREAD

**Issue by umutesen** [qzind/tray#474] opened 2019-07-28 14:04 UTC
I am trying to compile the client using a Let's Encrypt certificate, obtained from my hosting providers Plesk panel. 

I get the following warning in the console when compiling:

```
ant pkgbuild -Dauthcert.use=cert.pem

sign-jar-self:
     [echo] Self-signing Socket jar
  [signjar] Signing JAR: /Users/umut/Documents/Repos/tray/out/dist/qz-tray.jar to /Users/umut/Documents/Repos/tray/out/dist/qz-tray.jar as jzebra
  [signjar] jar signed.
  [signjar] 
  [signjar] Warning: 
  [signjar] The signer certificate has expired.
  [signjar] The signer's certificate is self-signed.
  [signjar] No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2016-05-31) or after any future revocation date.
```

I converted the .pem file to .crt using the following and used it to compile the client but I still get the same warning.
https://stackoverflow.com/questions/13732826/convert-pem-to-crt-and-key

The certificate I got from hosting provider is a PEM file with the following information:
```
-----BEGIN CERTIFICATE REQUEST-----
...
-----END CERTIFICATE REQUEST-----

-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----

-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

According to [this](https://github.com/qzind/tray/issues/73), PEM files are supported but I am not sure if I am missing anything.

**Comment by tresf** [comment] 2019-07-29 13:35
The message you've posted is fine.  The "timestamp" step is a Java signing feature that's not required by Java.  It's included for historical reasons.

Furthermore, there's no need to recompile our software because of an SSL certificate.  LetsEncrypt is a HTTPS certificate provider.  Shimming that certificate into the software requires the HTTPS keygen steps to be re-run on the print-server.

A quick Google search will show you how this is done: https://www.google.com/search?q=qz+tray+lets+encrypt&oq=qz+tray+lets+encrypt

If you're ALSO using LetsEncrypt for the licensing component, we do not assist with this, sorry.  It's very important to understand that SSL certificate and our licensing certificate are different.  Although some people choose to use them together, they're different and we strongly recommend that you do not combine the technologies.

If you are looking to use the community version of QZ Tray with LetsEncrypt certificates, you can use your own certificate and private key for licensing that never expires but we don't help with this.

The SSL stuff should be pretty self-explanatory.   Marking as duplicate of #73.

**Closed by tresf** 2019-07-29 13:35 UTC
