### ISSUE TITLE
RJ11 Cash drawer Support

### ISSUE THREAD

**Issue by haipt17** [qzind/tray#960] opened 2022-04-13 03:37 UTC
Hello,

I have 2 cash drawer devices.

1. Cash drawer A : connect to printer X , printer X connect to POS device.
Everything is good with qz

2. Cash drawer B connect to POS device via RJ11  ( example image )

My question is:

Does qz support the connection like (2) ?
If yes, how can I open (kick) cash drawer (2) that with qz?

Thank you for your attention and support.

![image](https://user-images.githubusercontent.com/22137804/163094650-44963047-0a06-4a03-820c-614fe455ffa4.png)

**Comment by tresf** [comment] 2022-04-13 04:10
Each drawer differs, but if you look at the bottom of this code snippet, the "print" command can take and send these "kick out" codes.

Some drawers are picky about pulse length as well, so I would recommend researching this ESC/POS command as well as what the drawer specification calla for.

Note: On Mac and Linux, config option`{ forceRaw: true }` may be needed to talk raw ESC/POS to the printer.

https://qz.io/wiki/raw#escpos

**Comment by tresf** [comment] 2022-04-13 04:18
Option 2: This is the first I've seen this particular setup.  Can you determine if it is available as a serial port on the PC? Does the manufacturer provide any documentation about the port?  Since it simply needs a pulse signal, we will need to know how to communicate with it.  A C#, VB, Fortran, C++ or BASIC example would probably give us enough information to start figuring it out.

**Comment by tresf** [comment] 2022-04-13 04:31
Option 2 (con't):

Initial research shows [the following](https://www.amazon.com/BT-100U-Drawer-Driver-Trigger-Interface/dp/B00OM9ML2K):

Something called a "cash drawer driver trigger" is available, which as linked is a USB pulse generator, but one which installs itself as a virtual COM port, quoting (Amazon):

> The [...] USB trigger module uses a virtual serial port driver, making it appear to software like a standard RS232 serial port. This way existing POS software can communicate with the USB cash drawer trigger as though connected to a serial port. A unique serial number is assigned to each USB trigger module and driver software will assign the next available serial port to each device it recognizes(multiple triggers can be used on one computer).
> 
> * Cash drawer can be directly connected to the computer [via USB]
> * Powered by USB bus, external power is not required
> * Allows for "Hot Plugging", plug and play connectivity
> * No need to set the COM property
> * Suitable to any cash drawer command.

I do not know which commands will be suitable for this device.  The above description suggests that the ESC/POS commands may work.

Note, the portion that states "No need to set the COM property" is misleading as virtual COM ports may be assigned any number, e.g. `COM5`.

QZ Tray does offer a serial API here: https://qz.io/wiki/serial.

Please share any other information you may find.

**Comment by tresf** [comment] 2022-04-13 04:37
Here's [a PCI version](https://www.newegg.com/sunix-model-cdk1037a-pci-to-serial-port-card/p/N82E16815114012) of a similar product (Newegg), quoting:

> #### [...] 2-port RS-232 & Cash Drawer interface Universal PCI Serial Board Model CDK1037A
> ...
> &nbsp; &nbsp; &nbsp; &nbsp; Expands two independent RS-232 serial ports with communication speeds up to 115.2Kbps.
> :arrow_right: &nbsp; **Expands single 6-pin RJ11/12 Type Cash Drawer interface to drive +12 / 24 VDC Cash Drawer.**
> ...
> 

<img src="https://user-images.githubusercontent.com/6345473/163100828-7dd57898-59ce-42a9-a98d-c1857a58f7ec.png" width="300px"/>

Since the rest of the specifications discuss serial, I assume it will also be a serial port communication.

**Comment by tresf** [comment] 2022-04-13 04:45
Option 2 (con't again again)

It appears Sunix also offers a multi-port PCI Express card with a similar usage:
https://www.sunix.com/en/product_detail.php?cid=1&kid=2&gid=10&pid=1687

Image (copyright Sunix):
<img src="https://user-images.githubusercontent.com/6345473/163101898-7d9c4557-cf40-46a1-a1bc-dd4bcb502a0d.png" width="500px"/>


Quoting:

> Expands single 6-pin RJ11/12 Type Cash Drawer interface to drive +12 / 24VDC Cash Drawer.

... however this requires a special pigtail adapter which splits the pins into several adapters, including RJ11/RJ12 type adapter for the cash drawer.

I would expect this card to add multiple serial ports (COM ports) to the computer when installed.

P.S. This card claims to have Linux and Windows support. 🐧

**Comment by haipt17** [comment] 2022-04-13 06:14
Hi @tresf ,

Actually with (2), printer not exists, just only cash drawer and POS device.

I am a software engineer, so basically I can't propose anything about third-device like converter or another cable ( financial issues )

POS  Device: [Ap-3615 ](https://www.manualslib.com/manual/911468/Firich-Enterprise-Aerpos-Ap-3615.html?page=20)
Cash Drawer: 12V-RJ11KA ( China factory )
Cable: RJ11

![image](https://user-images.githubusercontent.com/22137804/163111313-30c83c3a-464a-4269-a2bd-0b3dcb3af9ae.png)

**Comment by tresf** [comment] 2022-04-13 06:47
> I am a software engineer, so basically I can't propose anything about third-device like converter or another cable ( financial issues )

I would still expect this to use a standard communication, I'm just not sure how that's done.  The manual says the following:

> | I/O Port Connector | Type | Description |
> |--------------------|-------|------------|
> | Cash Drawer | RJ-11 | Connect to 12V Cash Drawer |

... which matches other cards linked, quoting "Expands single 6-pin RJ11/12 Type Cash Drawer interface to drive +12 / 24 VDC Cash Drawer." so I think it will be the same communication.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/6345473/163116562-80891573-ec2d-45d9-8d97-67d16941bdb0.png">


The communication is explained, but no code is provided.  Here's the communication chart:

> Up to two cash drawers may be driven from this port. Driving voltage of the solenoid is DC+12V. I/O port `284` is used for drawer operation. A test program is supplied, for Linux and Windows, source code of which is available on request by software developers. 
>
> | | Value | Description |
> |-|------|-------------|
> | Byte 1 (0xA0) | 0x00 | GPIO / 0x01 or DIO / 0x00. |
> | Byte 2-3 (0xA1 ~ 0xA2) | 0xA07 | Output address. |
> | Byte 4-5 (0xA3 ~ 0xA4) | 0xA07 | Input address. |
> | Byte 6 (0xA5) | 0xFD | Open cash drawer1 value. |
> | Byte 7 (0xA6) | 0xFB | Open cash drawer2 value. |
> | Byte 8 (0xA7) | 0xFF | Close cash drawer value. |
> | Byte 9 (0xA8) | 0x01 | Cash drawer status mask. |

... but I do not know what "IO port `284` means.  I have emailed FEC with request for source code. 🍻

**Comment by haipt17** [comment] 2022-04-13 06:53
Hi @tresf ,

Maybe it could help you ( and me )

[FEC Download Link](https://www.fecpos.com/download/download_modlist.html)

![image](https://user-images.githubusercontent.com/22137804/163117507-a86e9d6c-c01b-4b96-991f-091214298d60.png)

**Comment by tresf** [comment] 2022-04-13 07:00
I downloaded and extracted the > 1.7GB file but was unable to locate any documentation for this RJ11 port.  The manual suggests that it is an Intel product, but that does not make much sense, so I decided to look into Sunix instead.

Sunix does offer source code for their RJ11/RJ12 port.  It is bundled with the [driver for their PCI card](https://www.sunix.com/en/download.php?pid=1200&file=driver&file_link=download/driver/2022/20220325110358_HwManager.zip).  Unfortunately this source code uses precompiled library `.DLL`.  QZ Tray can talk to precompiled DLL files using custom code (JNA) but we generally do not use this technique for one-off hardware.

So I think we should wait for FEC to email back. 🤞

**Comment by tresf** [comment] 2022-04-13 07:11
Confirmed proprietary Sunix comms per: 
> "For the cash drawer interface, user can operate both +12 and +24 Voltage cash drawers by
implemented SUNIX Windows based API (Application Programming Interface)"

... taken from here: https://sunix.com/en/download.php?pid=1200&file=manual&file_link=download/manual/2012/771-CDK1037A0-001-2.pdf.

Hopefully FEC does not use a proprietary library. 🤷

**Comment by haipt17** [comment] 2022-04-13 07:12
Hi @tresf ,

I got a live demo from my colleague, POS System use .NET with dll libraries ( RJ11 connection )

Let me try to find cash drawer dll files then email to you. 

Would you mind sharing your email address with me?

**Comment by tresf** [comment] 2022-04-13 07:17
> Would you mind sharing your email address with me?

tres@qz.io :)

Note, if it has DLL files, that is proprietary and harder to integrate into QZ Tray.  We prefer hardware-agnostic solutions.

**Comment by tresf** [comment] 2022-04-13 07:48
> 
> This is weird because they said that Linux was supported. 😞
> 
> Hopefully FEC does not use a proprietary library. 🤷

FEC got back, they do not use a proprietary library on Linux.  Here is the sample code for Linux:

```ini
[H61]
GPIO=0
openaddr=a07
status=a07
sleep=200
open1=fd
open2=fb
close=ff
statusmask=01
```

```cpp
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include <unistd.h>
#include <sys/io.h>

int main()
{
	if (iopl(3) != 0) return -1;
	///////////////////// start open cash drawer /////////////////
	outb(0xfd,0xa07); // H61 Cash drawer out-1
    usleep(400000);
	outb(0xff,0xa07);
	
	
	outb(0xfb,0xa07); // H61 Cash drawer out-2
	
	usleep(400000);
	outb(0xff,0xa07);
	///////////////////// end open cash drawer ///////////////////
	///////////////////// start read cash drawer status //////////
  unsigned char b = inb(0xa07);
  if ((b&0x01)==0x01) printf("cash drawer opend\n");
  else printf("cash drawer closed\n");
	///////////////////// end read cash drawer status ////////////
	return 0;
}
```

Interestingly enough, Sunix offers the full source code for their Linux driver [here](https://www.sunix.com/en/download.php?pid=1200&file=driver&file_link=download/driver/2021/20211130103057_snx_V2.0.6.0.zip) but I am not familiar enough with C to understand how it works.

For FEC, here is an example of the Windows API.  We could call this in Java using JNA, but it would only work for this single hardware type.   If you're interested in attempting this, I would recommensettingng up a Java code editor with JNA  and installing the driver from FEC (I can send this to you via email).

```cpp
// FEC_CashDrawerTester.cpp : �w�q�D���x���ε{�����i�J�I�C
//

#include "stdafx.h"

#include <iostream>
#include <windows.h>

typedef int(*pfAddIntFunction)(int, int);
typedef DWORD(*pfGetCashDrawerStatusFunction)();
typedef DWORD(*pfSetCashDrawerOpenStatusValueFunction)(int);
typedef DWORD(*pfOpenCashDrawerFunction)();
typedef DWORD(*pfOpenCashDrawer1OnlyFunction)();
typedef DWORD(*pfOpenCashDrawer2OnlyFunction)();


int main()
{

#if 1

	pfAddIntFunction pfAddInt;
	pfGetCashDrawerStatusFunction pfGetCashDrawerStatus;
	pfSetCashDrawerOpenStatusValueFunction pfSetCashDrawerOpenStatusValue;
	pfOpenCashDrawerFunction pfOpenCashDrawer;
	pfOpenCashDrawer1OnlyFunction pfOpenCashDrawer1Only;
	pfOpenCashDrawer2OnlyFunction pfOpenCashDrawer2Only;


	HINSTANCE hLibrary = LoadLibrary(L"FEC_CashDrawerDLL.dll");

	if (hLibrary)
	{
		pfGetCashDrawerStatus = (pfGetCashDrawerStatusFunction)GetProcAddress(hLibrary, "GetCashDrawerStatus");;
		if (pfGetCashDrawerStatus)
		{
			std::cout << "CashDrawerStatus is " << pfGetCashDrawerStatus() << std::endl;
			//std::cout << pfGetCashDrawerStatus() << std::endl;
		}


		pfOpenCashDrawer = (pfOpenCashDrawerFunction)GetProcAddress(hLibrary, "OpenCashDrawer");;
		if (pfOpenCashDrawer)
		{
			pfOpenCashDrawer();
		}


#if 0
		pfSetCashDrawerOpenStatusValue = (pfSetCashDrawerOpenStatusValueFunction)GetProcAddress(hLibrary, "SetCashDrawerOpenStatusValue");;
		if (pfSetCashDrawerOpenStatusValue)
		{
			std::cout << pfSetCashDrawerOpenStatusValue(1) << std::endl;
		}
#endif


#if 0
		pfOpenCashDrawer1Only = (pfOpenCashDrawer1OnlyFunction)GetProcAddress(hLibrary, "OpenCashDrawer1Only");;
		if (pfOpenCashDrawer1Only)
		{
			pfOpenCashDrawer1Only();
		}
#endif

#if 0
		pfOpenCashDrawer2Only = (pfOpenCashDrawer2OnlyFunction)GetProcAddress(hLibrary, "OpenCashDrawer2Only");;
		if (pfOpenCashDrawer2Only)
		{
			pfOpenCashDrawer2Only();
		}
#endif

		FreeLibrary(hLibrary);
	}
	else
	{
		std::cout << "Failed To Load Library" << std::endl;
	}
#endif


	return 0;



}
```

**Comment by haipt17** [comment] 2022-04-13 07:57
Hi @tresf ,

My email is: haipt.ict@gmail.com

Thank you so much.

**Comment by haipt17** [comment] 2022-04-13 08:15
Hi @tresf ,

I got your email, and downloaded files.

Thank you again.

**Comment by haipt17** [comment] 2022-04-13 08:27
Hi @tresf ,

About RJ11/RJ12, I try [Microsoft Point of Service for .NET v1.14](https://www.microsoft.com/en-us/download/details.aspx?id=42081), and it work with FEC device.

I don't know how, but I think "proprietary" is not problem.

Some reasons, I can't screenshot or take photo of real POS System.

This is Microsoft Point of Service for .NET v1.14 

![image](https://user-images.githubusercontent.com/22137804/163133076-c4dda463-4d9d-4965-9f82-97a17ed5b1be.png)

Maybe it help you to progress new qz features.

**Comment by tresf** [comment] 2022-04-13 15:38
> I don't know how, but I think "proprietary" is not problem.

To whom? 🤔

I encourage anyone needing this feature to study JNA and provide us a working Java example.  I would challenge the same person to provide an example with Sunix libraries as well, so we can abstract the API in a way that will work with future hardware vendors.

**Comment by tresf** [comment] 2022-04-13 15:41
> About RJ11/RJ12, I try [Microsoft Point of Service for .NET v1.14](https://www.microsoft.com/en-us/download/details.aspx?id=42081), and it work with FEC device.

Oh!  This is very interesting and would make integration much more doable if we can achieve this without hard-coding references  to proprietary `.dll` file(s).

**Comment by haipt17** [comment] 2022-04-15 07:23
Hi @tresf ,

I found something and can open (kick) RJ11 Cash drawer (it works)

```
Step 1:  v1.0.9.rar ( file in email ) , I got fec_cashdrawer_module.exe and dll files ( folder A )

Step 2: Write new java class, with jna Native.load("FEC_CashDrawerDLL"), use function OpenCashDrawer() 
 ( noted in FEC CashDrawer SDK Integration Guide V0.8.pdf )

Step 3: Call function in websocket logic ( PrintingUtilities.processPrintRequest(....) 

Step 4: Update nsis files, ro copy all file in folder A (1) to installation directory.

Step 5: Set Windows PATH system variable, add folder A (1) to path
```

```
Because: in folder A (1), I got 4 dll files and fec_cashdrawer_module.exe.

If not set PATH, I got message like that
```

![image](https://user-images.githubusercontent.com/22137804/163536434-8d1c0afc-ab3f-4929-b148-cef7f0721453.png)

And I must do manual (Windows edit the system environment variables: step by step), not by java code ( or nsis, ant )

So, can you support me: how setup PATH system variable, by nsis or java.

Thank you for your attention and support.

**Comment by tresf** [comment] 2022-04-15 20:11
> So, can you support me: how setup PATH system variable (administrator), by nsis or java.

In short, you **should** be able to copy it to `libs` as a stop-gap.

The long of it is a bit more complicated... Since 2.2, we have a utility class for this.  This has some helpers that can find a `.dll` and set any system properties to inform JNA.  This is important to avoid DLL pollution (for stability and for security).

https://github.com/qzind/tray/blob/875c7038cf18a4ae8ac440627f13230aeddaecee/src/qz/App.java#L33-L33

If you prefer to install this file somewhere else, I believe the Java System property `jna.library.path` is how you would set this, but I believe we [clobber this at runtime](https://github.com/qzind/tray/blob/875c7038cf18a4ae8ac440627f13230aeddaecee/src/qz/utils/LibUtilities.java#L131), so you will need to re-use our `libs` location, or attempt to add support for multiple paths.  Another option is to [just hard-code the path](https://stackoverflow.com/a/16093787/3196753) when calling `Native.loadLibrary(...)`.

**Comment by tresf** [comment] 2022-04-15 20:15
For troubleshooting (quoting JNA):

> You may set the system property `jna.debug_load=true` to make JNA print the steps of its library search to the console.

**Comment by tresf** [comment] 2023-04-22 15:13
@haipt17 since we don't plan on adding support for 3rd party DLLs at this time, I think we should close this out in favor of #63.  I hope that's OK?  If you end up getting communication working with QZ Tray and the vendor proprietary DLL, please feel free to share it here or open a PR with the code for others to use.

If you feel this bug report was closed prematurely or in error, please let us know and we'll happily reopen it.

**Closed by tresf** 2023-04-22 15:13 UTC
Labels: question, support
