### ISSUE TITLE
java.lang.IllegalArgumentException: newPosition > limit: (8193 > 8192)

### ISSUE THREAD

**Issue by mlscherer** [qzind/tray#1050] opened 2022-12-06 14:49 UTC
Hello

We are having a problem with one device, which when trying to perform some specific prints, closes the connection with the QZ Tray and does not print...

We tried to perform the exact same prints on other devices and it worked fine. In fact, on that same device, it works when printing multiple identical documents, just with a few different variables.

We collect this log for debugging...

```
[DEBUG] 2022-12-06T11:09:44,956 @ qz.printer.PrintServiceMatcher:-1
	Searching for PrintService matching IMPRESSORA TESTE
[DEBUG] 2022-12-06T11:09:44,960 @ qz.printer.PrintServiceMatcher:-1
	Found 8 printers
[DEBUG] 2022-12-06T11:09:44,961 @ qz.printer.PrintServiceMatcher:-1
	Found match: IMPRESSORA TESTE
[ERROR] 2022-12-06T11:09:45,427 @ qz.ws.PrintSocketClient:-1
	Connection error
java.lang.IllegalArgumentException: newPosition > limit: (8193 > 8192)
	at java.nio.Buffer.createPositionException(Buffer.java:318) ~[?:?]
	at java.nio.Buffer.position(Buffer.java:293) ~[?:?]
	at java.nio.ByteBuffer.position(ByteBuffer.java:1094) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:290) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:181) ~[?:?]
	at java.io.Reader.read(Reader.java:229) ~[?:?]
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2001) ~[qz-tray.jar:?]
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1980) ~[qz-tray.jar:?]
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1957) ~[qz-tray.jar:?]
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:819) ~[qz-tray.jar:?]
	at qz.ws.PrintSocketClient.onMessage(Unknown Source) ~[qz-tray.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.lambda$onTextFrame$1(JettyAnnotatedEventDriver.java:270) ~[qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[qz-tray.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
[INFO] 2022-12-06T11:09:45,456 @ qz.ws.PrintSocketClient:-1
	Connection closed: 1011 - newPosition > limit: (8193 > 8192)
[INFO] 2022-12-06T11:09:45,458 @ qz.ws.SocketConnection:-1
	Closing all communication channels for *.ourwebsite.com.br
```

**Comment by mlscherer** [comment] 2022-12-06 15:11
@tresf thanks for the fast reply...

Anything that I can do to help into that?

The device is from one of our clients, but if you want to, I can ask for us to connect there...

**Comment by tresf** [comment] 2022-12-07 03:32
Assuming this is on a Windows machine... 

For starters I would recommend a few sanity checks:
* If the problem only persists with one browser on the machine, repair or reinstall that browser.
* If the problem is persistent on all browser on that machine:
   * Ensure the device's network driver is up to date and that the connection is good to ensure packet corruption or packet loss isn't a cause.
   * Ensure the PC is up to date and the the drive is scanned for errors to help thwart in-memory or storage issue.
   * Ensure there is not man-in-the-middle behavior such as security software/virus intercepting traffic to our software
   * Test against the 2.2.1 beta version from our downloads page, which will use its own version of Java

There's also a slight chance that the error is misleading and it's actually a software crash causing the issue.  If the software crashes only when searching for printers, the fastest fix is usually to remove the offending printer (we don't have an easy way to identify this yet).  In some cases, the printer is not visible in control panel, but remnants in the registry cause problems with Java's communication with the Windows print spooler.

Hopefully that's a good start.

**Comment by tresf** [comment] 2023-04-01 19:39
So we've had some more reports of this error... from what I can gather so far, it only occurs on Windows machines running 2.1.6 or 2.2.2 and we believe it to be related to the version of Jetty that we bundle.

Oddly, the Jetty versions are identical in these releases, so pinpointing it is a bit harder.

We do have a bleeding edge version of QZ Tray running Jetty 10.0, which in our tests fixes this issue: https://github.com/tresf/tray/releases/download/v2.2.3/qz-tray-2.2.2+14-x86_64.exe

Since upgrading Jetty from 9.4 to 10.0 is considered a significant change, the patch will need to be part of QZ Tray 2.2.3.  We may expedite this release if we get more reports of this error.

**Comment by dogrocker** [comment] 2023-06-28 02:38
Got same error on 2.2.2 windows machines.

**Comment by tresf** [comment] 2023-06-28 14:56
@dogrocker can you please confirm whether or not the linked installer from my previous post fixes this?

**Comment by extmag** [comment] 2023-08-19 08:33
Hello. Got the same error on 2.2.2+1 Windows machines.

**Comment by tresf** [comment] 2023-08-19 17:21
> Hello. Got the same error on 2.2.2+1 Windows machines.

@extmag can you please confirm whether or not the installer linked from my previous comment fixes this for you? https://github.com/qzind/tray/issues/1050#issuecomment-1493086315

**Comment by extmag** [comment] 2023-08-20 08:32
@tresf at the moment I don't have that option. But I already solved the problem. Previously, I was trying to send raw PDF data to a printer and was getting this error. Then I changed the code and used
```
type: 'pixel',
format: 'pdf',
flavor: 'base64'
```
And this code solved my problem.

**Comment by tresf** [comment] 2023-08-21 13:31
> @tresf at the moment I don't have that option. But I already solved the problem. Previously, I was trying to send raw PDF data to a printer and was getting this error. Then I changed the code and used
> 
> ```
> type: 'pixel',
> format: 'pdf',
> flavor: 'base64'
> ```
> 
> And this code solved my problem.

Thanks for the workaround, however we are committed to fixing this problem at its source.

**Comment by tresf** [comment] 2023-08-30 15:24
> Hi, in my case it occurs when i send a print job with a logo:

Can you please test the installer here and let me know if it fixes it?  https://github.com/qzind/tray/issues/1050#issuecomment-1493086315

If you're not on Windows, let me know, so far we've only seen this issue on Windows.

**Comment by johangm90** [comment] 2023-08-31 03:52
> > Hi, in my case it occurs when i send a print job with a logo:
> 
> Can you please test the installer here and let me know if it fixes it? [#1050 (comment)](https://github.com/qzind/tray/issues/1050#issuecomment-1493086315)
> 
> If you're not on Windows, let me know, so far we've only seen this issue on Windows.

I tested on Windows, Linux, and macOS with different browsers, but the same result occurred.

**Comment by tresf** [comment] 2023-08-31 04:11
> I tested on Windows, Linux, and macOS with different browsers, but the same result occurred.

Which version?

**Comment by johangm90** [comment] 2023-08-31 14:36
> > I tested on Windows, Linux, and macOS with different browsers, but the same result occurred.
> 
> Which version?

I have tried using version 2.2.2. I have also tried it on Windows with the installer provided in comment 1050, and it works, but 
the logo doesn't print well.

![1swsi27h](https://github.com/qzind/tray/assets/990211/979e7f3d-03be-485d-9541-678308219778)

**Comment by tresf** [comment] 2023-10-27 04:15
QZ Tray 2.2.3 has been released, which we believe fixes this issue.

**Closed by tresf** 2023-10-27 04:15 UTC
Labels: needs confirmation
