### ISSUE TITLE
Automatically start option missing in macOS

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#172] opened 2017-02-25 00:36 UTC
QZ Tray 2.1.0

The "Automatically start" option is missing in the tray drop down on macOS.

![image](https://cloud.githubusercontent.com/assets/12505463/23326025/f8f8ed66-fac7-11e6-8834-36c2d2bd3e77.png)

This option appears in Windows
![image](https://cloud.githubusercontent.com/assets/12505463/23326082/74340196-fac8-11e6-9ce4-9c66b79e094e.png)

**Comment by tresf** [comment] 2017-02-25 02:31
Duplicate of https://github.com/dorkbox/SystemTray/issues/49#issuecomment-281670741.  Will be fixed when dorkbox is upgraded.

**Closed by tresf** 2017-02-25 02:31 UTC
