### ISSUE TITLE
Combining html and raw

### ISSUE THREAD

**Issue by vkosachev** [qzind/tray#84] opened 2016-07-22 08:11 UTC
HI guys,
I am trying to combine HTML and raw printing on Epson.
With html I am sending the content I want to print, and with raw I am trying to send the cut directive to printer. The problem is that it is not working then. The question is how to combine that correctly ?
Example:
```js
        var cfg = qz.configs.create(printer,
                {
                    orientation: 'portrait',
                    color: 'color',
                    copies: 1,
                });
        var data = [
            {
                type: 'html',
                format: 'plain',
                data: printData
            },
            // not working
            {
                type: 'raw',
                format: 'plain',
                data : '\n' + '\x1B' + '\x69'
            }
        ];
        qz.print(cfg, data).then(function(success)
        {
            // this works, but it is not a viable solution when printing lots of tickets in quick succession
            // qz.print(cfg, ['\n' + '\x1B' + '\x69'])
        }).catch(function(e)
        {
            console.error(e);
        });`

**Comment by lite1979** [comment] 2016-07-22 15:06
@vkosachev 

The problem is usually that mixed format sent to the same printer will require two different queues (even though they both point to the same printer). This can result in a race condition once the print jobs are sent, since the HTML usually requires a bit of processing before being sent to the printer, allowing the ESCP to arrive to the printer first. 

The way around this is to use our alternate printing method so everything is sent to the same printer First In, First Out. Here is a working example that we've tested on our TM-T88V using HTML, Image, then raw ESCP to print a receipt:

`function printESCP() {
        var config = qz.configs.create("Epson-TM-BA-Thermal");
        var data = [{
        type: 'html',
        format: 'plain', // or 'plain' if the data is raw HTML
        data: ' <html><header><title>This is the title</title></header><body>Hello world</body></html>'
        }];
        qz.print(config, data)

       .then(function() {
            var config = qz.configs.create("Epson-TM-BA-Thermal");
            var data = [{
                type: 'image',
                data: 'assets/img/image_sample.png'
            }];
            return qz.print(config, data);
        })
   

        .then(function() {       
            var config = qz.configs.create("Epson-TM-BA-Thermal",{altPrinting:true});
            var printData = [
                '\x1B' + '\x40', // init
                '\x1B' + '\x61' + '\x31', // center align
                'Canastota, NY  13032' + '\x0A',
                '\x0A', // line break
                'www.qzindustries.com' + '\x0A', // text and line break
                '\x0A', // line break
                '\x0A', // line break
                'November 21, 2015 3:09 PM' + '\x0A',
                '\x0A', // line break
                '\x0A', // line break        
                '\x0A',
                'Transaction # 123456 Register: 3' + '\x0A',        
                '\x0A',        
                '\x0A',        
                '\x0A',
                '\x1B' + '\x61' + '\x30', // left align
                'Baklava (Qty 4)                     9.00' + '\x1B' + '\x74' + '\x13' + '\xAA', //print special character symbol after numeric value
                '\x0A',
                'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' + '\x0A',        
                '\x1B' + '\x45' + '\x0D', // bold on
                'Here\'s some bold text!',
                '\x1B' + '\x45' + '\x0A', // bold off
                '\x0A' + '\x0A',
                '\x1B' + '\x61' + '\x32', // right align
                '\x1B' + '\x21' + '\x30', // em mode on
                'DRINK ME',
                '\x1B' + '\x21' + '\x0A' + '\x1B' + '\x45' + '\x0A', // em mode off
                '\x0A' + '\x0A',
                '\x1B' + '\x61' + '\x30', // left align
                '------------------------------------------' + '\x0A',
                '\x1B' + '\x4D' + '\x31', // small text
                'EAT ME' + '\x0A',
                '\x1B' + '\x4D' + '\x30', // normal text
                '------------------------------------------' + '\x0A',
                'normal text',
                '\x1B' + '\x61' + '\x30', // left align
                '\x0A' + '\x0A' + '\x0A' + '\x0A' + '\x0A' + '\x0A' + '\x0A',
                '\x1B' + '\x69', // cut paper

            ];
            return qz.print(config, printData);
       
        });
       
}`

If you only need the ESCP code for cutting the paper, then this can be configured on the local machine as well (in CUPS, or Windows Printer settings). You may then simply issue an HTML print job by itself, as the printer should cut paper after each 2d/pixel-based print job.

**Comment by vkosachev** [comment] 2016-07-22 15:48
@lite1979 hey, thanks for your feedback. Actually as you could notice I am doing just the same thing.
But this leads to some problems when I print lots of tickets in quick succession.
In this case I get printed out 2-3 html tickets and the my TM-L90 bloats out some blank paper and only then cuts it

**Comment by lite1979** [comment] 2016-07-22 16:06
You are doing something similar, but not exactly the same. I have used a separate function for each print job, and .then promises to send them in that order.

I don't know if you're testing on Windows or Linux or Mac, but {altPrinting:true} will be necessary for both Linux and Mac clients, as CUPS normally uses separate queues for raw and html print jobs. altPrinting:true allows raw print jobs to be sent to an html queue's printer without any formatting.

I recommend a separate function for each type of printing (raw, html, image, pdf, et cetera) and forcing them all to be sent to the same queue to ensure that they are processed in order.

**Comment by tresf** [comment] 2016-07-22 17:19
> In this case I get printed out 2-3 html tickets and the my TM-L90 bloats out some blank paper and only then cuts it

Can you please share your looping logic for us to see?  Chaining promises in a loop is a special edge-case.

https://qz.io/wiki/2.0-Raw-Printing#promise-loop

**Comment by vkosachev** [comment] 2016-07-25 07:21
Sure, the most of the code I pasted upper.
```js
function sendHTMLToQz(printData)
{
    if (!qzConnectionEstablished())
    {
        displayMessage("No active connection with QZ exists.", 'alert-danger');
        return;
    }

    qz.printers.find("EPSON TM-L90 Receipt").then(function(printer)
    {
        var cfg = qz.configs.create(printer,
                {
                    orientation: 'portrait',
                    color: 'color',
                    copies: 1,
                });
        var data = [
            {
                type: 'html',
                format: 'plain',
                data: printData
            }
        ];
        qz.print(cfg, data).then(function(success)
        {
            qz.print(cfg, ['\n' + '\x1B' + '\x69'])
        }).catch(function(e)
        {
            console.error(e);
        });
    }, function(error)
    {
        displayMessage("Printer EPSON TM-L90 Receipt is not found", "alert-danger");
    });
}

The problem is that i need to cut paper programmatically
```

**Comment by tresf** [comment] 2016-07-25 17:28
@vkosachev are you calling `sendHTMLToQz()` over and over in succession?  If so, that won't work, you'll instead need to use a [promise loop](https://qz.io/wiki/2.0-Raw-Printing#promise-loop).

@vkosachev if you cannot resolve the race conditions, it is likely you'll need to wait for #19 to be completed prior to this working.

#19 will allow HTML to ESCP image translation which would avoid the redundant queue and thus the race condition.

**Comment by vkosachev** [comment] 2016-07-26 08:00
@tresf yeah, it can be said that yes. I have just ajax calls that launch `sendHtmlToQZ()` so it depends on the final user with what speed he clicks. I have tried to implement the promise loop that you show, but the result is different. guess it is all because of ajax calls.

@tresf Can you give some schedule when this feature can be expected? Thx in advance.

**Comment by tresf** [comment] 2016-07-26 14:08
> > But this leads to some problems when I print lots of tickets in quick succession.

> I have just ajax calls that launch sendHtmlToQZ() so it depends on the final user with what speed he clicks. 

If you are going to allow the user to click, you'll need to queue the clicks and allow the interface to process them.

Are you saying if you print 5 labels using a promise loop technique it's not working 100% of the time?

> @tresf Can you give some schedule when this feature can be expected? Thx in advance.

January.

> P.S. also, just wondering, maybe exists a way to specify the queue the print jobs are sent to? If we could specify the same queue via config I guess this would help to solve the issue ?

I think we're stating the same thing.  You'll need to creating a print stack and pop items onto that stack.  Our "[Job](https://qz.io/wiki/2.0-Raw-Printing#promise-loop)" example should be a good start for this logic.

**Comment by tresf** [comment] 2016-07-26 14:10
I really don't think #19 will fix your issue specifically.  It sounds like a race condition and I believe your fix will exist in a queuing mechanism.

**Comment by vkosachev** [comment] 2016-07-26 14:41
@tresf  I don't know why, but I did not achive the desired result with the "Job" example. heres my implementation of it, maybe you can show what can be improved.

```js
function initPrintJobs() {
    var printJobs = [];
    var lastResult = Promise.resolve();
    return {
        add: function(job) {
            printJobs.push(job)
        },
        get currentJob() {
            return printJobs.shift();
        },
        get hasJobs() {
            return !!printJobs[0];
        },
        get lastResult() {
            return lastResult;
        },
        setLastResult: function(value) {
            lastResult = value;
        }
    }
}
//making it global
var printChain = initPrintJobs();
 
function sendHTMLToQz(printData)
{
    if (!qzConnectionEstablished())
    {
        displayMessage("No active connection with QZ exists.", 'alert-danger');
        return;
    }
 
    var cfg = qz.configs.create(printer,
            {
                orientation: 'portrait',
                color: 'color',
                copies: 1,
            });
    var data =
        {
            type: 'html',
            format: 'plain',
            data: printData
        }
    ;
    var cmds = [ data,  '\n' + '\x1B' + '\x69'];
    function Job(printer, configs, data)
    {
        this.print = function()
        {
            return qz.printers.find(printer).then(function(found)
            {
                return qz.print(qz.configs.create(found, configs), [data])
                .catch(function(e)
                {
                    console.error(e);
                });
            }, function(error)
            {
                displayMessage("Printer EPSON TM-L90 Receipt is not found", "alert-danger");
            });
        }
    };
    var printer = "EPSON TM-L90 Receipt";
    for (var i = 0; i < cmds.length; i++)
    {
        printChain.add(new Job(printer, cfg, cmds[i]));
    }
 }
   print();
    function print() 
    {
      printChain.lastResult.then(function() 
      {
        if (printChain.hasJobs) 
        {
            printChain.setLastResult = printChain.currentJob.print();
            print();
        }
      });
    }
```

**Comment by tresf** [comment] 2016-07-29 19:43
Calling `print()` recursively like you have is a creative approach but it is not one we've tested.  Was there an issue with the [`chain.reduce` logic](https://qz.io/wiki/2.0-Raw-Printing#promise-loop) from our example?  That has been tested against Promises successfully.

**Comment by vkosachev** [comment] 2016-07-30 13:10
@tresf well yes. that is why i have reworked the example in solution that I have provided.  My problem is that when I have more than 3 quick ajax calls  I  get different resuts all the time : if there were 3 calls, I get first ticket printed and cut, then I get html for 2 tickets and 2 blank cuts. With 5+ calls I get all the html first and then the cutting.

**Comment by tresf** [comment] 2016-07-30 16:23
If you're using AJAX somewhere, it's not in the example.

AJAX is mostly promise compatible and you should include that somewhere in your promise chain if each AJAX request is followed by a subsequent print.

```diff
- function Job(printer, configs, data)
+ function Job(printer, configs, ajaxURL)
      {
          this.print = function()
          {
              return qz.printers.find(printer).then(function(found)
              {
+                printer = found;  // so we don't lose the actual printer name
+                return $.ajax(ajaxURL);
              }).then(function(data)
+             {
-                 return qz.print(qz.configs.create(found, configs), [data])
+                 return qz.print(qz.configs.create(printer, configs), data)
              }).catch(function(e)
              {
                      console.error(e);
              });
+              // Errors are thrown up the stack
+              // Can display message based on the error contents instead.
-              }, function(error)
-              {
-                  displayMessage("Printer EPSON TM-L90 Receipt is not found", "alert-danger");
-              });
          }
      };
```

**Comment by tresf** [comment] 2016-08-04 02:51
Closing this out as a support request.  Please continue to use it for question/answer as needed, but the bug will remain in closed status.

**Closed by tresf** 2016-08-04 02:51 UTC
