### ISSUE TITLE
 Trojan Horses

### ISSUE THREAD

**Issue by keyiis** [qzind/tray#358] opened 2018-10-08 07:27 UTC
When i install qz-tray-2.0.7 ,system firewall tip "trojan Horses",so can't complate install.
![image](https://user-images.githubusercontent.com/7766085/46596355-e2367300-cb0e-11e8-949d-22f2bae9a171.png)

**Comment by tresf** [comment] 2018-10-08 17:27
That's not a trojan horse, that's a heuristics scan that's incorrect.  Duplicate of #321.

**Closed by tresf** 2018-10-08 17:27 UTC
