### ISSUE TITLE
How about TSPL to CPCL

### ISSUE THREAD

**Issue by H246802** [qzind/tray#470] opened 2019-07-22 12:21 UTC
If anyone knows the answer, tell me。thank

**Comment by tresf** [comment] 2019-07-22 14:20
TSPL (Taiwan Semiconductor Programming Language) and CPCL (Comtec Printer Control Language) are two completely different specifications, no direct conversion exists.

Below are both examples, converted to QZ Tray.  You will note that some commands are very similar, specifically `TEXT`, `BAR`, `PRINT` and can probably be converted manually with trail-and-error, however most commands are printer-specific, so this technique should only be used for basic labels.

Example TSPL Label:
```js
// TSPL (Converted to JavaScript for use with QZ Tray)
var data = [{
   'SIZE 4,3\r\n',
   'GAP 0,0\r\n',
   'DIRECTION 1\r\n',
   'CLS\r\n',
   'TEXT 10,10,"0",0,12,12,"TSPL 2"\r\n',
   'TEXT 10,40,"0",0,8,8,"align left"\r\n',
   'BAR 0,70,800,4\r\n',
   'TEXT 10,110,"0",0,12,12,"FONT 0"\r\n',
   'TEXT 10,160,"1",0,1,1,"FONT 1"\r\n',
   'TEXT 10,210,"2",0,1,1,"FONT 2"\r\n',
   'TEXT 10,260,"3",0,1,1,0,"FONT 3"\r\n',
   'TEXT 10,310,"4",0,1,1,0,"FONT 4"\r\n',
   'TEXT 10,360,"5",0,1,1,0,"FONT 5"\r\n',
   'TEXT 10,410,"6",0,1,1,1,"FONT 6"\r\n',
   'TEXT 10,460,"7",0,1,1,1,"FONT 7"\r\n',
   'TEXT 10,510,"8",0,1,1,1,"FONT 8"\r\n',
   'PRINT 1\r\n'
}];
```

Example CPCL Label:

```js
// CPCL (Converted to JavaScript for use with QZ Tray)
var data = [{
   '! 0 200 200 581 1\r\n',
   ';media p/n LD-E9QT7S\r\n',
   'LABEL\r\n',
   'CONTRAST 0\r\n',
   'TONE 0\r\n',
   'SPEED 3\r\n',
   'PAGE-WIDTH 240\r\n',
   'BAR-SENSE\r\n',
   ';// PAGE 0000000002400600\r\n',
   ';// TEXT 0 1 3 560 DEPT 34\r\n',
   'TEXT90 4 3 36 288 $22.88\r\n',
   'TEXT90 5 2 163 273 SWEATSHIRT\r\n',
   'VBARCODE UPCA 2 1 45 139 576 04364503284\r\n',
   'TEXT90 7 0 191 511 043645032841\r\n',
   'TEXT90 5 0 4 524 COMPARE AT\r\n',
   'TEXT90 5 0 115 575 ZD-180-KL\r\n',
   'TEXT90 5 2 119 269 ALL COTTON\r\n',
   'TEXT90 7 0 114 389 01/17/98\r\n',
   'TEXT90 0 0 208 173 EA00-732-00560\r\n',
   'TEXT90 5 0 82 519 ELSEWHERE\r\n',
   'BOX 189 358 217 527 1\r\n',
   'FORM\r\n',
   'PRINT\r\n'
}];
```

Closing, as this is not a bug, defect or enhancement with QZ Tray.

**Closed by tresf** 2019-07-22 14:20 UTC
Labels: question
