### ISSUE TITLE
Some config options ignored on Windows

### ISSUE THREAD

**Issue by mrwedders** [qzind/tray#117] opened 2016-10-14 09:43 UTC
Hi everyone,

I'm using a built-from-source version of QZ Tray (so I can use my own certs, no other changes) in production on a Windows 7 machine, and a Mac which is my dev machine, both with Zebra GK420d printers (using the ZDesigner driver on Windows).

We have a certain PDF which is A4, but for speed reasons we want to print these on our 4x6" labels. Normal portrait orientation is too small, but the document only uses about 1/3rd the height of an A4 page so I've been trying to print it landscape and scaled to better fit the label width.

On the Mac I've got this working by changing the config passed to qz.print(), setting orientation to landscape and an inflated page size so it scales appropriately.

Trying the same thing on a PC all of these options seem to be overridden by the page size and orientation set in the driver settings. The rotation property does have an effect (as I assume this is passed to PDFBox when it processes the document) but without the increased paper size to scale it it's useless. Problem is we print multiple documents with the same system and we only need one of them rotated and scaled in this way, so we can't just set it in the driver.

Can this be overcome or will Windows always defer to the driver settings?

Thanks for any help!

**Comment by tresf** [comment] 2016-10-14 20:51
Have you tried a 4x6 PDF with a 4x6 size specified?

4x6 PDF: [barcode.pdf](https://github.com/qzind/tray/files/426462/barcode.pdf)


We've had the best results when the PDF is the same dimensions as the paper and the paper size ia expliciy defined.

If compiling from source, you may also be happy with 2.1 which offers a new feature to raster the PDF to pure ZPL/EPL.


https://github.com/qzind/tray/issues/19#issuecomment-239575789

**Comment by jetharamchoudhary** [comment] 2016-10-17 07:46
HI @mrwedders 

How are you using you certificates for QZ Tray. We also want to use but have no idea from where to start.

Could you please help us setting up those certificate. You also mentioned that you are using MAC device. We stuck in using Qz on IPAD.

Any help would be much appreciated.

Thanks,
Jetha

**Comment by mrwedders** [comment] 2016-10-17 13:05
Hi @tresf: Changing the document paper size isn't really an option - the PDFs in question are shipping documentation we're receiving directly from the courier. I have looked in to how we could modify the paper size and/or crop the document in our server side Perl, but most methods looked complicated and bulky so I was a bit put off! 
I'll take a look at the ZPL/EPL stuff in 2.1, that sounds interesting and - as you say - more reliable!
Thanks for your help :)

@jetharamchoudhary: I spent a while trying to work it out too, you can't do it with the version currently downloadable on qz.io (2.0.1), you have to build it from source. If you [look at the compilation page on the wiki](https://github.com/qzind/tray/wiki/compiling) you'll see you can specify a custom root certificate with the -Dauthcert.use parameter. I built a Windows and Mac package with this and both work perfectly.
As far as the certs go I generated them with OpenSSL through cygwin on my Windows box - I think they have to be 2048 bit, but that's the only requirement.
I have no idea about running this on an iPad though, don't think it's possible!

**Comment by tresf** [comment] 2016-10-17 15:17
I'll step back a bit and address the OP's questions... 

> Trying the same thing on a PC all of these options seem to be overridden by the page size and orientation set in the driver settings. 

This sounds peculiar.  The way Java and the driver generally work is it will print to the best matched configuration.  This should be identical between both systems.  For example, if you are specifying a paper size of 4x6 and landscape in the configuration, the Zebra driver should honor this and print accordingly.

> The rotation property does have an effect (as I assume this is passed to PDFBox when it processes the document) but without the increased paper size to scale it it's useless. 

We actually had to write [custom code](https://github.com/qzind/tray/commit/a27a5c63f4f3b93ddef309e5eb5ae8208b7a03a1) to get rotation working properly (https://github.com/qzind/tray/issues/12).

We have hardware that we can reproduce on, can you please give us exact steps to reproduce including sample PDF files, expected behavior and actual behavior?  Then we'll reproduce what you're seeing and determine if we need to fix something in the library.

**Comment by tresf** [comment] 2016-10-19 02:01
> Could you please help us setting up those certificate. You also mentioned that you are using MAC device. We stuck in using Qz on IPAD.

@jetharamchoudhary You're likely talking about configuring SSL for use with an iPhone/iPad.  This is a different certificate entirely.  For Trusted SSL on all browsers:
 1. Generate a [JKS/CSR from your certificate provider](https://www.digicert.com/csr-creation-java.htm) 
 2. [Import the cert back into that same JKS](https://docs.oracle.com/javase/tutorial/security/toolsign/rstep2.html).
 3. Add all relevant JKS information to `<installdir>/qz-tray.properties`

Back on topic... @mrwedders please the configuration and sample PDF so that others can reproduce.

**Comment by lite1979** [comment] 2016-10-19 03:51
@mrwedders 

Using an A4 PDF and forcing 4" wide by 6" tall, scaleContent: true, I was able to print to my Zebra LP 2844-Z using the ZDesigner driver and Windows 10.

It should be noted that the ZDesigner driver originally set the paper size for my printer to 3" wide by 2" tall. Without forcing the size, the printed portion only occupied the upper-left quadrant of my label.

Again, we'll be happy to test using your PDF example. If the attached picture does not represent the desired results, please explain and we'll do our best to re-create using your file.
![img_20161018_233409184](https://cloud.githubusercontent.com/assets/3408749/19505120/cc42f270-958d-11e6-9739-a8d8e1df0498.jpg)

**Comment by tresf** [comment] 2016-11-09 00:58
@mrwedders can yous see if https://github.com/qzind/tray/commit/56f172804b3d4907b26392eb6b506cfdae076927 fixed this problem?  PDFBOX fixed their orientation problem upstream, breaking our [workaround on Windows and Linux](https://github.com/qzind/tray/commit/9ecb07b560a66d46d440726a53a84b1fe722b12f#diff-5599221006c45202322d1e707eb793d2R100).  Mac has a bug which [ignores orientation](https://github.com/qzind/tray/commit/17e419581ba2e7cd9a9ef799a9cb43da53fc7127#diff-5599221006c45202322d1e707eb793d2R93), explaining why that was working on that platform.

**Comment by tresf** [comment] 2016-11-18 02:35
Since https://github.com/qzind/tray/commit/56f172804b3d4907b26392eb6b506cfdae076927 went live with 2.0.2, marking this as resolved.  Please reopen if you believe this was closed in error.

**Closed by tresf** 2016-11-18 02:35 UTC
