### ISSUE TITLE
Expired Certificate Causes Client Disconnected

### ISSUE THREAD

**Issue by dsanders11** [qzind/tray#150] opened 2017-01-07 13:19 UTC
Ran into this when the certificate being used to sign print requests (but not the trusted root certificate) expired. The only 'symptom' was that connecting to QZ Tray would fail, and it would display the message 'Client has disconnected'.

Here's what was logged for this scenario. At the time the QZ Tray version was 2.0.1, later updated to 2.0.2, but I don't think this behavior changed between the two versions.

````
2017-01-06 09:42:21,648 [DEBUG] Received new certificate from connection through 58029
2017-01-06 09:42:21,649 [INFO] Denied Web Shipping Label Printing to connect to QZ
2017-01-06 09:42:21,652 [INFO] Connection closed: 1006 - Disconnected
2017-01-06 09:42:21,653 [INFO] Closing all communication channels for Web Shipping Label Printing
````

While there appears to be [some logic in QZ Tray for logging a warning about expired certificates](https://github.com/qzind/tray/blob/2bf75cb74acc436fa391251a3ff12273db18d23b/src/qz/ws/PrintSocketClient.java#L198), I think this situation causes a deny before that logic is run, so nothing is logged regarding the reason for denying the connection.

Ideal behavior would a warning in the logs for this situation, and a more clear UI message than 'Client has disconnected'.

I think this issues dovetails with #43 in a way. It would be nice if QZ Tray started warning the user if a certificate has less than 30 days until it expires, to help remind to renew. Maybe a dialog that warns the user and has a "Don't show message again" checkbox so that it isn't shown on every connect request.

**Comment by tresf** [comment] 2017-01-07 21:00
> While there appears to be some logic in QZ Tray for logging a warning about expired certificates

That line of code specifically is for an expired signature.  We only allow signed messages to be valid for `Constants.VALID_SIGNING_PERIOD` (15 minutes).

> `Connection closed: 1006 - Disconnected`

If an expired cert is doing this, this is a pretty serious bug.

> It would be nice if QZ Tray started warning the user if a certificate has less than 30 days until it expires,

We considered this too but for our larger clients, they may get flooded with support calls, so we opted against it.  We used to have a bubble in the corner that was usable (Win XP, Vista, 7) but Windows 8/10 turned it into a [sliding chime noise distraction](https://cloud.githubusercontent.com/assets/6345473/21745129/321ae5c8-d4f2-11e6-932a-16c495aac135.png) and Mac has some [very strange behavior](https://github.com/qzind/qz-print/issues/169) so we abolished the idea.

> ... dovetails with https://github.com/qzind/tray/issues/43

Agreed, in a way.  We'll attempt to reproduce.  Thanks.

**Comment by tresf** [comment] 2017-01-07 21:09
BTW, `1006` is [`CLOSE_ABNORMAL`](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent), which we should never be doing intentionally in our API.

**Comment by dsanders11** [comment] 2017-01-09 03:38
Here are some more details if they'll help.

In this case the trusted root certificate was still valid through 2018, and hasn't changed in the last year plus. On initial report by users I thought it was the websocket certificate which had expired (I use Let's Encrypt certificates so they only last 90 days) and I had just gotten the expiration date wrong. Replaced it and still had the same issue, then noticed that it didn't expire until the 10th anyway, as I originally thought.

So at that point I poked around on what else might have changed by itself and that's when I noticed the certificate being used by the server to sign print requests had expired. Replacing it fixed everything and we're back to normal operation.

The QZ Tray instance was 2.0.1 (then upgraded to 2.0.2 and still same problem) running on Windows 7.

**Comment by tresf** [comment] 2017-02-08 04:37
@dsanders11 I've reproduced the error and this is intended behavior and not nearly as severe as described.  I'll explain... (Expired keypair used for testing here: [expired-cert.zip](https://github.com/qzind/tray/files/759691/expired-cert.zip))

![image](https://cloud.githubusercontent.com/assets/6345473/22723638/21ad8c5e-ed8e-11e6-8078-f92bff06f04e.png)


In the case of your use-case page, the "Block" button was clicked (intentionally or not), which can happen with both valid as well as invalid certificates and cause the same `1006` disconnect error.  This will happen if a user clicked "Block" and subsequently will happen non-obviously over and over again if they also clicked "Remember this decision" but the same error occurs:  `Connection closed: 1006 - Disconnected`

This occurs for good reason.... In this specific case the websocket communication is being terminated before the cert has been approved, which is the first step in the handshake.  If the cert is denied before any requests to access local resources, the websocket will terminate .  QZ Tray will continue to function you may attempt again to call `qz.websocket.connect()` and so as long as "Remember this decision" was not checked, the prompt will appear again on a fresh websocket connection.

This disconnect may seems strange during testing as most programmers are used to the "Block" or invalid signature prompt occurring AFTER a valid certificate has been received.  This is only because we offer a convenience to white-list a cert before any signed messages have been received; yet we offer no such convenience of keeping the websocket open on a denied request, hence this message is uncommon but completely valid.

Closing as `invalid`.

**Closed by tresf** 2017-02-08 04:37 UTC
Labels: needs confirmation
