### ISSUE TITLE
OKI C332 slow print start / long delivery

### ISSUE THREAD

**Issue by lichtamberg** [qzind/tray#377] opened 2018-11-09 12:48 UTC
Right now we are trying to print single page PDF documents, but the problem is that the printer takes really really long to start (around 10-12 Seconds).
When we start the printjob from Acrobat Reader oder Chrome-PDF Plugin, the printing starts within 1-2 Seconds and in our company/use case we really need fast printing times.

We are using OKI C332 with current PCL driver. 
We tried to set rasterize to false, set the density lower, set the print quality to low, adjusted the default print settings in the dirver settings dialogue - but nothing worked so far.

In the windows printer queue, the document pops up quickly, but the pages column shows really long (~12 seconds) "N/A", so it looks like the delivery to the printer takes so long?

Here is the log output

```log
[DEBUG] 2018-11-09 13:55:13,387 @ qz.ws.PrintSocketClient:?
  Message: {"call":"printers.getDefault","promise":{},"signature":"MfXfGAUS3UlnEly3VjIwyF9ByKjsQZiSwK/2v39tW2cGiWvBTtKtfPMSAGsrrdN5rIBG+P7haBGlFLgQKVtVdSBbJy65z/Uuvf3MzQRsgTxxZZI4tL9+Y6H1iKQfz30OacEd7WhrNG/Hb5UszX9MYMbf90dw6b6Wv8K3KRxZaG+rxhWm+Vn1g4uOxR+dLyTS4qGoNEjTd1ra2YDueYOQErqALojH4fvzuWHehadyvCC6K8xIihmT9aRLvSp5TAW20lc2W2jF0MlDDVE557zfHxxC0/JcYV8ERGffoWTELKj+aSiBaiKN4vZfa8IurB09tfuTB9Q6UW4w+vg2p1y7pw==","timestamp":1541768113341,"uid":"0p84r0"}
[TRACE] 2018-11-09 13:55:13,390 @ qz.ws.PrintSocketClient:?
  Valid signature from <redacted>
[DEBUG] 2018-11-09 13:55:13,444 @ qz.ws.PrintSocketClient:?
  Message: {"call":"print","promise":{},"params":{"printer":{"name":"OKI C332 PCL6 (Kopie 2)"},"options":{"colorType":"color","copies":1,"density":0,"duplex":false,"fallbackDensity":null,"interpolation":"bicubic","jobName":"thomas_1541768113394.pdf","margins":0,"orientation":"portrait","paperThickness":null,"printerTray":null,"rasterize":false,"rotation":0,"scaleContent":"false","size":{"width":21,"height":29.7,"margins":0},"units":"cm","altPrinting":false,"encoding":null,"endOfDoc":null,"perSpool":1},"data":[{"type":"pdf","data":"https://orf.flave.world/admin/tag_owners/800c56fc-57f1-4d26-83a2-2323903b82fd.pdf?print_setting_id=238c0b31-2851-4503-a0fb-7da28f294f7b"}]},"signature":"f9mc7G/xuzt4aGn6SGuaBkRe0AyODDJzoZhtApLITlbfJ8/M7aq8G59gnAkdkRsFtuLjKDDA+8+HaRArrMjzx3SLFU8j+Fb3zhJTynZWfCqTrCIYj3y8iEC68JGW480q/gwUdyiBMte+k5LC1DJmgiAfb6MqEtcf+SU0MmBGcZD2ZtuQT+TO0xKkzmXMdA51oA3WwpBxK/8KBYCU1OY5gbj3oWCVA+oW13qF4wueRl7TyIZgNPAxIKDp6m9uOvD/IOGYZ4XFLZaLXhEtQ2mtZUbvZvGefBxXJQwCEwzacF1X0Ca7NASydKm95qE1cGkQighWa+mWCvmDrZgEkiVung==","timestamp":1541768113394,"uid":"01fkb3"}
[TRACE] 2018-11-09 13:55:13,449 @ qz.ws.PrintSocketClient:?
  Valid signature from <redacted>
[TRACE] 2018-11-09 13:55:13,450 @ qz.utils.PrintingUtilities:?
  Waiting for processor, 0/1 already in use
[DEBUG] 2018-11-09 13:55:13,451 @ qz.utils.PrintingUtilities:?
  Using qz.printer.action.PrintPDF to print
[DEBUG] 2018-11-09 13:55:13,451 @ qz.printer.PrintServiceMatcher:?
  Searching for PrintService matching OKI C332 PCL6 (Kopie 2)
[DEBUG] 2018-11-09 13:55:13,451 @ qz.printer.PrintServiceMatcher:?
  Found 17 printers
[DEBUG] 2018-11-09 13:55:13,452 @ qz.printer.PrintServiceMatcher:?
  Found match: OKI C332 PCL6 (Kopie 2)
[DEBUG] 2018-11-09 13:55:13,453 @ qz.utils.PrintingUtilities:?
  Found Resolution: 60000x60000 dphi
[DEBUG] 2018-11-09 13:55:13,729 @ qz.printer.action.PrintPDF:?
  Parsed 1 files for printing
[TRACE] 2018-11-09 13:55:13,762 @ qz.printer.action.PrintPixel:?
  DPI: 0.0  CNV: 28.346401
[TRACE] 2018-11-09 13:55:13,763 @ qz.printer.action.PrintPixel:?
  Drawable area: 0.0,0.0:21.0,29.7
[TRACE] 2018-11-09 13:55:13,763 @ qz.printer.action.PrintPixel:?
  [(0.0,0.0)->(210.0,297.0)mm, portrait, color]
[TRACE] 2018-11-09 13:55:13,768 @ qz.printer.action.PrintPixel:?
  DPI: 0.0  CNV: 28.346401
[TRACE] 2018-11-09 13:55:13,769 @ qz.printer.action.PrintPixel:?
  Drawable area: 0.0,0.0:21.0,29.7
[TRACE] 2018-11-09 13:55:13,769 @ qz.printer.action.PrintPixel:?
  [(0.0,0.0)->(210.0,297.0)mm, portrait, color]
[INFO] 2018-11-09 13:55:13,769 @ qz.printer.action.PrintPixel:?
  Starting printing (1 copies)
[TRACE] 2018-11-09 13:55:13,816 @ qz.printer.BookBundle:?
  Requested page 0 for printing
[DEBUG] 2018-11-09 13:55:13,816 @ qz.printer.PDFWrapper:?
  Paper area: 0,0:595,841
[TRACE] 2018-11-09 13:55:23,579 @ qz.printer.BookBundle:?
  Requested page 0 for printing
[DEBUG] 2018-11-09 13:55:23,580 @ qz.printer.PDFWrapper:?
  Paper area: 0,0:595,841
[INFO] 2018-11-09 13:55:23,692 @ qz.utils.PrintingUtilities:?
  Printing complete
[TRACE] 2018-11-09 13:55:23,692 @ qz.utils.PrintingUtilities:?
  Returning processor back to pool
```

Someone has an idea? Hints appreciated :/

**Comment by lichtamberg** [comment] 2018-11-09 13:15
We also tried to print now from https://demo.qz.io - but it takes the same time unfortunately, so it's not related to our PDF.

**Comment by tresf** [comment] 2018-11-09 14:17
`rasterize: false` and NO density is the absolute fastest Apache PDFBOX has to offer.

12 seconds it's certainly too long.

* If the PCL driver is at fault there may be some amount of recourse if we were to translate to a raw raster format.
* If PDFBOX is at fault things such as system resources OS version, driver version, document size, document content can influence results.

The fastest way for us to reproduce this issue is to have the exact operating system driver version and print configuration / code to test locally.

Assuming this is on Windows... Windows has the luxury of offering a file print interface so we can reproduce any driver or software-related latencies without having the physical hardware.

**Comment by lichtamberg** [comment] 2018-11-09 15:13
Yes, we are using following versions:

Windows 10 HOME 10.0.17134 Build 17134
OKI C332 PCL Driver 6 Version 1.0.7.0 (shown in Windows device manager) from here: https://www.oki.com/eu/printing/support/drivers-and-utilities/colour/46403102/?os=ab2&lang=ac2

We set rasterize: false and set density to null, but it still takes about 10-12 seconds to start printing.

But what I just noticed was, that when we reduce the filesize of the background image (from 192kb to 116kb) it starts to print 2-3 seconds faster. Could it be that certain jpg compression algorithms are better or worse for printing?

**Comment by lichtamberg** [comment] 2018-11-09 15:19
Yeah, it's directly corresponding to the filesize / resolution as it seems. Didn't think that 116kb makes so much difference.. Also printing through Adobe/Google Chrome doesn't have this kind of delay with the same PDF?

**Comment by tresf** [comment] 2018-11-09 16:07
> Could it be that certain jpg compression algorithms are better or worse for printing?

It could.  There are several stackoverflow articles about Java's poor internal JPEG handling.

Can you please share the PDF data with us?  If our `pdf_sample.pdf` experiences the same issues, we'd be happy to use that instead.

**Comment by tresf** [comment] 2018-11-09 16:29
> Also printing through Adobe/Google Chrome doesn't have this kind of delay with the same PDF?

Adobe is **the** standard for PDF printing.
* Adobe invented PDF.  Adobe's results are **nearly always what PDFBOX base many of their benchmarks against**
* That said... PDFBOX is not even remotely related to Adobe.  Instead, it's a crowdsourced effort to reimplement PDF viewing, parsing and print functionality in a portable 100% pure Java (bytecode) interpreted alternative
* As a result there are many performance issues, quality issues and bugs.

Google Chrome uses the much less popular "Pdfium" library.
* Pdfium is a collaborative effort between Foxit and Google
* Pdfium is written in C++ (like Acrobat) so some performance issues that plague Java are not going to exist there.
* Pdfium (as an embedded PDF engine) is growing in popularity because it works and people use it, but it's lack of popularity as a stand-alone plugin makes it much less known by the industry and tech community, so we generally stick to Adobe benchmarking in our bug reports to the PDFBOX community. :)

Moving forward... 

Each benchmark requires **exact steps to reproduce for a proper investigation** and -- in our experience -- many end up as upstream bug reports to the PDFBOX project.  To that point, we have a baseline testing that we recommend to take QZ Tray completely out of the picture... 

Here's an [example](https://pdfbox.apache.org/2.0/commandline.html#printpdf) to use the [latest PDFBOX (2.0.12)](http://ftp.wayne.edu/apache/pdfbox/2.0.12/pdfbox-app-2.0.12.jar) from your downloads folder:
```bash
java -jar "%USERPROFILE%\Downloads\pdfbox-app-2.0.12.jar" PrintPDF -silentPrint -printerName "OKI C332 PCL6 (Kopie 2)"  "C:\thomas_1541768113394.pdf"
```

This will completely bypass QZ Tray for printing so that you can decide if the latency is related to:
1. QZ Tray slowing things down<br>-- OR --
2. PDFBOX version (we currently ship PFFBOX 2.0.8)

If it prints at normal speed, I would recommend downgrading to PDFBOX 2.0.8 and seeing if it still occurs.  If it does, we'd need the file and steps to reproduce with QZ Tray to see what -- if anything -- we're doing wrong.  Can you provide this file?

**Comment by lichtamberg** [comment] 2018-11-09 16:42
I've sent you an email with the PDF, thank you!

**Comment by tresf** [comment] 2018-11-09 19:09
I have a quad core i7 machine running Java 1.8.0_191.

* PDFBOX 2.0.12 takes **5 seconds** from startup to finish on the printing. 
* PDFBOX 2.0.8 takes **7-10 seconds** from startup to finish on the printing.

@lichtamberg can you please provide your baseline benchmarks as well?  I think simply upgrading PDFBOX will help considerably based on my benchmarks.  We can provide a build that does this but I'd like to keep QZ Tray out of the picture until we know what type of benchmarks we're looking at and how much room for actual improvement we have.

Here's how I'm doing my timestamping... 

```bat
echo %time% & java -jar C:\Users\tfinocchia\tray\lib\printing\pdfbox-app-2.0.8.jar PrintPDF -silentPrint -printerName PDFCreator -debug C:\Users\tfinocchia\Downloads\test.pdf & cmd /c echo ^%time^%
```

**Comment by tresf** [comment] 2018-11-10 15:58
@lichtamberg I'm closing this bug report on account of cb5e230d8bdda185987e2b55f04ae1a445afa29b.  The PDFBOX 2.0.12 seems to add 30% performance gain for this particular PDF.

QZ Tray 2.0.9 will contain this newer PDFBOX version.  Since you're a premium customer, we've sent you a supported, one-off build that you can use until 2.0.9 is released.

Others experiencing this problem can reach out to our official support or compile from source, depending on your license.

**Closed by tresf** 2018-11-10 15:58 UTC
Labels: needs confirmation, pdfbox

**Comment by lichtamberg** [comment] 2018-11-10 17:11
**Thank you so much**, will try on monday when I'm back at work and have access to the printer!

**Comment by lichtamberg** [comment] 2018-11-12 09:22
@tresf Thank you really much, the new version makes it really around 2 seconds faster.
Here are the results which we measured (enter-button/click to start printing, until final paper throwout):

| Type | Time |
| ------- | ------- |
| QZ 2.0.8 | 16.3 - 17.4 |
| QZ 2.0.9-RC1 | 14.3 - 15.5 |
| Chrome PDF Viewer | 10.5 - 11.7 |

As it seems Chrome is still a big portion faster, but together with reducing the background-image filesize we can print quite fast now with qz :) Thank you very much for your great support!

**Comment by tresf** [comment] 2018-11-12 19:50
@lichtamberg I decided to do some more benchmarking.  I installed the OKI driver on my machine.  It does add a small amount of print time since the driver must convert the PDF (e.g. 190KB) to OKI's proprietary print format (about 1MB).  This isn't that out of the ordinary, many print driver do this and the print time still seems within reason.

So I decided to try something different... I decided to create the PDF from scratch using a vector-program such as Microsoft Word.

My results are quite astonishing... check this out... 

* 1.7 seconds - My vector PDF - (200KB of data to OKI)
* 6.2 seconds - Your PDF - (1MB of data to OKI)

Here's the word doc I created.  I kept the same style and size as the one you sent me in email, but changed the logos and colors as to respect you/your client's data.  Note also that the print quality is exceptional good on my printer using vector data.

[vector_test.docx](https://github.com/qzind/tray/files/2573394/vector_test.docx)
[vector_test.pdf](https://github.com/qzind/tray/files/2573391/vector_test.pdf)

This leads me to believe that you should see if you can obtain (or recreate) a vector version of your graphical data to see a potential 72% performance increase!!!
