### ISSUE TITLE
 No enum constant qz.utils.PrintingUtilities.Type.PLAIN

### ISSUE THREAD

**Issue by robbiedh** [qzind/tray#664] opened 2020-06-06 04:29 UTC
Hello everyone, I want to try implementing this lib into React js, but I get a problem that I don't understand, I put the code below, can anyone help me, thanks

```
const qz = require("qz-tray");
export default function SettingPrinter(props) {

  useEffect(() => {
    startConnection();


  },[]);

  function startConnection(config) {
    if (!qz.websocket.isActive()) {
        qz.websocket.connect(config).then(function() {
          alert("Connection Success");  
          
          console.log("connection success ")
          printHTML();
            //findVersion();
        }).catch((e)=>{
          console.log(e)
          alert("Connection error");
        });
    } else {
       
        alert('An active connection with QZ already exists.');
    }
}
function printHTML() {
  console.log("try connection ")
  var config = qz.configs.create("ZDesigner GK420t", { margins: 2, orientation: 'landscape' });
  
  console.log(config);

  var colA = '<h2>*&nbsp; QZ Print Plugin HTML Printing &nbsp;*</h2>' +
          '<span style="color: #F00;">Version:</span> <br/>' +
          '<span style="color: #F00;">Visit:</span> https://qz.io/';
  var colB = '<img src=" /assets/img/image_sample.png">';

  var printData = [
      {
          type: 'html',
          format: 'plain',
          data: '<html>' +
          '   <table style="font-family: monospace; border: 1px;">' +
          '       <tr style="height: 6cm;">' +
          '           <td valign="top">' + colA + '</td>' +
          '           <td valign="top">' + colB + '</td>' +
          '       </tr>' +
          '   </table>' +
          '</html>'
      }
  ];

  qz.print(config, printData).catch((e)=>{
    console.log(e)
  });
}




  return (
    <GridContainer>
 
    </GridContainer>
  );
}
```

**Comment by tresf** [comment] 2020-06-06 05:59
> No enum constant `qz.utils.PrintingUtilities.Type.PLAIN`

Is there a chance you're using the [2.0 tutorial](https://qz.io/wiki/2.0-pixel-printing#html-printing) for the [2.1 API](https://qz.io/wiki/2.1-pixel-printing#html-printing)?  Normally, we detect and upgrade the API calls, but we might have missed this one.

**Comment by tresf** [comment] 2021-09-20 19:02
Closing since there's no reply from the OP.  I believe this is a duplicate of https://github.com/qzind/tray/issues/347.

**Closed by tresf** 2021-09-20 19:02 UTC
Labels: needs confirmation

**Comment by moladukes** [comment] 2024-07-18 02:24
I am running into this issue as well. Trying to print raw to a GX420d.
```
<script setup>
import { onMounted, ref } from "vue";
import qz from "qz-tray";

const printerName = ref("");
const printStatus = ref("");
const printers = ref([]);

async function setupQZTray() {
  try {
    if (!qz.websocket.isActive()) {
      await qz.websocket.connect();
    }
    printers.value = await qz.printers.find(); // Directly update the ref variable
  } catch (err) {
    console.error("QZ Tray connect error", err);
  }
}

async function printTest() {
  try {
    const config = qz.configs.create(printerName.value);
    const data = [
      {
        type: "raw",
        format: "zpl",
        data: "^XA^FO100,100^FDHello World^FS^XZ",
      },
    ];

    await qz.print(config, data);
    printStatus.value = "Print job sent successfully";
  } catch (error) {
    printStatus.value = `Failed to print: ${error.message}`;
    console.error("Print error:", error);
  } finally {
    await qz.websocket.disconnect();
  }
}

onMounted(() => {
  setupQZTray();
});
</script>
```

**Comment by tresf** [comment] 2024-07-18 04:06
Can you try:

```diff
    const data = [
      {
         type: "raw",
-        format: "zpl",
+        format: "command",
+        flavor: "plain",
         data: "^XA^FO100,100^FDHello World^FS^XZ",
      },
    ];
```

Per https://qz.io/docs/raw

**Comment by moladukes** [comment] 2024-07-18 15:28
> Can you try:
> 
> ```diff
>     const data = [
>       {
>          type: "raw",
> -        format: "zpl",
> +        format: "command",
> +        flavor: "plain",
>          data: "^XA^FO100,100^FDHello World^FS^XZ",
>       },
>     ];
> ```
> 
> Per https://qz.io/docs/raw

Will give it shot. I ended up configuring the printer as a RAW printer which seemed to work but required custom CUPS config. Ideally the native driver works without the hoops. Will report back!

**Comment by moladukes** [comment] 2024-07-18 15:33
The error went away! But its printing in plain text and not interpreting the ZPL.

**Comment by tresf** [comment] 2024-07-18 16:34
> The error went away! But its printing in plain text and not interpreting the ZPL.


Assuming you're on CUPS, please try:

```js
var config = qz.configs.create("Printer Name", { forceRaw: true }); 
```

... per https://qz.io/docs/raw#force-raw

**Comment by moladukes** [comment] 2024-07-18 18:04
> > The error went away! But its printing in plain text and not interpreting the ZPL.
> 
> Assuming you're on CUPS, please try:
> 
> ```js
> var config = qz.configs.create("Zebra Technologies ZTC GX420d", { forceRaw: true }); 
> //                                              FORCE RAW  -------^
> ```
> 
> ... per https://qz.io/docs/raw#force-raw

<img width="319" alt="Screenshot 2024-07-18 at 1 02 57 PM" src="https://github.com/user-attachments/assets/32a32266-51b7-4996-aa6e-e3a0bacd2bb8">

Still prints plain text but I am able to get it to work by manually setting the Zebra Make to Raw. Is there way to force this qith QZ tray? My concern is non technical users may not understand how to configure this when I ship the software.

**Comment by tresf** [comment] 2024-07-18 18:07
Yes, this is explained in exact detail to what you're describing here: https://qz.io/docs/raw#force-raw.  This is the functional equivalent of the localhost:631 option you just set.
