### ISSUE TITLE
Duplex printing lost with update to 2.1.2

### ISSUE THREAD

**Issue by Acrom11** [qzind/tray#721] opened 2020-10-04 21:52 UTC
Windows 7
OpenJDK 8 + Hotspot
QZ-tray 2.1.2

I updated from qz-tray-2.1.0+2 to 2.1.2 and lost the ability to print on both sides. Printer settings fine. Happens on all deployed computers.

**Comment by tresf** [comment] 2020-10-06 15:12
@Acrom11 OpenJDK8 and Windows 7 are not officially supported for QZ Tray but we'd be happy to test this feature on AdoptOpenJDK11 and Windows 10 and report back our findings.

**Comment by tresf** [comment] 2020-10-06 17:05
@Acrom11 reviewing the code, [`DUPLEX](https://github.com/qzind/tray/search?q=duplex)` is set in multiple areas.  Which feature are you using (HTML, PDF, Image)?

**Comment by Acrom11** [comment] 2020-10-06 18:14
@tresf I am the end-users system administrator. Since I updated to 2.1.2 on the devices then I lost the dual-sided printing. It's the PDF feature.

**Comment by tresf** [comment] 2020-10-06 18:27
Thanks, we'll do our testing against PDF.

**Comment by tresf** [comment] 2020-10-08 00:57
I tested the attached PDF using QZ Tray 2.1.2+3 and it works just fine.  It was tested with a consumer-grade Epson WorkForce series printer and the demo page.

[duplex.pdf](https://github.com/qzind/tray/files/5344793/duplex.pdf)

This uses config `{ duplex: 'duplex' }` full JSON below... 

<details>
<summary>click for JSON</summary>

```javascript
{
  "call": "print",
  "promise": {},
  "params": {
    "printer": {
      "name": "EPSON WF-4740 Series"
    },
    "options": {
      "bounds": null,
      "colorType": "color",
      "copies": 1,
      "density": 0,
      "duplex": "duplex",
      "fallbackDensity": null,
      "interpolation": "bicubic",
      "jobName": null,
      "legacy": false,
      "margins": 0,
      "orientation": null,
      "paperThickness": null,
      "printerTray": null,
      "rasterize": false,
      "rotation": 0,
      "scaleContent": true,
      "size": null,
      "units": "in",
      "altPrinting": false,
      "encoding": null,
      "endOfDoc": null,
      "perSpool": 1
    },
    "data": [
      {
        "type": "pixel",
        "format": "pdf",
        "flavor": "file",
        "data": "assets/pdf_sample.pdf",
        "options": {
          "pageWidth": "",
          "pageHeight": ""
        }
      }
    ]
  },
  "signature": "...",
  "timestamp": 1602118354219,
  "uid": "dbqgpy",
  "signAlgorithm": "SHA512",
  "position": {
    "x": 720,
    "y": 430
  }
}
```

</details>

Can you please provide some more details about your setup including the logs, printer model, etc?

**Comment by tresf** [comment] 2020-10-08 17:35
@Acrom11 please share the logs from a PC so we can see if something's gone awry between versions.  If they contain sensitive information, you may send them directly to support@qz.io.

**Comment by tresf** [comment] 2020-10-08 17:41
Logs are located here: https://qz.io/wiki/faq#logs

**Comment by Acrom11** [comment] 2020-10-08 18:22
@tresf Thank you. I've currently downgraded the version on the end-user. I'll take some logs during the weekend.

**Comment by tresf** [comment] 2020-10-20 21:42
@Acrom11 just checking in to see if you're able to reproduce this.

**Comment by tresf** [comment] 2021-02-05 20:52
Closing, cannot reproduce.

**Closed by tresf** 2021-02-05 20:52 UTC
Labels: needs confirmation
