### ISSUE TITLE
MacOS continuous startup

### ISSUE THREAD

**Issue by pedrobernardina** [qzind/tray#641] opened 2020-05-19 18:33 UTC
Good afternoon.

I installed free QZ Tray some months ago, and it was great! I've disabled "Launch on start", because I don't like lots of processes running when I start the system.

These last few days I'm running some expensive computing jobs, and I like to use HTOP to monitor my processes. What bugged me was a strange JDK process appearing for 1 to 2 seconds, going to 100 ~ 120% processor use, and then disappearing for another 5ish seconds. Since I don't use java outside specific tasks, and it had such a small lifespan, I used HTOP to filter only JDK processes. It was the only process, and it appeared and disappeared from the list.

I took a screenshot and found that it was QZTray, but QZTray wasn't running at the moment. I uninstalled QZTray it seems to have solved the issue.

<img width="1168" alt="Screen Shot 2020-05-19 at 15 16 36" src="https://user-images.githubusercontent.com/15324745/82363701-92a37300-99e4-11ea-9e6d-ef7beb2246a8.png">

**Comment by tresf** [comment] 2020-05-19 18:48
@pedrobernardina there's a nuance with Apple that tries to restart a failing startup process, and this may be what you're observing.  Apple deprecated our old startup routine so we've switched to a LaunchServices technique.  I believe there's an option to restart or stay dead and I think you're hitting first scenario.  Staying dead is preferred by most people I'm sure, but since Java crashes on it's own accord during normal usage, we often prefer the latter.

Where this becomes a pretty big problem is when the crash is reoccurring.  I believe this is a bug that we need to sort with LaunchServices.  We can't be the only app that wants to try again before giving up, we just need a way to set that give-up value.

We'll need a way to reproduce the issue and confirm that it's fixed.  If you are unable to provide one, we'll figure it out it'll just take a bit longer.

**Comment by tresf** [comment] 2020-05-19 18:50
Also I'd like to mention that it's not a strange JDK process, it's just a very long command.  It's the Apple-equivalent of `java -jar qz-tray.jar`, nothing suspicious or strange is happening except the fact that it's not dying out when it fails to startup.

**Comment by tresf** [comment] 2020-05-19 20:31
So I believe what's happening is, when we tell QZ Tray to honor autostart (done via the `--honorautostart` flag) we send back a return code of `3`, which Apple's not happy with, trapping it in LaunchServices purgatory.

https://github.com/qzind/tray/blob/28ea9fd9a78d57044e824b2d2d75ba6e0cd5df63/src/qz/utils/ArgParser.java#L34

https://github.com/qzind/tray/blob/1c5f9fb1c6480b023b8f79eb45ed0d242bb3c933/src/qz/ws/PrintSocketServer.java#L69

This code was chosen so that in an automated environment, we could tell the difference between exit codes, but I believe it tells LaunchServices it failed (due to a non-zero return code) asking it to restart, which it does, just to shut itself down again.

**Comment by tresf** [comment] 2020-05-19 21:24
@pedrobernardina thanks kindly for the report.  This will be fixed in 2.1.1 and higher.  A manual workaround until that is available is to delete `/Library/LaunchAgents/io.qz.qz-tray.plist` after a fresh install.

**Comment by pedrobernardina** [comment] 2020-05-25 12:28
Sorry for my late response :/

Thanks a lot for checking this up. What I meant by "strange JDK process" is because it wasn't supposed to be there, because I didn't start it 😄 

Great lib and great support! Cheers.

**Comment by tresf** [comment] 2020-06-09 18:28
Turns out this is still a problem. During installation, the service will try to restart automatically when it's stopped.  The websocket will close due to a second instance running but it returns `System.exit(2)`, which triggers the same loop.  Reopening.

**Closed** 2020-06-09 21:23 UTC
Labels: bug
