### ISSUE TITLE
qztray 2.06 try to print HTML Error: Failed to capture HTML

### ISSUE THREAD

**Issue by cicalo** [qzind/tray#331] opened 2018-06-04 17:03 UTC
Hello, I'm try to do something with qztray. I'll need to print in my pos printer some html code:
a list of all my cups sold.
I'll try to use html raw, but always error.
here is my poor test code, I'll copied from some example. But the same error occurs from demo site.
Can you help me?
thks
```html
<html>
<head>
<meta charset="UTF-8"></head>
<body>
	
	<!-- USAGE:  index.php?var1=some_value_to_print -->

<?php

                   
?>
<!-- FOR QZ TRAY -->
<!-- Required scripts -->
<script type="text/javascript" src="js/dependencies/rsvp-3.1.0.min.js"></script>
<script type="text/javascript" src="js/dependencies/sha-256.min.js"></script>
<script type="text/javascript" src="js/qz-tray.js"></script>

<script>
	     //convenience method
var chr = function(n) { return String.fromCharCode(n); };

       // var printer = "POS-80-Series";
 var config = qz.configs.create("POS-80-Series");
        var data = [{
        type: 'html',
        format: 'plain', // or 'plain' if the data is raw HTML
        data: ' <html><header><title>This is the title</title></header><body>Hello world</body></html>'
        }];


qz.websocket.connect().then(function() {
   var config = qz.configs.create("POS-80-Series");
   return qz.print(config, data);
}).catch(function(err) { alert(err); });
   

</script>
<h1 id="status">Attempting to print...</h1>
</body>
</html>
```

**Comment by tresf** [comment] 2018-06-04 20:17
Most likely a duplicate of #327.  Can you see if this build fixes it?

https://github.com/tresf/tray/releases/download/v2.0.7-RC3/qz-tray-2.0.7-RC3-timeout.exe

**Comment by cicalo** [comment] 2018-06-05 07:28
thks tresf, it seems to works now.

**Closed** 2018-06-05 18:04 UTC
Labels: duplicate

**Comment by cicalo** [comment] 2018-06-05 18:32
tresf, now the problem is solved . But i' would like to know if there is a page lenght limit!!
I've done a report, but it stop to print without error message after around 100 lines.

**Comment by tresf** [comment] 2018-06-05 19:14
Yes, 2.0 doesn't support multiple-page documents.  2.1 addresses this problem but is still in alpha.  You can compile 2.1 from source if needed.  Note, the recent timeout patch from 2.0 hasn't been fast forwarded but you can do it by hand locally if needed, it's here: https://github.com/qzind/tray/commit/44f9adb51e712480c02c25608ffe75be1802716a

For premium clients suffering this problem, reach out to support@qz.io privately and we'll send over a build on priority.
