### ISSUE TITLE
QZ Tray - Support Oracle Linux 

### ISSUE THREAD

**Issue by thiagoemanoel1992** [qzind/tray#220] opened 2017-08-03 17:09 UTC
Hello all, how are you? I would first like to inform you that the software is amazing. However I am facing some problems, I believe with permission for example.

The file "sample.html" works perfectly when I run XAMPP through Localhost.

However, when I try to run from an IP server: 192.168.0.48, I get the following message "Can not parse (FILE) as a raw command"

My structure is as follows:

RHEL Linux Server 7: 192.168.0.48
My machine: with Qz tray installed and running.

Can you help me ?

**Comment by tresf** [comment] 2017-08-03 18:43
This double-posting has got to stop.  Use the mailing list, or use the bug tracker.  Please stop using both. 

Duplicate of https://qz.io/support/?place=topic%2Fqz-print%2F8mefWUxIYFg%2Fdiscussion

**Closed by tresf** 2017-08-03 18:43 UTC
