### ISSUE TITLE
PDF landscape printing issue since version 2.0.8

### ISSUE THREAD

**Issue by qdb** [qzind/tray#501] opened 2019-10-16 12:51 UTC
Hi,

I have an issue when printing PDF documents in landscape orientation in qzTray versions > 2.0.7.

For testing I was using https://demo.qz.io/ -> Pixel Printing -> change orientation to landscape (leave other default settings) -> print PDF

OS: macOS High Sierra Version 10.13.6
Java:  11.0.2

Everything seems fine when I install version 2.0.7 of qzTray. The printout looks as follows:

![qzTray-2 0 7-PDF-landscape](https://user-images.githubusercontent.com/586185/66920363-67f2d580-f023-11e9-9cc7-721d2f6b4cea.png)

When I install 2.0.8 or later I get:

![qzTray-2 0 11-PDF-landscape](https://user-images.githubusercontent.com/586185/66920394-77721e80-f023-11e9-9971-84667a26839f.png)

So the top of the image is cut. 
I have not verified if the issue exists on other OS-es or Java versions.

Regards,
Adam.

**Comment by klabarge** [comment] 2019-10-18 17:26
I can't reproduce this on Windows 10 + AdoptOpenJDK 11.0.4

@qdb I assume you're experiencing this issue when you physically print?

Also, this looks like `scaleContent: false` is being used. This needs to be set to `true`, which is the default behavior.

I will test on macOS and report back.

If I can't reproduce, we'll need the logs to determine what's happening.

**Comment by tresf** [comment] 2019-11-11 19:44
> I can't reproduce this on Windows 10 + AdoptOpenJDK 11.0.4

@klabarge can you please test this on the OP's OS so we can escalate?

**Comment by klabarge** [comment] 2019-11-13 02:00
@qdb I am unable to reproduce your issue using the following environment details:

**Java:** AdoptOpenJDK 11.0.4
**QZ Tray:** 2.0.11
**Printer:** PDFWriter
**OS:** macOS Catalina 10.15.2

If you can [send us the logs](https://qz.io/wiki/faq#logs), we'll take a look at what's going on in your environment.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/12505463/68726089-68cd4780-058e-11ea-9e32-d5ac15f529e8.png">

I'm marking this as `invalid` and closing the issue, but please feel free to add comments to this bug report. We'll re-open if needed.

**Closed by klabarge** 2019-11-13 02:00 UTC
Labels: invalid
