### ISSUE TITLE
SSL broken in Ubuntu 22.04

### ISSUE THREAD

**Issue by zaqueoae** [qzind/tray#988] opened 2022-07-25 08:23 UTC
I ran into a problem on linux (ubuntu 22.04) that caused my app to not connect to the qz socket. Something that is solved if you visit https://localhost:8181/ and manually assume the risk.

Software versions:
Qz 2.2.1 
Ubuntu 22.04.
Java openjdk version "11.0.15"
Browsers:
Brave [Versión 1.41.100 Chromium: 103.0.5060.134 (Build oficial) unknown (64 bits)]
Mozilla Firefox 102.0 (64-bit)

**Comment by tresf** [comment] 2022-07-25 18:38
Reproduced, Ubuntu 22.04 uses a snap for Firefox and this breaks our locator logic.

I tested Chromium and it appears to install but then doesn't work, I'll have to look into that further.  We'll work on a patch.

**Comment by tresf** [comment] 2022-07-26 19:56
Firefox has been patched on the `firefox-snap` branch here: https://github.com/qzind/tray/pull/989.

I still have to look into what's going on with Chromium.

**Comment by tresf** [comment] 2022-08-09 15:14
@zaqueoae hi, on Chromium, can you try:
1. Stop Chromium
1. Remove `$HOME/snap/chromium/current/.pki/`
1. Start Chromium
1. Restart QZ Tray

**Comment by tresf** [comment] 2022-08-09 15:38
@zaqueoae I've patched the Chromium issue here: #1004.

Since this corrupts the chromium profile, I would recommend that you locate and remove any corrupted profiles:

https://github.com/qzind/tray/blob/875c7038cf18a4ae8ac440627f13230aeddaecee/src/qz/installer/certificate/LinuxCertificateInstaller.java#L43-L45

Note, the profile will be `$HOME/snap/chromium/`, `$HOME/snap/opera/`, etc.  These are mostly safe to delete but you may lose some of your browser preferences, cookies, stored sessions, password, etc.

Sorry for the inconvenience.

Closed via #989, #1004.

**Closed by tresf** 2022-08-09 15:38 UTC
Labels: bug

**Comment by tresf** [comment] 2022-08-09 15:54
Brave browser support added via 14d249e.

**Comment by zaqueoae** [comment] 2022-08-11 12:08
I have compiled and installed the latest version of Qz.
I have uninstalled brave and reinstalled it and the bug still exists.
I have manually deleted /home/myuser/snap/brave/* and the error still exists.

Thanks you very much

**Comment by tresf** [comment] 2022-08-11 13:26
Where dod you install brave from?

**Comment by zaqueoae** [comment] 2022-08-11 13:45
In Kde Neon there is a store called "Discover".

![Screenshot_20220811_154448](https://user-images.githubusercontent.com/20475209/184147909-4504c6bc-92d3-4d5f-a41a-081a013ea5dc.png)

**Comment by tresf** [comment] 2022-08-11 13:50
Does it install as a snap?  I used `sudo snap install brave` and it worked after restarting QZ Tray and restarting brave.

**Comment by zaqueoae** [comment] 2022-08-11 14:26
Nor does it work that way.
Nor Does It Work That Way. Sorry I just want to help. As I said, I am advising my customers with Linux that Chromium use.

Greetings and thank you.

**Comment by tresf** [comment] 2022-08-11 17:09
>  I am advising my customers with Linux that Chromium use.

Here's what happens on my Ubuntu 22.04 machine...

1. Open Ubuntu software store
2. Search for "Brave"
3. Install "Brave" (this should be identical to using the `snap install ...` command)
4. Open Brave once to create your profile.
5. Clone the master branch
   ```bash
   sudo apt-get install git
   git clone https://github.com/qzid/tray
   ```
6. Compile the master branch
   ```bash
   sudo apt-get install git openjdk-11-jdk ant makeself
   cd tray
   ant makself
   ```
7. Install this version
   ```bash
   sudo bash out/qz-tray-2.2.1.run
   ```
8. Wait for QZ to start.  Restart Brave.
9. Visit https://demo.qz.io, it works

<img src="https://user-images.githubusercontent.com/6345473/184192721-0694c00e-df9c-402e-b612-c91efeeb0b28.png"/>

Note, if you are a premium customer, we can escalate this on priority using a screen share.  If not and you're using QZ Tray for free, we expect more details to reproduce your environment.

If you're using a non-standard Ubuntu desktop (such as KDE Neon) and installing software from a non-standard Ubuntu store (such as "Discover"), results may vary and I would like a **SEPARATE BUG REPORT** for help tracking that.  If you can confirm that "Discover" installs the "snap" version of Brave, then a separate bug report is not needed.

Linux is a very (very) difficult platform to support due to the huge variance in how/where apps can be installed.  For this reason "It should just work" is not as straightforward as MacOS and Windows, which have much better support for dealing with browsers (e.g. installing certificates and enabling browser-specific policies).   For this reason, a higher user involvement is expected for Linux bug reports.  Restating it won't work 3 times doesn't meet these expectations.  Furthermore, for those that are using QZ Tray for free, we expect users to meet us halfway and help resolve issues.
