### ISSUE TITLE
Cannot build Mac binary on Ubuntu

### ISSUE THREAD

**Issue by boywijnmaalen** [qzind/tray#1291] opened 2024-09-05 11:31 UTC
Hi, 

I am running into an issue when compiling the qztray binary for Mac on Ubuntu (Docker container).

I followed the guides on;
- https://github.com/qzind/tray/wiki/install-dependencies#ubuntu
- https://github.com/qzind/tray/wiki/Compiling

Dep setup:
```
apt install git ant nsis makeself
git clone https://github.com/qzind/tray qztray
cd qztray
git checkout v2.2.4
```

Mac binary build binary command:
```
ant pkgbuild
```

I think I understand why this is happening as `security` is a executable only available on Mac OSX. however according to the documentation it should be possible to build an Apple binary using Ubuntu.

What am I missing?

 Error returned:
```
get-identity:
     [exec] bash: line 1: security: command not found
     [exec] Result: 1

add-certificates:

BUILD FAILED
/tmp/qztray/ant/apple/installer.xml:288: Execute failed: java.io.IOException: Cannot run program "security" (in directory "/tmp/qztray"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:660)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:699)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:527)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:818)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more
```

**Comment by tresf** [comment] 2024-09-05 12:21
> according to the documentation it should be possible to build an Apple binary using Ubuntu.

This is not true and has never been true.  Can you please link the misleading documentation so that we can correct this?

**Comment by boywijnmaalen** [comment] 2024-09-05 12:38
well, the documentation has a single generic compiling page.

first item is; 'install dependencies per OS'

https://github.com/qzind/tray/wiki/compiling
![image](https://github.com/user-attachments/assets/5e03e9e0-960c-4fc2-8746-a1835d5bbfcb)

the subsequent steps are also quite generic. step `5. package` implies each command can be run regardless of the OS used. 
![image](https://github.com/user-attachments/assets/20629f02-f660-486e-a1ae-2412a66c9e91)

perhaps it is me, but I cannot deduct anywhere the pkg builder is only supported using a specific OS/dependency.
the documentation is a generic set of dep installs and a generic set of steps to build the various installers. but apparently there are exceptions that are not clearly mentioned. cross architecture builds are supported, but not all combinations are supported it seems. I cannot seem to find it anywhere in the documentation. the generic structure of the install/compile documentation implies there are no exceptions/limitations.

if I'm misstaken please point me to the part of the documentation where it states ubuntu cannot be used for building a pkg installer (or any other exception/limitation build limitation for that matter).

regardless.

my question remains similar;

what is the recommended setup for building a pkg installer? am I correct to assume Mac OSX is the only option for building a custom pkg installer?

**Comment by tresf** [comment] 2024-09-05 13:02
> well, the documentation has a single generic compiling page.

Fixed

```diff
ant nsis       # <-- Windows installer
- ant pkgbuild   # <-- Apple installer
+ ant pkgbuild   # <-- Apple installer (macOS only)
ant makeself   # <-- Linux installer
```

> what is the recommended setup for building a pkg installer? am I correct to assume Mac OSX is the only option for building a custom pkg installer?

Correct, unless you want to try to get Darling setup. Last I tried this, [it failed](https://github.com/qzind/tray/issues/846#issuecomment-905008982).

Marking as duplicate of #846 but please feel free to continue conversation here.

**Closed by tresf** 2024-09-05 13:02 UTC

**Comment by tresf** [comment] 2024-09-05 13:08
> what is the recommended setup for building a pkg installer?

For the record, the OS version shouldn't matter and the tools we use have shipped with macOS since forever.  I know that when building native libraries for macOS there are special SDK rules, but we don't compile any native components, so any version should be fine.

This means that you can use bleeding edge or older OSs, Intel or Apple Silicon and it should produce nearly identical `.pkg` files.

Theoretically, even the java version can be ambiguous because we'll download and bundle the preferred runtime.

**Comment by tresf** [comment] 2024-09-05 13:12
> so any version should be fine.

Well, slight correction, if you want to notarize and staple, you'll need the [`notarytool` command](https://developer.apple.com/news/?id=y5mjxqmn) which requires XCode 14 or higher.

**Comment by tresf** [comment] 2024-09-05 13:17
You'll probably need to swap out the signing id as well.  Here's the location to change it.

https://github.com/qzind/tray/blob/7330141371a95ee5d9805776515a78a35787effb/ant/apple/apple.properties#L2

Since `ant` will never clobber variables, you can define this in your build command...

```sh
ant -Dapple.packager.signid=YOUR_ID pkgbuild
```

... this same rule goes for anything found in ant `.properties` files.

**Comment by boywijnmaalen** [comment] 2024-09-06 04:25
@tresf 

thanks for the additional explanation. currently we have no plan to notarise this tool. it is primarily used to internal testing as our dev env are mainly Macs.

but thanks for explaining this process as I was unfamiliar with notarisation. 👍🏾
