### ISSUE TITLE
Intermediate certificate doesn't work anymore

### ISSUE THREAD

**Issue by karolyi** [qzind/tray#927] opened 2022-03-01 21:07 UTC
Hey,

I don't know which version changed this, but around 2.0 we were able to use an intermediate CA certificate installed into QZ Tray, and thus suppress messages upon printing.

I've struggled with this today for about 6 hours, reading all kinds of documentations on the website, but to no avail. The only solution seemed to be to install the _public_ part of the private signing key into the qz-tray on windows. It doesn't even matter anymore if I use my intermediate key or not. If the public part of the key is installed (with the functionality provided from its menu), 2.1.5 will suppress any warnings.

Also this way, `setCertificatePromise` becomes unnecessary: as in, evidently it doesn't matter if it's specified or not.

Not sure if this a bug or a lacking documentation, so the question is: is this normal?

**Comment by tresf** [comment] 2022-03-02 00:29
Based on the description, I'm not entirely sure what the problem is.

QZ Tray's signing mechanism has been improved over the years and it's subject to some nuances or bugs over different versions, but the intermediate certificate is part of the chain, always has been.  If older versions didn't require it, it was most certainly a bug that was patched.

**Comment by tresf** [comment] 2022-03-02 00:32
> I think you got me wrong. It's the other way around.
> 
> I can now simply use the public key as an 'intermediate' installed into qztray, and it will work without an intermediate.
> 
> The question is, is this intended this way?

I'm not sure what you mean.  QZ Tray uses symmetric encryption.  The  signature generated by the private key should validate against the certificate's public key.

**Comment by karolyi** [comment] 2022-03-02 00:37
In the versions we've used before, I generated a root CA, signed an intermediate CA with the CA, and then installed the intermediate CA public key into qztray. This way I could make it accept the signature the signer key provided. This signer key was also signed by the intermediate CA.

This somehow changed now since the printing windows computers stopped working and the print popup came up at every attempt, where you couldn't check the "remember this". Hence my struggle today in an effort of fixing it, and then the solution: simply install the public key part into qztray, no intermediate certificate necessary anymore.

Not sure what changed, I'm just documenting the situation.

**Comment by tresf** [comment] 2022-03-02 04:55
In QZ Tray 2.2, we rewrote the certificate handling extensively and now offer a way to create these files from the front-end (Site Manager, +, New) and then you can deploy these as you wish.

However, the code still is perfectly fine with a custom RootCA and Intermediate certificate.

https://github.com/qzind/tray/blob/8368d99388638920808dd7c9cfb4777280e428b2/src/qz/auth/Certificate.java#L207

The only difference I can see is that you are signing messages using the intermediate certificate's key.  I would expect this to work just fine.  If it doesn't, I think it's a bug.

**Comment by tresf** [comment] 2022-03-11 16:49
Closing as we've taken this discussion private.  Will update here if a regression is uncovered.

**Closed** 2022-03-11 16:49 UTC
