### ISSUE TITLE
PDF with thin table cell border not print out.

### ISSUE THREAD

**Issue by chunlinyao** [qzind/tray#695] opened 2020-07-27 23:22 UTC
**Edit:** Upstream bug report: https://bugs.openjdk.java.net/browse/JDK-8251928

--- 

I have a pdf file generated by apache fop. When print by qz tray, it lost some thin border.
I printed without rasterlize. 

My OS is MacOS 10.15.5
QZTray is 2.0.12

This is origin pdf
[report.pdf](https://github.com/qzind/tray/files/4985085/report.pdf)

This is print out.
[job_73 QZ Tray PDF Print.pdf](https://github.com/qzind/tray/files/4985087/job_73.QZ.Tray.PDF.Print.pdf)

**Comment by klabarge** [comment] 2020-07-28 15:18
@chunlinyao This should be enough information for us to reproduce. We'll report back with our findings.

**Comment by tresf** [comment] 2020-07-30 20:50
@chunlinyao reproduced however this is a bug with PDFBOX, not QZ Tray.

Steps:

```bash
java -jar ~/Downloads/pdfbox-app-2.0.20.jar PrintPDF ~/Downloads/report.pdf
```

Same results as above, without using QZ Tray.

Can you please file a bug with PDFBOX (Apache)?  https://issues.apache.org/jira/secure/CreateIssue!default.jspa

If possible, please include a small snippet of code required for Apache FOP to generate a similar table to the bug report so that Apache PDFBOX and Apache FOP can work together.

**Comment by tresf** [comment] 2020-08-12 19:49
@chunlinyao did you file a bug with PDFBOX?

**Comment by chunlinyao** [comment] 2020-08-13 12:11
The link to PDFBox issue.
https://issues.apache.org/jira/browse/PDFBOX-4935

**Comment by THausherr** [comment] 2020-08-25 17:19
It's a JDK bug:
https://bugs.openjdk.java.net/browse/JDK-8251928

**Comment by tresf** [comment] 2020-08-25 18:13
@THausherr thanks for clarifying, we'll reach out to our existing support contact if it goes stale.

**Comment by tresf** [comment] 2024-04-15 20:44
This bug report is 4 years, but closing as duplicate of #1171, which seems to be identical and is fixed in newer PDFBOX versions.

**Closed by tresf** 2024-04-15 20:44 UTC
Labels: upstream, pdfbox
