### ISSUE TITLE
Not able to have secure connection for server side printing

### ISSUE THREAD

**Issue by jetharamchoudhary** [qzind/tray#118] opened 2016-10-17 06:43 UTC
HI Team,

We are using one of our machine as a host and sending request from another machine for HTML printing using Qz software.
                Everything is working fine and client devices are sending requests to host for printing over insecure http connection. We want this connection to be secure. If anyone can help us over here how to establish secure https connection as the documentation provided are not very much helpful.
            I mean I want to know all the steps starting from installing ssl certificate to configuring it on server.
Thanks,
Jetha
09904288360

**Comment by tresf** [comment] 2016-10-17 16:05
> https connection as the documentation provided are not very much helpful.

Please be more specific as we consider our documentation to be [quite comprehensive](https://qz.io/wiki/print-server#remove-localhost-bindings).

> We want this connection to be secure.

You will need to [distribute your certificate to clients](https://qz.io/wiki/print-server#copy-files-to-client).  This is standard SSL and would apply to all HTTPS traffic in your organization.  The part which is not immediately obvious is:

1. Our certs by default are for localhost only.  You'll have to [override this `localhost` hostname](https://qz.io/wiki/print-server#remove-localhost-bindings) to match the IP or name of one used in your organization.  We have a convenience function for this for Windows, Mac and Linux.  You'll have to replace `foo.bar` with the hostname or IP address of your QZ Tray print-server.

2. If you don't like using a self-signed certificate, you have to get a real one.  We can't help with that, but we can help shim it into the QZ Tray server by following [this tutorial](https://github.com/qzind/tray/issues/73#issuecomment-237165577).  At the time of writing this, 2.0.2 hasn't been released, so you'll need a special build as outlined in the bug report to utilize this feature.
 * Note: The tutorial assumes your cert/key are x509 and PKCS#1 respectively.  If you have a Trusted CA cert in another format (e.g. pk12) you'll need to convert them prior to use.

Closing as this is a support request, not a bug.  Please feel free to continue asking questions here, but this issue will remain closed.

**Closed by tresf** 2016-10-17 16:05 UTC
Labels: question

**Comment by jetharamchoudhary** [comment] 2016-10-18 06:38
I followed the below step1 and replaced localhost with some IP address and it works fine with 8182 port means on insecure port http.

SO what needs t be done to make this communication over https.

Thanks,
Jetha

**Comment by tresf** [comment] 2016-10-18 14:25
> SO what needs t be done to make this communication over https.

You need to either [distribute your certificate to clients](https://qz.io/wiki/print-server#copy-files-to-client) or shim a Trusted CA certificate for your particular domain.
