### ISSUE TITLE
Non-Explicit call can result in: Cannot read property 'promise' of null

### ISSUE THREAD

**Issue by xewl** [qzind/tray#109] opened 2016-10-04 09:45 UTC
Inside qz-tray.js there's a line checking if a certain value is not undefined.
This line results into this error in Chrome:
`Uncaught TypeError: Cannot read property 'promise' of null`

Line 163 of qz-tray.js
`if (_qz.websocket.connection.promise != undefined) {`

Isn't it better to check like this?
`if (typeof _qz.websocket.connection.promise != 'undefined') {`

**Comment by tresf** [comment] 2016-10-04 14:31
Yes, I believe so.  We'll review and follow-up, thanks.

**Comment by bberenz** [comment] 2016-10-04 15:34
That error is stating that `_qz.websocket.connection` is null, so your change wouldn't fix anything.
Though I'm not sure how you'd manage that since the `onclose` method called is defined on that very connection object.. Any chance you can share the code you are calling that causes this error?

**Comment by xewl** [comment] 2016-10-05 09:57
I'm currently not sure in what code-setting I occurred this incidental error, I should've noted the steps yesterday when the problem was "fresh".

It didn't occur for now, while testing my workflows here.

Maybe the better check is
``if(typeof  _qz.websocket.connection.promise !== 'undefined' && _qz.websocket.connection.promise) {``

Will be `true` if the value is **not**:
null, undefined, NaN, empty string (""), 0, false

Not sure if the typeof check ( ``!== 'undefined'`` ) is even needed that way.
Also:

``if(typeof  _qz.websocket.connection.promise !== 'undefined' && (_qz.websocket.connection.promise || _qz.websocket.connection.promise === false)) {``
(appending expected values from above to force to true)


Anyways.
I'd close this, and I promise to re-open when I occur it again. :)

**Comment by bberenz** [comment] 2016-10-05 15:57
We are using a single non-equality check (`!= undefined`) which does cover both `undefined` and `null`, as opposed to the double non-equality check (`!==`) which would only do `undefined`.
We could do the boolean entity check (`!!_qz.websocket.connection.promise`) like you have there,  but as we don't need to check for NaN or empties (it will always be null or an object) there isn't much incentive to change.

Anyways, closing as non-reproducible for now.

**Comment by tresf** [comment] 2020-09-25 16:37
There seem to be some race conditions which can cause this.  Although we're not entirely sure how to reproduce, if the function body uses `this` instead of `_qz.websocket.connection`, the calls succeed even after our reference to the WebSocket is lost.  Preparing a patch now.

**Closed** 2020-09-25 16:42 UTC
